### ISSUE TITLE
TypeError: polyfillDispose is not a function

### ISSUE THREAD

**Issue by Xaliks** [discordjs/discord.js#10134]
### Which package is this bug report for?

discord.js

### Issue description

When I updated discord.js to the latest dev version, I get an error
```
C:\Users\Xaliks\Desktop\example\node_modules\discord.js\src\index.js:6
polyfillDispose();
^

TypeError: polyfillDispose is not a function
    at Object.<anonymous> (C:\Users\Xaliks\Desktop\example\node_modules\discord.js\src\index.js:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\Xaliks\Desktop\example\index.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
```
![image](https://github.com/discordjs/discord.js/assets/64866197/d366df9a-e6e6-4691-a0f5-b69910a46b12)

### Code sample

```typescript
require("discord.js");
```

### Versions

- discord.js@14.15.0-dev.1707869366-543d61737
- Node JS v20.11.0
- Windows 10 64-bit (10.0.19045)

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

### I have tested this issue on a development release

543d61737

**Comment by Jiralite** [comment]
Please override @discordjs/util to a development release as well.
