### ISSUE TITLE
crashing after message deletion

### ISSUE THREAD

**Issue by Daijobou** [discordjs/discord.js#10313]
### Which package is this bug report for?

discord.js

### Issue description

- Type/Submit !testdelete
- Message is successfully deleted
- Bot crash after deletion with:

at module.exports [as MESSAGE_DELETE] (/home/mybot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_DELETE.js:4:32) at WebSocketManager.handlePacket (/home/mybot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31) at WebSocketManager. (/home/mybot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12) at WebSocketManager.emit (/home/mybot/node_modules@vladfrangu/async_event_emitter/dist/index.cjs:282:31) at WebSocketShard. (/home/mybot/node_modules@discordjs/ws/dist/index.js:1190:51) at WebSocketShard.emit (/home/mybot/node_modules@vladfrangu/async_event_emitter/dist/index.cjs:282:31) at WebSocketShard.onMessage (/home/mybot/node_modules@discordjs/ws/dist/index.js:1005:14)

### Code sample

```typescript
client.on('messageCreate', message => {
    if (message.content === '!testdelete')
    {
        message.delete().then(() => {
        });
    }
});
```

### Versions

discord.js@14.15.2
Node.js v21.7.3.
AlmaLinux 8.10

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
Can you provide the error message (and never omit it)?

**Comment by Daijobou** [comment]
I don't understand, the error message is already in "Issue description".

**Comment by Jiralite** [comment]
That is not an error message. That is the stack trace. The error message will be above the stack trace and is a crucial piece of information.

**Comment by Daijobou** [comment]
Oh there was more. I didn't know that, because I used "journalctl -u mybot -f" but must use "journalctl -u mybot -f -n 100" for much more lines. Thanks, this hint helped me a lot!

**Comment by Jiralite** [comment]
In the future, it would be wise to share what was wrong in case people stumble across the same issue.
