### ISSUE TITLE
oops

### ISSUE THREAD

**Issue by rusvet18** [discordjs/discord.js#10336]
### Which package is this bug report for?

discord.js

### Issue description

embed not working
error logs:
Uncaught TypeError TypeError: isJSONEncodable is not a function
    at <anonymous> (c:\Users\rusve\node_modules\discord.js\src\structures\MessagePayload.js:202:9)
    at resolveBody (c:\Users\rusve\node_modules\discord.js\src\structures\MessagePayload.js:201:36)
    at send (c:\Users\rusve\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:172:61)
    at <anonymous> (c:\Users\rusve\Downloads\ytdl-music-bot\src\index.js:49:17)
    at processTicksAndRejections (internal/process/task_queues:95:5)
No debugger available, can not send 'variables'
Process exited with code 1

### Versions

discord.js - 14.15.3
node.js - v22.2.0
typescript - 5.4.5

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Channel, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildModeration, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent, GuildScheduledEvents, AutoModerationConfiguration, AutoModerationExecution, GuildMessagePolls, DirectMessagePolls

**Comment by Jiralite** [comment]
Please make your way over to the [Discord server](https://discord.com/invite/djs) for help. This issue is lacking and you'll have a better experience there.
