### ISSUE TITLE
ReferenceError: ReadableStream is not defined

### ISSUE THREAD

**Issue by rico345100** [discordjs/discord.js#10368]
### Which package is this bug report for?

discord.js

### Issue description

Trying to make a bot. Followed the official tutorial. Run index.js throws ReferenceError: ReadableStream is not defined.
```
F:\Development\node\discord_bot_test\node_modules\@discordjs\rest\node_modules\undici\lib\web\fetch\response.js:530
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (F:\Development\node\discord_bot_test\node_modules\@discordjs\rest\node_modules\undici\lib\web\fetch\response.js:530:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (F:\Development\node\discord_bot_test\node_modules\@discordjs\rest\node_modules\undici\lib\web\fetch\index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

Node version 16.11.0. LTS version failed to install. Node 18 doesn't work too. Dafuq.

### Code sample

```typescript
const { Client, Events, GatewayIntentBits } = require('discord.js');
const { token } = require('./config.json');

const client = new Client({ intents: [GatewayIntentBits.Guilds] });

client.once(Events.ClientReady, readyClient => {
    console.log(`Ready! Logged in as ${readyClient.user.tag}`);
});

client.login();
```

### Versions

discord.js@14.15.3
node@16.11.0
Windows 10

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by SuperchupuDev** [comment]
update node, discord.js requires node >=18.0.0

**Comment by rico345100** [comment]
PS F:\Development\node\discord_bot_test> nvm use 18
18.0.0
Now using node v18.0.0 (64-bit)
PS F:\Development\node\discord_bot_test> node -v
v18.0.0
PS F:\Development\node\discord_bot_test> npm install
npm ERR! Unexpected token '.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2024-06-30T22_12_51_556Z-debug-0.log

Not work

**Comment by Jiralite** [comment]
If you need help, visit the [Discord server](https://discord.gg/djs) and ask around in the help channels.
