### ISSUE TITLE
Unhandled 'error' event emitted

### ISSUE THREAD

**Issue by Pyr33x** [discordjs/discord.js#10372]
### Which package is this bug report for?

discord.js

### Issue description

I've been trying to login to the bot client and faced this error:
`~/projects/raytop/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:278 throw err;
Error: Unhandled 'error' event emitted, received [object Object]
    at WebSocketShard.emit`
Then I decided to try a template so maybe I could find a way: 
1. clone this [Sapphire Typescript Starter](https://github.com/sapphiredev/examples/tree/main/examples/with-typescript-starter) which using sapphire framework on top of the `discord.js`
2. try running `pnpm start` and you'll see `~/projects/raytop/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:278 throw err; Error: Unhandled 'error' event emitted, received [object Object] at WebSocketShard.emit`
This issue isn't coming from sapphire, cause I've even tried on discord.js itself and got the same result.

### Code sample

```typescript
import './lib/setup';

import { LogLevel, SapphireClient } from '@sapphire/framework';
import { GatewayIntentBits } from 'discord.js';

const client = new SapphireClient({
	defaultPrefix: '!',
	caseInsensitiveCommands: true,
	logger: {
		level: LogLevel.Debug
	},
	intents: [GatewayIntentBits.DirectMessages, GatewayIntentBits.GuildMessages, GatewayIntentBits.Guilds, GatewayIntentBits.MessageContent],
	loadMessageCommandListeners: true
});

const main = async () => {
	try {
		client.logger.info('Logging in');
		await client.login();
		client.logger.info('logged in');
	} catch (error) {
		client.logger.fatal(error);
		await client.destroy();
		process.exit(1);
	}
};

void main();
```

### Versions

- Discord.js: `^14.14.1`
- @Sapphire/framework: `^5.0.7`
- Typescript: `~5.4.5`

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

User

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, DirectMessages, MessageContent

**Comment by didinele** [comment]
Hi. Can you provide a sample without sapphire, please? It makes debugging harder for me.

Possibly related: #10371

**Comment by didinele** [comment]
Hey there. With the code snippet from the website, I am unable to reproduce your issue.

That being said, I did notice that in your original sapphire example, you provided more intents. Indeed, one of them is `MessageContent`, which you are not allowed to use by default. This *does* cause an error, but I find it extremely strange that you're getting an unhandled error event, here's what it looks like for me if I run this code snippet with a bot that doesn't have that intent enabled:

```ts
import { Client, GatewayIntentBits } from "discord.js";
const client = new Client({
  intents: [
    GatewayIntentBits.DirectMessages,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.Guilds,
    GatewayIntentBits.MessageContent,
  ],
});

client.on("ready", () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on("interactionCreate", async (interaction) => {
  if (!interaction.isChatInputCommand()) return;

  if (interaction.commandName === "ping") {
    await interaction.reply("Pong!");
  }
});

client.login(TOKEN);
```

Error:
```
❯ node --enable-source-maps whatever.js
/home/dd/Documents/work/js-playground/node_modules/@discordjs/ws/src/ws/WebSocketShard.ts:815
                                        error: new Error('Used disallowed intents'),
                                               ^


Error: Used disallowed intents
    at WebSocketShard.onClose (/home/dd/Documents/work/js-playground/node_modules/@discordjs/ws/src/ws/WebSocketShard.ts:815:13)
    at WebSocket.connection.onclose (/home/dd/Documents/work/js-playground/node_modules/@discordjs/ws/src/ws/WebSocketShard.ts:203:14)
    at callListener (/home/dd/Documents/work/js-playground/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/home/dd/Documents/work/js-playground/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emitClose (/home/dd/Documents/work/js-playground/node_modules/ws/lib/websocket.js:265:10)
    at TLSSocket.socketOnClose (/home/dd/Documents/work/js-playground/node_modules/ws/lib/websocket.js:1291:15)
    at TLSSocket.emit (node:events:531:35)
    at node:net:337:12
    at TCP.done (node:_tls_wrap:657:7)

Node.js v21.5.0```

Can you do the following?
1. Attach `client.on('debug', console.log);`
2. Run your program with `node --enable-source-maps ./path/to/program.js`
3. Confirm if you have enabled the intent or not

**Comment by Pyr33x** [comment]
Alright buddy.
1. I've attached `client.on('debug', console.log);` and got this result
```
Provided token: MTI1NzQyNTA5ODQ1ODAwOTcyMQ.G8CdyW.**************************************
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 1000
[WS => Shard 0] Connecting to wss://gateway.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
~/projects/tests/node_modules/@vladfrangu/async_event_emitter/src/index.ts:449
                        throw err; // Unhandled 'error' event
                        ^

Error: Unhandled 'error' event emitted, received [object Object]
    at WebSocketShard.emit 

```
2. Got the same result
3. Yeah, I've already enabled intents

**Comment by Pyr33x** [comment]
You wanna check out the full log?

**Comment by didinele** [comment]
Yes. Naturally.

**Comment by Pyr33x** [comment]
there u go
```
~/projects/tests/node_modules/@vladfrangu/async_event_emitter/src/index.ts:449
                        throw err; // Unhandled 'error' event
                        ^


Error: Unhandled 'error' event emitted, received [object Object]
    at WebSocketShard.emit (~/projects/tests/node_modules/@vladfrangu/async_event_emitter/src/index.ts:445:16)
    at WebSocketShard.onError (~/projects/tests/node_modules/@discordjs/ws/src/ws/WebSocketShard.ts:719:8)
    at WebSocket.connection.onerror (~/projects/tests/node_modules/@discordjs/ws/src/ws/WebSocketShard.ts:199:9)
    at callListener (~/projects/tests/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onError (~/projects/tests/node_modules/ws/lib/event-target.js:230:9)
    at WebSocket.emit (node:events:520:28)
    at emitErrorAndClose (~/projects/tests/node_modules/ws/lib/websocket.js:1035:13)
    at ClientRequest.<anonymous> (~/projects/tests/node_modules/ws/lib/websocket.js:880:5)
    at ClientRequest.emit (node:events:520:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9) {
  context: {
    error: Error: connect ETIMEDOUT 10.10.34.36:443
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
      errno: -4039,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '10.10.34.36',
      port: 443
    }
  }
}
```

**Comment by Pyr33x** [comment]
Thank you anyways buddy. <3
