### ISSUE TITLE
ws Gateway Close error messages are not properly logged

### ISSUE THREAD

**Issue by imnaiyar** [discordjs/discord.js#10371]
### Which package is this bug report for?

ws

### Issue description

- Log into your bot
- Disable privilaged intent from dev portal
- Get unhandled "error"

The error recieved 
<details><summary>The full error</summary>
<p>

```
err: {
      "type": "Error",
      "message": "Unhandled 'error' event emitted, received [object Object]",
      "stack":
          Error: Unhandled 'error' event emitted, received [object Object]
              at WebSocketShard.emit (C:\Users\admin\Desktop\Coding\discord-js-bot\node_modules\@vladfrangu\async_event_emitter\dist\index.cjs:276:19)
              at WebSocketShard.onClose (C:\Users\admin\Desktop\Coding\discord-js-bot\node_modules\@discordjs\ws\dist\index.js:1146:14)
              at connection.onclose (C:\Users\admin\Desktop\Coding\discord-js-bot\node_modules\@discordjs\ws\dist\index.js:686:17)    
              at callListener (C:\Users\admin\Desktop\Coding\discord-js-bot\node_modules\ws\lib\event-target.js:290:14)
              at WebSocket.onClose (C:\Users\admin\Desktop\Coding\discord-js-bot\node_modules\ws\lib\event-target.js:220:9)
              at WebSocket.emit (node:events:518:28)
              at WebSocket.emitClose (C:\Users\admin\Desktop\Coding\discord-js-bot\node_modules\ws\lib\websocket.js:265:10)
              at TLSSocket.socketOnClose (C:\Users\admin\Desktop\Coding\discord-js-bot\node_modules\ws\lib\websocket.js:1291:15)      
              at TLSSocket.emit (node:events:530:35)
              at node:net:337:12
      "context": {
        "error": {}
      }
    }
```
</p>
</details> 

This only happens on the latest djs version
on closer inspection, this code in https://github.com/discordjs/discord.js/blob/ab8bf0f4d2a50cd85cf8b2aa1d4e2ea93872807b/packages/ws/src/ws/WebSocketShard.ts#L894 seems to be the issue
```ts
	this.emit(WebSocketShardEvents.Error, {
					error: new Error('Used disallowed intents'),
				});
				return this.destroy({ code });
			}
			
```

changing it to this seems to fix this 
```ts
	this.emit(WebSocketShardEvents.Error, new Error('Used disallowed intents'));
				return this.destroy({ code });
			}
```

i'd imagine other Gateway Close error logs would be the same too but I didn't test those out
I'd open a pr about this but i'm not sure if this is the correct fix

### Versions

- discordjs 14.15.3

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by didinele** [comment]
Hi. Does this not happen on 14.15.2?

**Comment by imnaiyar** [comment]
> Hi. Does this not happen on 14.15.2?
> 
> Also, please provide a complete reproducible code sample.

This happen on the lates version which is v14.15.3, also for code sample there is none ig,
You just have to have subscribe to a Privileged Intent through client constructor (but disabled on dev portal), then try to login, the error thrown should have "Using disallwed intent" but it logs the one I sent above

**Comment by Idris1401** [comment]
```js
H:\IdrisAll\Dev\Obito\node_modules\@vladfrangu\async_event_emitter\dist\index.cjs:276
      const err = new Error(`Unhandled 'error' event emitted, received ${stringifiedError}`);
                  ^

Error: Unhandled 'error' event emitted, received [object Object]
    at WebSocketShard.emit (H:\IdrisAll\Dev\Obito\node_modules\@vladfrangu\async_event_emitter\dist\index.cjs:276:19)
    at WebSocketShard.onClose (H:\IdrisAll\Dev\Obito\node_modules\@discordjs\ws\dist\index.js:1148:14)
    at connection.onclose (H:\IdrisAll\Dev\Obito\node_modules\@discordjs\ws\dist\index.js:686:17)
    at callListener (H:\IdrisAll\Dev\Obito\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onClose (H:\IdrisAll\Dev\Obito\node_modules\ws\lib\event-target.js:220:9)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emitClose (H:\IdrisAll\Dev\Obito\node_modules\ws\lib\websocket.js:265:10)
    at TLSSocket.socketOnClose (H:\IdrisAll\Dev\Obito\node_modules\ws\lib\websocket.js:1291:15)
    at TLSSocket.emit (node:events:531:35)
    at node:net:338:12 {
  context: {
    error: Error: Used disallowed intents
        at WebSocketShard.onClose (H:\IdrisAll\Dev\Obito\node_modules\@discordjs\ws\dist\index.js:1149:18)
        at connection.onclose (H:\IdrisAll\Dev\Obito\node_modules\@discordjs\ws\dist\index.js:686:17)
        at callListener (H:\IdrisAll\Dev\Obito\node_modules\ws\lib\event-target.js:290:14)
        at WebSocket.onClose (H:\IdrisAll\Dev\Obito\node_modules\ws\lib\event-target.js:220:9)
        at WebSocket.emit (node:events:519:28)
        at WebSocket.emitClose (H:\IdrisAll\Dev\Obito\node_modules\ws\lib\websocket.js:265:10)
        at TLSSocket.socketOnClose (H:\IdrisAll\Dev\Obito\node_modules\ws\lib\websocket.js:1291:15)
        at TLSSocket.emit (node:events:531:35)
        at node:net:338:12
        at TCP.done (node:_tls_wrap:657:7)
  }
}
```
This is what I get when unsubscribing to privileged intents on the Dev Portal but still setting them in the client initialisation.

**Comment by didinele** [comment]
> Also, for code samples, there is none ig,
You just have to have subscribe to a Privileged Intent through client constructor

So there... literally is one. This is why we ask for a code sample, so we can just copy paste exactly what you did.

**Comment by imnaiyar** [comment]
Okay, yeah! That's my bad! I didn't think that would count as a code snippet

**Comment by didinele** [comment]
Sorry, I've gotten a little busy, but I can confirm there's an issue here for sure. I'll look into it this week.

Possibly related (not sure if it's really a dupe yet?) #10372

**Comment by didinele** [comment]
Hey there, I've investigated this issue.

So, if you call `client.login()` (and await it, preferably) and right off the bat you do not have the intent enabled, you will get the following:

```
Uncaught Error Error: Used disallowed intents
    at onClose (/home/dd/Documents/work/js-playground/node_modules/@discordjs/ws/dist/index.js:1217:18)
    at connection.onclose (/home/dd/Documents/work/js-playground/node_modules/@discordjs/ws/dist/index.js:737:17)
    at callListener (/home/dd/Documents/work/js-playground/node_modules/@discordjs/ws/node_modules/ws/lib/event-target.js:290:14)
    at onClose (/home/dd/Documents/work/js-playground/node_modules/@discordjs/ws/node_modules/ws/lib/event-target.js:220:9)
    at emit (events:519:28)
    at emitClose (/home/dd/Documents/work/js-playground/node_modules/@discordjs/ws/node_modules/ws/lib/websocket.js:265:10)
    at socketOnClose (/home/dd/Documents/work/js-playground/node_modules/@discordjs/ws/node_modules/ws/lib/websocket.js:1289:15)
    at emit (events:531:35)
    at <anonymous> (net:337:12)
    at done (_tls_wrap:657:7)
    at callbackTrampoline (internal/async_hooks:130:17)
    --- await ---
    at runMainESM (internal/modules/run_main:105:21)
    at executeUserEntryPoint (internal/modules/run_main:138:5)
    at <anonymous> (internal/main/run_main_module:28:49)
```

reproduced with this:
```ts
import { Client, GatewayIntentBits } from "discord.js";
const client = new Client({
  intents: [
    GatewayIntentBits.DirectMessages,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMembers,
  ],
});

client.on("ready", () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on("debug", console.log);

await client.login(TOKEN);
```

Where `GuildMembers` is not enabled in the dev portal. So far, this is completely expected behavior.

On the other hand, if the connection was already successfully established and you disable the `GuildMembers` intent in the portal, with the debug event attached, we can see exactly what's happening:
```
[WS => Shard 0] Waiting for event ready for 15000ms
[WS => Shard 0] Shard received all its guilds. Marking as fully ready.
Logged in as Test Bot#6354!
[turned off the intent here]
[WS => Shard 0] A request was somehow sent before the identify/resume payload.
[WS => Shard 0] Destroying shard
	Reason: none
	Code: 4003
	Recover: Reconnect
[WS => Shard 0] Connection status during destroy
	Needs closing: false
	Ready state: 3
[WS => Shard 0] Cancelled initial heartbeat due to #destroy being called
[WS => Shard 0] Connecting to wss://gateway.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] Preparing first heartbeat of the connection with a jitter of 0.5932344855349714; waiting 24470ms
[WS => Shard 0] Waiting for identify throttle
[WS => Shard 0] Identifying
	shard id: 0
	shard count: 1
	intents: 4611
	compression: none
[WS => Shard 0] Waiting for event ready for 15000ms
[WS => Shard 0] Destroying shard
	Reason: none
	Code: 4014
	Recover: none
[WS => Shard 0] Connection status during destroy
	Needs closing: false
	Ready state: 3
[WS => Shard 0] Cancelled initial heartbeat due to #destroy being called
```

Discord kills our connection (of course, because the intents we can use just changed), the shard immediately tries to reconnect, but this time during the initial connection we get "Disallowed intents", (4014) and the connection closes, allowing the process to quit.

One strange thing here is the initial close code Discord gives us, it's completely wrong and I'll be reporting that bug.

On our side though, your "fix" isn't really a fix, because there's parts of the codebase that expect the event to be emitted as `{ error: Error }`, you're just causing a bug.

What you're experiencing here is actually by design, see https://github.com/discordjs/discord.js/blob/093ac924aef1bf328feadb49876bfbe26052fe1a/packages/discord.js/src/client/websocket/WebSocketManager.js#L293-L301

If we adjust our test script to have a ShardError listener (which you should always have):
```ts
import { Client, GatewayIntentBits } from "discord.js";
const client = new Client({
  intents: [
    GatewayIntentBits.DirectMessages,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMembers,
  ],
});

client.on("ready", () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on("shardError", (error) =>
  console.log("Shard ran into an error!", error)
);

await client.login(TOKEN);
```

Then we get the following:
```
❯ node test.js
Logged in as Test Bot#6354!
[intent was turned off here]
Shard ran into an error! Error: Used disallowed intents
    at WebSocketShard.onClose (/home/dd/Documents/work/discordjs/discord.js/packages/ws/dist/index.js:1217:18)
    at connection.onclose (/home/dd/Documents/work/discordjs/discord.js/packages/ws/dist/index.js:737:17)
    at callListener (/home/dd/Documents/work/discordjs/discord.js/node_modules/.pnpm/ws@8.17.0_bufferutil@4.0.8_utf-8-validate@6.0.4/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/home/dd/Documents/work/discordjs/discord.js/node_modules/.pnpm/ws@8.17.0_bufferutil@4.0.8_utf-8-validate@6.0.4/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emitClose (/home/dd/Documents/work/discordjs/discord.js/node_modules/.pnpm/ws@8.17.0_bufferutil@4.0.8_utf-8-validate@6.0.4/node_modules/ws/lib/websocket.js:265:10)
    at TLSSocket.socketOnClose (/home/dd/Documents/work/discordjs/discord.js/node_modules/.pnpm/ws@8.17.0_bufferutil@4.0.8_utf-8-validate@6.0.4/node_modules/ws/lib/websocket.js:1289:15)
    at TLSSocket.emit (node:events:531:35)
    at node:net:337:12
    at TCP.done (node:_tls_wrap:657:7)
[process quit]
```
