### ISSUE TITLE
Network errors when using @discordjs/ws v1.1.1

### ISSUE THREAD

**Issue by AlexDiego123** [discordjs/discord.js#10382]
### Which package is this bug report for?

ws

### Issue description

I'm having trouble handling this error. This error occurs when my discord bot loses internet connection for a bit when my router restarts. This doesn't happen if i downgrade `@discordjs/ws` from `v1.1.1` to `v1.0.2` so this is probably something with an update to `@vladfrangu/async_event_emitter` that gets upgraded from `v2.2.3` to `v2.4.3` because it's that package's code that's throwing the error. I already tried handling this error with `client.on('error')`, `client.on(Discord.Events.ShardError)`, `process.on('EAI_AGAIN')` and `process.on('error')` but it doesn't work. I have another discord bot that has @discordjs/ws v1.0.2 and discord.js v14.14.1 and there it just reconnects when the internet connection becomes available again without logging anything, i want this to behave like that or at least find a solution to handle this error and make the bot reconnect automatically.

This is the error that occurs when i start my bot then disconnect internet for some minutes and reconnect it again, i've also enabled debug logs from discord.js:

<details>
<summary>Logs</summary>

```
Provided token: [REDACTED]
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 991
[WS => Shard 0] Connecting to wss://gateway.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] Preparing first heartbeat of the connection with a jitter of 0.19463540108076138; waiting 8028ms
[WS => Shard 0] Waiting for identify throttle
[WS => Shard 0] Identifying
        shard id: 0
        shard count: 1
        intents: 33283
        compression: none
[WS => Shard 0] Waiting for event ready for 15000ms
[WS => Shard 0] Shard received all its guilds. Marking as fully ready.
[WS => Shard 0] First heartbeat sent, starting to beat every 41250ms
[WS => Shard 0] Heartbeat acknowledged, latency of 143ms.
[WS => Shard 0] Heartbeat acknowledged, latency of 142ms.
[WS => Shard 0] Destroying shard
        Reason: Zombie connection
        Code: 4200
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: true
        Ready state: 1
[WS => Shard 0] Connecting to wss://gateway-us-east1-b.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
/home/alexdiego123/bots/Ping-Board2/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:278
      throw err;
      ^
 
Error: Unhandled 'error' event emitted, received [object Object]
    at WebSocketShard.emit (/home/alexdiego123/bots/Ping-Board2/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:276:19)
    at WebSocketShard.onError (/home/alexdiego123/bots/Ping-Board2/node_modules/@discordjs/ws/dist/index.js:1070:10)
    at connection.onerror (/home/alexdiego123/bots/Ping-Board2/node_modules/@discordjs/ws/dist/index.js:683:12)
    at callListener (/home/alexdiego123/bots/Ping-Board2/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onError (/home/alexdiego123/bots/Ping-Board2/node_modules/ws/lib/event-target.js:230:9)
    at WebSocket.emit (node:events:514:28)
    at emitErrorAndClose (/home/alexdiego123/bots/Ping-Board2/node_modules/ws/lib/websocket.js:1041:13)
    at ClientRequest.<anonymous> (/home/alexdiego123/bots/Ping-Board2/node_modules/ws/lib/websocket.js:881:5)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9) {
  context: {
    error: Error: getaddrinfo EAI_AGAIN gateway-us-east1-b.discord.gg
        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
      errno: -3001,
      code: 'EAI_AGAIN',
      syscall: 'getaddrinfo',
      hostname: 'gateway-us-east1-b.discord.gg'
    }
  }
}
 
Node.js v20.10.0
```
</details>

This is the output which is exactly the same when trying the exact same code but with a development build (3654efede):

<details>
<summary>Logs</summary>

```
Provided token: [REDACTED]
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
        URL: wss://gateway.discord.gg
        Recommended Shards: 1
[WS => Manager] Session Limit Information
        Total: 1000
        Remaining: 990
[WS => Shard 0] Connecting to wss://gateway.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] Preparing first heartbeat of the connection with a jitter of 0.02466562255625071; waiting 1017ms
[WS => Shard 0] Waiting for identify throttle
[WS => Shard 0] Identifying
        shard id: 0
        shard count: 1
        intents: 33283
        compression: none
[WS => Shard 0] Waiting for event ready for 15000ms
[WS => Shard 0] Shard received all its guilds. Marking as fully ready.
[WS => Shard 0] First heartbeat sent, starting to beat every 41250ms
[WS => Shard 0] Heartbeat acknowledged, latency of 142ms.
[WS => Shard 0] Heartbeat acknowledged, latency of 140ms.
[WS => Shard 0] Destroying shard
        Reason: Zombie connection
        Code: 4200
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: true
        Ready state: 1
[WS => Shard 0] Connecting to wss://gateway-us-east1-b.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
/home/alexdiego123/bots/Ping-Board2/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:278
      throw err;
      ^
 
Error: Unhandled 'error' event emitted, received [object Object]
    at WebSocketShard.emit (/home/alexdiego123/bots/Ping-Board2/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:276:19)
    at WebSocketShard.onError (/home/alexdiego123/bots/Ping-Board2/node_modules/@discordjs/ws/dist/index.js:1070:10)
    at connection.onerror (/home/alexdiego123/bots/Ping-Board2/node_modules/@discordjs/ws/dist/index.js:683:12)
    at callListener (/home/alexdiego123/bots/Ping-Board2/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onError (/home/alexdiego123/bots/Ping-Board2/node_modules/ws/lib/event-target.js:230:9)
    at WebSocket.emit (node:events:514:28)
    at emitErrorAndClose (/home/alexdiego123/bots/Ping-Board2/node_modules/ws/lib/websocket.js:1041:13)
    at ClientRequest.<anonymous> (/home/alexdiego123/bots/Ping-Board2/node_modules/ws/lib/websocket.js:881:5)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9) {
  context: {
    error: Error: getaddrinfo EAI_AGAIN gateway-us-east1-b.discord.gg
        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
      errno: -3001,
      code: 'EAI_AGAIN',
      syscall: 'getaddrinfo',
      hostname: 'gateway-us-east1-b.discord.gg'
    }
  }
}
 
Node.js v20.10.0
```
</details>

This is instead what my other discord bot that works and reconnects without errors logs with debug activated:

<details>
<summary>Logs</summary>

```
Provided token: [REDACTED]
Preparing to connect to the gateway...
[WS => Manager] Fetched Gateway Information
    URL: wss://gateway.discord.gg
    Recommended Shards: 1
[WS => Manager] Session Limit Information
    Total: 1000
    Remaining: 994
[WS => Shard 0] Connecting to wss://gateway.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] Preparing first heartbeat of the connection with a jitter of 0.9990806269038082; waiting 41212ms
[WS => Shard 0] Waiting for identify throttle
[WS => Shard 0] Identifying
        shard id: 0
        shard count: 1
        intents: 131
        compression: none
[WS => Shard 0] Waiting for event ready for 15000ms
[WS => Shard 0] Shard received all its guilds. Marking as fully ready.
[INFO] Logged in as Soccorso.Alex#9480
[DB] Database connected!
[WS => Shard 0] First heartbeat sent, starting to beat every 41250ms
[WS => Shard 0] Heartbeat acknowledged, latency of 140ms.
[WS => Shard 0] Heartbeat acknowledged, latency of 141ms.
[WS => Shard 0] Destroying shard
        Reason: Zombie connection
        Code: 4200
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: true
        Ready state: 1
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] The gateway closed with an unexpected code 1006, attempting to resume.
[WS => Shard 0] Destroying shard
        Reason: none
        Code: 1006
        Recover: Resume
[WS => Shard 0] Connection status during destroy
        Needs closing: false
        Ready state: 3
[WS => Shard 0] Tried to destroy a shard that was idle
[WS => Shard 0] Connecting to wss://gateway-us-east1-c.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] Preparing first heartbeat of the connection with a jitter of 0.43353267946812957; waiting 17883ms
[WS => Shard 0] Resuming session
        resume url: wss://gateway-us-east1-c.discord.gg
        sequence: 3
        shard id: 0
[WS => Shard 0] Invalid session; will attempt to resume: false
[WS => Shard 0] Destroying shard
        Reason: Invalid session
        Code: 1000
        Recover: Reconnect
[WS => Shard 0] Connection status during destroy
        Needs closing: true
        Ready state: 1
[WS => Shard 0] Cancelled initial heartbeat due to #destroy being called
[WS => Shard 0] Connecting to wss://gateway.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
[WS => Shard 0] Preparing first heartbeat of the connection with a jitter of 0.8450843997953759; waiting 34859ms
[WS => Shard 0] Waiting for identify throttle
[WS => Shard 0] Identifying
        shard id: 0
        shard count: 1
        intents: 131
        compression: none
[WS => Shard 0] Waiting for event ready for 15000ms
[WS => Shard 0] Shard received all its guilds. Marking as fully ready.
[WS => Shard 0] First heartbeat sent, starting to beat every 41250ms
[WS => Shard 0] Heartbeat acknowledged, latency of 137ms.
[WS => Shard 0] Heartbeat acknowledged, latency of 136ms.
```
</details>

You can see that here it just tries to reconnect endlessly without errors until the connection is restored and the heartbeat is sent, this is what i want to happen.

### Code sample

```typescript
const Discord = require('discord.js');

const client = new Discord.Client({ intents: [Discord.GatewayIntentBits.Guilds] });

client.on('debug', console.log)

client.login(TOKEN);
```

### Versions

- discord.js v14.15.3
- @discordjs/ws v1.1.1
- node.js v20.10.0
- Ubuntu Server 24.04 Noble Numbat (Raspberry Pi 5)

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

3654efede

**Comment by AlexDiego123** [comment]
I tested this on the new dev build after the pull request was merged and the initial error was fixed but there's still this error that occurs when internet goes down before the first heartbeat of the session is sent, i don't know if this is a bug or is intentional but i still wanted to report this. Either way it doesn't really cause problems because it's improbable that internet goes down like 40 seconds after the bot turns on.

**Logs** (dev build `9461045e5`): https://pastebin.com/aH5tj1nZ
