### ISSUE TITLE
TypeError: interaction.member.roles.add is not a function

### ISSUE THREAD

**Issue by MatteyGG** [discordjs/discord.js#10523]
### Which package is this bug report for?

discord.js

### Issue description

Cant add role to a member. I know, what something wrong with classes, but idk how to fix it(newbie).

I saw examples of implementation through cache, but I have no way to repeat it.

Mb helped:
```JavaScript
ChatInputCommandInteraction {
  type: 2,
  id: 'xxxxxxxxxxxx',
  applicationId: 'xxxxxxxxxxxx',
  channelId: 'xxxxxxxxxxxx',
  guildId: 'xxxxxxxxxxxx',
  user: User {
    id: 'xxxxxxxxxxxx',
    bot: false,
    system: false,
    flags: UserFlagsBitField { bitfield: 0 },
    username: 'matteygg',
    globalName: 'MatteyGG',
    discriminator: '0',
    avatar: 'b145f403d753b86b83b54b1f01287d5b',
    banner: undefined,
    accentColor: undefined,
    avatarDecoration: null,
    avatarDecorationData: null
  },
  member: {
    user: {
      username: 'matteygg',
      public_flags: 0,
      id: 'xxxxxxxxxxxx',
      global_name: 'MatteyGG',
      discriminator: '0',
      clan: null,
      avatar_decoration_data: null,
      avatar: 'b145f403d753b86b83b54b1f01287d5b'
    },
    unusual_dm_activity_until: null,
    roles: [ '1289890391155413064', '1289888599357132830' ],
    premium_since: null,
    permissions: '2251799813685247',
    pending: false,
    nick: null,
    mute: false,
    joined_at: '2024-09-28T08:26:09.365000+00:00',
    flags: 0,
    deaf: false,
    communication_disabled_until: null,
    banner: null,
    avatar: null
  },
  version: 1,
  appPermissions: PermissionsBitField { bitfield: 562949953863680n },
  memberPermissions: PermissionsBitField { bitfield: 2251799813685247n },
  locale: 'ru',
  guildLocale: 'en-US',
  entitlements: Collection(0) [Map] {},
  commandId: '1289538567684755457',
  commandName: 'verification',
  commandType: 1,
  commandGuildId: 'xxxxxxxxxxxx',
  authorizingIntegrationOwners: { '0': 'xxxxxxxxxxxx' },
  context: 0,
  deferred: false,
  replied: false,
  ephemeral: null,
  webhook: InteractionWebhook { id: 'xxxxxxxxxxxx' },
  options: CommandInteractionOptionResolver {
    _group: null,
    _subcommand: null,
    _hoistedOptions: []
  }
}
```

### Code sample

```typescript
module.exports = {
  
  data: new SlashCommandBuilder()
    .setName("verification")
    .setDescription("Начать верификацию"),

async execute(interaction) {
//....
//....
//....
try {
      const verificationAproved = await response.awaitMessageComponent({
        filter: R45collectorFilter,
        time: 6000_000,
      });

      if (verificationAproved.customId === "accept") {
        NewUserInfo.setColor("Green");
        NewUserInfo.setFields({
          name: "Состояние",
          value: "Верификация пройдена",
          inline: true,
        });
        await interaction.member.roles.add("1289888599357132830"); //Cant add role
        await verificationAproved.update({
          content: "",
          embeds: [NewUserInfo],
          components: [],
        });
      } else if (verificationAproved.customId === "decline") {
        NewUserInfo.setColor("Red");
        NewUserInfo.setFields({
          name: "Состояние",
          value: "Верификация отклонена",
          inline: true,
        });

        await verificationAproved.update({
          content: "",
          embeds: [NewUserInfo],
          components: [],
        });
      }
    }
},
};
```

### Versions

 discord.js  ^14.16.2
node  v20.11.1

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildMembers, GuildModeration

**Comment by vladfrangu** [comment]
Can you share the stacktrace of the error please?

**Comment by vladfrangu** [comment]
Also, can you try this with the Guilds intent present too?

**Comment by MatteyGG** [comment]
Yes, here it is, thanks for such a quick reply

TypeError: interaction.member.roles.add is not a function
    at Object.execute (C:\Users\..xxxxxxxxxxxx..\Code\NAME-discord-bot\commands\utility\verification.js:112:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (C:\Users\..xxxxxxxxxxxx..\Code\NAME-discord-bot\events\interactionCreate.js:16:4)

**Comment by MatteyGG** [comment]
Sorry, it was my mistake, problem was in settings of my test bot in .dev discord portal. 
![image](https://github.com/user-attachments/assets/eca82555-3ca6-45ac-91fe-57a3b4ed9f41)
Sorry again, your libary is super)
