### ISSUE TITLE
  code: 'ERR_IPC_CHANNEL_CLOSED'

### ISSUE THREAD

**Issue by gamer167** [discordjs/discord.js#10576]
### Which package is this bug report for?

discord.js

### Issue description

Unknown, it happens at random,

### Code sample

```typescript
N/A
```

### Versions

Discord.JS: 14.16.1
Device: Raspberry Pi 4
OS Ver. Debian GNU/Linux 11 (bullseye)

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by gamer167** [comment]
Error from console:
```
****@raspberrypi:~/Desktop/****/beta/Keep_Chat-Happy-Beta-main $ Provided token: ********************************************
Preparing to connect to the gateway...
Started refreshing 18 application (/) commands.
[WS => Manager] Fetched Gateway Information
	URL: wss://gateway.discord.gg
	Recommended Shards: 1
[WS => Manager] Session Limit Information
	Total: 1000
	Remaining: 1000
[WS => Shard 0] Connecting to wss://gateway.discord.gg?v=10&encoding=json
[WS => Shard 0] Waiting for event hello for 60000ms
Successfully reloaded 18 application (/) commands.
[WS => Shard 0] Preparing first heartbeat of the connection with a jitter of 0.8733810529091439; waiting 36026ms
[WS => Shard 0] Waiting for identify throttle
[WS => Shard 0] Identifying
	shard id: 0
	shard count: 1
	intents: 1
	compression: none
[WS => Shard 0] Waiting for event ready for 15000ms
[WS => Shard 0] Shard received all its guilds. Marking as fully ready.
Ready! Logged in as Keep Chat Happy Beta#3159... wait im a bot... AHHHHHHH. who programed me? oh wait my owner programed me... WHO IS MY OWNER... idk. help me im cool bot and fun but but froget my owner... HELP. whats my name... oh its keep chat happy. well im keeping chats happy. bye!
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at target.send (node:internal/child_process:754:16)
    at Client.<anonymous> (/home/****/Desktop/KCH/beta/Keep_Chat-Happy-Beta-main/node_modules/discord.js/src/sharding/ShardClientUtil.js:37:19)
    at Client.emit (node:events:519:28)
    at WebSocketShard.<anonymous> (/home/****/Desktop/KCH/beta/Keep_Chat-Happy-Beta-main/node_modules/discord.js/src/client/websocket/WebSocketManager.js:192:23)
    at WebSocketShard.emit (node:events:519:28)
    at WebSocketShard.checkReady (/home/****/Desktop/KCH/beta/Keep_Chat-Happy-Beta-main/node_modules/discord.js/src/client/websocket/WebSocketShard.js:184:12)
    at WebSocketShard.gotGuild (/home/****/Desktop/KCH/beta/Keep_Chat-Happy-Beta-main/node_modules/discord.js/src/client/websocket/WebSocketShard.js:158:10)
    at WebSocketManager.<anonymous> (/home/****/Desktop/KCH/beta/Keep_Chat-Happy-Beta-main/node_modules/discord.js/src/client/websocket/WebSocketManager.js:234:15)
    at WebSocketManager.emit (/home/****/Desktop/KCH/beta/Keep_Chat-Happy-Beta-main/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:287:31)
    at WebSocketShard.<anonymous> (/home/****/Desktop/KCH/beta/Keep_Chat-Happy-Beta-main/node_modules/@discordjs/ws/dist/index.js:1190:51)
Emitted 'error' event on process instance at:
    at node:internal/child_process:758:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v20.18.0
```

**Comment by didinele** [comment]
We still need a code sample to have an idea about what's going on here. Are you sharding? How so?

**Comment by gamer167** [comment]
What code sample do you want? The sharding code?

**Comment by gamer167** [comment]
im sharding the way the docs tell you to. With an addition of having updates send with a webhook,

**Comment by gamer167** [comment]
@didinele

**Comment by didinele** [comment]
Considering the time that has passed and the failure to provide a reproducible code sample, I'll be closing this.
