### ISSUE TITLE
Timeout Overflow

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#2324]
**Please describe the problem you are having in as much detail as possible:**
Node spamming TimeoutOverflow errors.
Maybe ratelimits errors or too high timeouts/intervals.

**Include a reproducible code sample here, if possible:**
It appears randomly so I am not able to know where it come from.

```js
(node:28404) TimeoutOverflowWarning: 1517707521667 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

**Further details:**

- discord.js version: master
- node.js version: 9.4.0
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Can you run node with trace warnings to get location of the setTimeout(s) causing this?
`node --trace-warnings file`

**Comment by Koyamie** [comment]
Alright this happens : 
```js
(node:6978) TimeoutOverflowWarning: 1517757815082 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
    at new Timeout (timers.js:533:15)
    at setTimeout (timers.js:441:10)
    at StreamDispatcher._step (discord.js/src/client/voice/dispatcher/StreamDispatcher.js:203:7)
    at StreamDispatcher._write (discord.js/src/client/voice/dispatcher/StreamDispatcher.js:105:10)
    at doWrite (_stream_writable.js:407:12)
    at writeOrBuffer (_stream_writable.js:393:5)
    at StreamDispatcher.Writable.write (_stream_writable.js:290:11)
    at Encoder.ondata (_stream_readable.js:646:20)
    at Encoder.emit (events.js:160:13)
    at Encoder.Readable.read (_stream_readable.js:482:10)
    at flow (_stream_readable.js:853:34)
    at StreamDispatcher.<anonymous> (_stream_readable.js:714:7)
    at StreamDispatcher.emit (events.js:160:13)
    at onwriteDrain (_stream_writable.js:484:12)
    at afterWrite (_stream_writable.js:472:5)
    at onwrite (_stream_writable.js:465:7)```

**Comment by Emdix** [comment]
I've encountered this issue after executing dispatcher.resume() while the dispatcher was already running. I'd check if this is the culprit.

**Comment by SpaceEEC** [comment]
Thank you for the tip with resuming the dispatcher!
That seems to be the culprit and should be fixed with the linked commit.
