### ISSUE TITLE
Rich Embeds don't work in Command Handler

### ISSUE THREAD

**Issue by ItsTauTvyDas** [discordjs/discord.js#2345]
**Please describe the problem you are having in as much detail as possible:**
I have a problem, **Rich Embeds** don't work in [Command Handler](https://anidiotsguide_old.gitbooks.io/discord-js-bot-guide/content/coding-guides/a-basic-command-handler.html)? I type command and I had this error in console:
```
TypeError: Discord.RichEmbed is not a constructor
at Object.exports.run (/app/commands/komandos.js:2:17)
at Client.bot.on.message (/app/bot.js:50:17)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:17)
    at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:115:13)
```
(I think I make mistake in code, right? What mistake?)
P.S. Sorry for my english..

**Include a reproducible code sample here, if possible:**
```js
exports.run = (bot, message, Discord) => {
  const embed = new Discord.RichEmbed()
    .setTitle("Hello!")
    .setDescription(`My name is ${bot.user}, and I'm bot!`)
  message.channel.sendMessage(embed);
}
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.4.0

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Boujee0002** [comment]
Show us how do you run commands, on message event

**Comment by YoussefElshemi** [comment]
Are you sure you're not in master?

**Comment by SpaceEEC** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by vypr** [comment]
I had the same issue, my solution was to set Discord.js to "^11.2.1" in my package.json.

**Comment by BlissSc** [comment]
thx
