### ISSUE TITLE
Cannot find module './commands/eval var.js'

### ISSUE THREAD

**Issue by ipadpuppydogdude1** [discordjs/discord.js#2358]
**Please describe the problem you are having in as much detail as possible:**
I have been having problems running eval with the `var` definition, which is preventing me from doing things without having to code it in a js file.

**Include a reproducible code sample here, if possible:**
```js
{ Error: Cannot find module './commands/eval
var.js'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
t Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at Client.client.on.message (/home/ipad/ChromeBot/ChromeBot.js:29:23)
at emitOne (events.js:116:13)
at Client.emit (events.js:211:7)
at MessageCreateHandler.handle (/home/ipad/ChromeBot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
at WebSocketPacketManager.handle (/home/ipad/ChromeBot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
at WebSocketConnection.onPacket (/home/ipad/ChromeBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35) code: 'MODULE_NOT_FOUND' }

```

**Further details:**
PROOF: 

http://prntscr.com/ijczou
http://prntscr.com/ijczuq
---
- discord.js version: 11.3
- node.js version: 8.9.4
- Operating system: Ubuntu server LTX 16.04
- Priority this issue should have – please be realistic and elaborate if possible:
Take your time. I will just wait I guess. Depends on whoever is reviewing it, I am being kind and just letting it be time-wise as possible.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by dragonfire535** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
