### ISSUE TITLE
fs.js:648   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

### ISSUE THREAD

**Issue by Jathur95** [discordjs/discord.js#2365]
When the bot is launched it say that :

```js
fs.js:648
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open 'C:\Users\*****\Discord\Bot\DoritosXDD\ressource.json'
    at Object.fs.openSync (fs.js:648:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.<anonymous> (C:\Users\*****\Discord\Bot\DoritosXDD\index.js:6:31)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
```

**Comment by Lewdcario** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
