### ISSUE TITLE
Unhanded "error" event at client.emit (events.js:186:19)

### ISSUE THREAD

**Issue by orkc** [discordjs/discord.js#2397]
Bot working fine but periodically getting the following crash.  Appears to be problem with handling of a connection issue.  If discord.js will not or cannot handle gracefully how can I intercept this event to handle in my bot?  

Error: Unhandled "error" event. ([object Object])
    at Client.emit (events.js:186:19)
    at WebSocketConnection.onError (/Users/ken/dev/PokeAlert/GymBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/Users/ken/dev/PokeAlert/GymBot/node_modules/discord.js/node_modules/ws/lib/event-target.js:128:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at _receiver.cleanup (/Users/ken/dev/PokeAlert/GymBot/node_modules/discord.js/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/Users/ken/dev/PokeAlert/GymBot/node_modules/discord.js/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/Users/ken/dev/PokeAlert/GymBot/node_modules/discord.js/node_modules/ws/lib/websocket.js:206:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)

**Further details:**

    "discord.js": "^11.3.2",
    "node.js": v8.9.4
    OSX 10.11.6

**Comment by iCrawl** [comment]
Do you have a listener attached to the error event?

**Comment by orkc** [comment]
No I do not.  Is it as simple as listening for error on the client?

**Comment by orkc** [comment]
Thank you for the prompt response.  New to this so apologies for bothering you with this.
