### ISSUE TITLE
Ban Error

### ISSUE THREAD

**Issue by emilvsn** [discordjs/discord.js#2402]
The error:
(node:11222) UnhandledPromiseRejectionWarning: Error: Couldn't resolve the user ID to ban.

    at RESTMethods.banGuildMember (/rbd/pnpm-volume/28d61cb8-91ec-4589-9f9b-ea41ca411dad/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/client/rest/RESTMethods.js:573:36)

    at Guild.ban (/rbd/pnpm-volume/28d61cb8-91ec-4589-9f9b-ea41ca411dad/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/structures/Guild.js:875:37)

at Client.client.on (/app/bot.js:47:19)

    at emitOne (events.js:116:13)

    at Client.emit (events.js:211:7)

    at Guild._addMember (/rbd/pnpm-volume/28d61cb8-91ec-4589-9f9b-ea41ca411dad/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/structures/Guild.js:1142:19)

    at GuildMemberAddHandler.handle (/rbd/pnpm-volume/28d61cb8-91ec-4589-9f9b-ea41ca411dad/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/client/websocket/packets/handlers/GuildMemberAdd.js:12:13)

    at WebSocketPacketManager.handle (/rbd/pnpm-volume/28d61cb8-91ec-4589-9f9b-ea41ca411dad/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)

    at WebSocketConnection.onPacket (/rbd/pnpm-volume/28d61cb8-91ec-4589-9f9b-ea41ca411dad/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)

    at WebSocketConnection.onMessage (/rbd/pnpm-volume/28d61cb8-91ec-4589-9f9b-ea41ca411dad/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)

(node:11222) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:11222) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The Code:

client.on("guildMemberAdd", (message, client, member) => {
message.guild.ban(member);
});

**Comment by Lewdcario** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
