### ISSUE TITLE
ReferenceError: connection is not defined

### ISSUE THREAD

**Issue by Milomand99** [discordjs/discord.js#2416]
Im trying to make a bot that streams audio via a local file. i can get it to join an audio channel, but when i add const dispatcher = connection.play('/home/discord/audio.mp3'); it gives me this error 

"C:\DiscordBot\ourbot.js:4
const dispatcher = connection.play('./Portalsound.mp3');
                   ^

ReferenceError: connection is not defined
    at Object.<anonymous> (C:\DiscordBot\ourbot.js:4:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3"

Does anyone have a fix? i cant find anyone else with this problem.

Sorry if this is a bit of a newbie problem, im new to programming. wouldnt suprise me if it was a really easy fix.

**Comment by SpaceEEC** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.
