### ISSUE TITLE
TypeError: this.activity._clone() is not a function

### ISSUE THREAD

**Issue by Favna** [discordjs/discord.js#2418]
**Please describe the problem you are having in as much detail as possible:**

While trying to write some code using the `onPresenceUpdate` event emitter I ran into this TypeError:

```
    if (this.activity) clone.activity = this.activity._clone();
                                                      ^

TypeError: this.activity._clone is not a function
    at Presence._clone (E:\UserFiles\DevProjects\ribbon\node_modules\discord.js\src\structures\Presence.js:44:55)
    at PresenceUpdateHandler.handle (E:\UserFiles\DevProjects\ribbon\node_modules\discord.js\src\client\websocket\packets\handlers\PresenceUpdate.js:43:54)
    at WebSocketPacketManager.handle (E:\UserFiles\DevProjects\ribbon\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (E:\UserFiles\DevProjects\ribbon\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:316:35)
    at WebSocketConnection.onMessage (E:\UserFiles\DevProjects\ribbon\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:279:10)
    at WebSocket.onMessage (E:\UserFiles\DevProjects\ribbon\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (E:\UserFiles\DevProjects\ribbon\node_modules\ws\lib\websocket.js:137:47)
    at Receiver.dataMessage (E:\UserFiles\DevProjects\ribbon\node_modules\ws\lib\receiver.js:397:14)
```

It talks about these lines:

https://github.com/discordjs/discord.js/blob/d041cb2460a294b026e73750647647168ce7359a/src/structures/Presence.js#L42-L46

No idea why this error occurs but if I compare them to similar `_clone()` functions, those are written differently

https://github.com/discordjs/discord.js/blob/d041cb2460a294b026e73750647647168ce7359a/src/structures/Base.js#L17-L19
https://github.com/discordjs/discord.js/blob/d041cb2460a294b026e73750647647168ce7359a/src/structures/Base.js#L23-L27

**Include a reproducible code sample here, if possible:**

The error seems to occur regardless of specific code but always directly after starting some code using the presenceUpdate event. That said, to reproduce I think it suffices to write any basic onPresenceUpdate and then jumble around with presences. Personally I notice it when going from no activity whatsoever (`activity = null`) to streaming to twitch, this can be reproduced by starting a stream and then enabling and disabling streamer mode in discord user settings.

As far as I can tell the exact occurrence is when going in this order:
not streaming -> streaming (entire function as linked below resolves) -> not streaming -> error when start streaming
or
streaming -> not streaming -> error when start streaming

The full onPresenceUpdate code that I have written is [on a gist here](https://gist.github.com/Favna/ed545ec4c34b63977c13db3da50bcc22) to save on length in the issue body. Note that the error is thrown even before the very first console log. A successful output of this code would look something like this:

![](https://favna.s-ul.eu/80Faz102.png)

Lastly, the entire file (stripped irrelevant event functions) from requires to export just in case is ~~[again on hastebin](https://hastebin.com/cewenagami.js)~~ *snipped because link appears to be broken*

**Further details:**

- discord.js version: master branch
- node.js version: 8.10.0
- yarn version: 1.5.1
- Operating system: Windows 10 64 bit (win32 x64)
- Priority this issue should have – please be realistic and elaborate if possible: medium

- Full yarn-error log file [on hastebin here](https://hastebin.com/ubogezaraz.log)

- [ ] I found this issue while running code on a __user account__
- [X] I have also tested the issue on latest master, commit hash: d041cb2460a294b026e73750647647168ce7359a

**Comment by Favna** [comment]
I've had some time to do some further debugging as it were and I've managed to zero in the issue to a specific part in my own code. The crashes seem to occur when doing any `if` check on the activity. In my code I perform these two checks:

```js
if (!oldMember.presence.activity) {
  oldMember.presence.activity = {'url': 'placeholder'};
}
if (!newMember.presence.activity) {
  newMember.presence.activity = {'url': 'placeholder'};
}
```

```js
if (!(/(twitch)/i).test(oldMember.presence.activity.url) && (/(twitch)/i).test(newMember.presence.activity.url)) { 
  console.log('Passed checking if twitch is in new presence');
}
```

When first saving the activity of the old and new members to a variable however the issue appears to be resolved. I suppose that is at least a work around until the clone issue is fixed in the library but personally I strongly believe in the philosophy of not saving data to variables if you do not really have to for the sake of code clarity, that is to say, I'd rather do `if (member.presence.activity.url) { // do something };` than `const activity = member.presence.activity; if (activity.url) { // do something };`

---

I also noticed the hastebin links seem to no longer be working so I snipped the second one in an edit and the first one is updated to a Gist which now also has the above mentioned workaround fix added.

**Comment by SpaceEEC** [comment]
The library expects `Presence#activity` to be either null, or an [`Activity`](https://github.com/discordjs/discord.js/blob/master/src/structures/Presence.js#L69) with a [_clone](https://github.com/discordjs/discord.js/blob/master/src/structures/Presence.js#L168) method, which a plain object does not have.

Regarding to save it to a variable:
That is pretty much what you should do here.

Assigning a plain object to a property where a specific class is expected leads, as you see here, to unexpected behaviour or even uncaught exceptions.
