### ISSUE TITLE
Cannot read property id on create MessageAttachment

### ISSUE THREAD

**Issue by ceduliocezar** [discordjs/discord.js#2423]
This documentation [https://github.com/discordjs/discord.js/blob/master/docs/examples/attachments.md](https://github.com/discordjs/discord.js/blob/master/docs/examples/attachments.md)says that to send an attachment to a channel you should do the following:

`client.on('message', message => {
	// If the message is '!rip'
	if (message.content === '!rip') {
		// Create the attachment using MessageAttachment
		const attachment = new MessageAttachment('https://i.imgur.com/w3duR07.png');
		// Send the attachment in the message channel with a content
		message.channel.send(`${message.author},`, attachment);
	}
});`

However if you run the exact same example code, it crashes with a message that a property id cannot be find.

**TypeError: Cannot read property 'id' of undefined
    at MessageAttachment.setup (..\node_modules\discord.js\src\structures\MessageAttachment.js:28:20)
    at new MessageAttachment (..\node_modules\discord.js\src\structures\MessageAttachment.js:20:10)**

**Comment by ceduliocezar** [comment]
Have already talked about this on discord but a guy there told me to look at the docs, even if I stated that the docs code is broken.

**Comment by ceduliocezar** [comment]
I was looking on master docs instead of stable one.
