### ISSUE TITLE
Topicupdate patchrequest denied by API if category is present

### ISSUE THREAD

**Issue by queezly** [discordjs/discord.js#2533]
**Please describe the problem you are having in as much detail as possible:**
Testenvironment:
Category (no overwrites - empty collection if checked)
Subchannel Type text overwrite for the botuser, not the role allow: 805829713
Permissions are not synced to the category

Expected Outcome:
- console logs true
- The topic is updated

Actual Outcome:
- console logs true (the permission is present on the immediate textchannel after all)
- The topic is not updated, APIerror:
```prolog
DiscordAPIError: Missing Permissions
    at item.request.gen.end (C:\Users\Moeh\Documents\GitHub\djs-stable\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:71:65)
    at then (C:\Users\Moeh\Documents\GitHub\djs-stable\node_modules\snekfetch\src\index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```
Upon further testing:
Snekfetch client requests are identical
Snekfetch data differs
```js
{ name: 'textchannel',
  topic: 'newTopic',
  nsfw: undefined,
  bitrate: undefined,
  user_limit: undefined,
  parent_id: undefined,
  lock_permissions: undefined,
  permission_overwrites: undefined }
```
```js
{ name: 'textchannel',
  topic: 'newTopic',
  position: 2,
  bitrate: undefined,
  user_limit: undefined,
  parent_id: '441030914949120012' }
```

Isolated the issue by adapting the data before sending the patchrequest in snekfetch sourcecode at .send(data) {} 
If parent_id is set the API rejects the request, if it is adapted to undefined the request goes through.
If the same request from master is adapted to the parent_id the request is rejected as well.

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
    console.log('Ready!');
});
client.on('message', msg => {
   console.log(msg.channel.permissionsFor(msg.client.user).has("MANAGE_CHANNELS"))
   msg.channel.setTopic('newTopic')
})

client.login('token');
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: v9.11.1
- Operating system: Windows 10 Home x64 v1803 (17134.1)
- Priority this issue should have – please be realistic and elaborate if possible:
medium, prevents stable bots from modifying channelsettings in channels with a parent

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:
The issue is not present on master due to the different json layout for the channelupdate patchrequest

**Comment by queezly** [comment]
Can not reproduce any longer, seems to be fixed
