### ISSUE TITLE
[Close this issue - Snekfetch wasn't correctly installed]Invalid or unexpected token

### ISSUE THREAD

**Issue by SermonB** [discordjs/discord.js#2549]
So I'm using next line in my code to include the discord.js script. When i run it locally I don't receive any errors. When I test in on my online version I receive the error noted on the bottom.

```const discord = require('discord.js');```

The only difference between local and online is the node version.
Local: v8.11.1
Online: v8.9.4

```
/volume1/web/discord/node_modules/snekfetch/index.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/volume1/web/discord/node_modules/discord.js/src/util/Util.js:1:81)
```

**Comment by Rickyxstar** [comment]
How did you install it correctly?

**Comment by GuimDev** [comment]
`npm install discord.js` is it not enough ?
