### ISSUE TITLE
'FFMPEG not found' but installed...

### ISSUE THREAD

**Issue by Alkanife** [discordjs/discord.js#2560]
Hello, (I'm french so sorry for my bad english)

I want to connect my discord bot on a voice channel, but I have an error.
The error say "Error: FFMPEG not found" but FFMPEG is already installed.
Somebody can help me ? ^^

Code: 

>         let voiceChannel = message.guild.channels
>            .filter(function (channel){
>                return channel.type === 'voice'
>            })
>            .first();
>
>        voiceChannel.join();

Error:
> alkabot.js:5
(node:8648) UnhandledPromiseRejectionWarning: Error: FFMPEG not found
warning.js:18
    at Function.selectFfmpegCommand (c:\Users\alkan\OneDrive\Documents\Discord\Alkabot\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:46:13)
    at new FfmpegTranscoder (c:\Users\alkan\OneDrive\Documents\Discord\Alkabot\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:7:37)
    at new MediaTranscoder (c:\Users\alkan\OneDrive\Documents\Discord\Alkabot\node_modules\prism-media\src\transcoders\MediaTranscoder.js:10:19)
    at new Prism (c:\Users\alkan\OneDrive\Documents\Discord\Alkabot\node_modules\prism-media\src\Prism.js:5:23)
    at new VoiceConnection (c:\Users\alkan\OneDrive\Documents\Discord\Alkabot\node_modules\discord.js\src\client\voice\VoiceConnection.js:46:18)
    at Promise (c:\Users\alkan\OneDrive\Documents\Discord\Alkabot\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:63:22)
    at new Promise (<anonymous>)
    at ClientVoiceManager.joinChannel (c:\Users\alkan\OneDrive\Documents\Discord\Alkabot\node_modules\discord.js\src\client\voice\ClientVoiceManager.js:45:12)
    at VoiceChannel.join (c:\Users\alkan\OneDrive\Documents\Discord\Alkabot\node_modules\discord.js\src\structures\VoiceChannel.js:120:30)
    at Client.<anonymous> (c:\Users\alkan\OneDrive\Documents\Discord\Alkabot\alkabot.js:18:22)
(node:8648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
(node:8648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
warning.js:18

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
