### ISSUE TITLE
Mention prefix is protesting

### ISSUE THREAD

**Issue by ignissak** [discordjs/discord.js#2561]
**Further details:**

- discord.js version: 11.3.2
- node.js version: 5.6
- Operating system: Linux Ubuntu 16.04.3

```
4|logio    | TypeError: prefixMention.match is not a function
4|logio    |     at Query._callback (/home/bots/discord/Logio/index.js:95:39)
4|logio    |     at Query.Sequence.end (/home/bots/discord/Logio/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
4|logio    |     at Query._handleFinalResultPacket (/home/bots/discord/Logio/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
4|logio    |     at Query.EofPacket (/home/bots/discord/Logio/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
4|logio    |     at Protocol._parsePacket (/home/bots/discord/Logio/node_modules/mysql/lib/protocol/Protocol.js:279:23)
4|logio    |     at Parser.write (/home/bots/discord/Logio/node_modules/mysql/lib/protocol/Parser.js:76:12)
4|logio    |     at Protocol.write (/home/bots/discord/Logio/node_modules/mysql/lib/protocol/Protocol.js:39:16)
4|logio    |     at Socket.<anonymous> (/home/bots/discord/Logio/node_modules/mysql/lib/Connection.js:103:28)
4|logio    |     at Socket.emit (events.js:159:13)
```

```js
const prefixMention = new RegExp(`^<@!?${bot.user.id}> `);
        mentionPrefix = prefixMention.match(message.content) ? message.content.match(prefixMention)[0] + " " : prefix;
```

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
