### ISSUE TITLE
StreamDispatcher errors

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#2567]
**Please describe the problem you are having in as much detail as possible:**
Getting this error after a timeout with stream dispatcher.

**Error code:**
```js
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
at doWrite (_stream_writable.js:406:19)
at clearBuffer (_stream_writable.js:540:7)
at onwrite (_stream_writable.js:465:7)
at Timeout.setTimeout [as _onTimeout] (/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:207:60)
at ontimeout (timers.js:427:11)
at tryOnTimeout (timers.js:289:5)
at listOnTimeout (timers.js:252:5)
at Timer.processTimers (timers.js:212:10)
```
Getting another error when resuming.

**Error code:**
```js
Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
at onwrite (_stream_writable.js:451:11)
at StreamDispatcher.resume (/node_modules/discord.js/src/client/voice/dispatcher/StreamDispatcher.js:147:57)
at "<StreamDispatcher>.resume();"
at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Further details:**

- discord.js version: master
- node.js version: 10.2.1
- Operating system: Debian 9
- Priority this issue should have – please be realistic and elaborate if possible: When have some time

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by hydrabolt** [comment]
Hi!

Sorry it took so long to get to this issue, I think I've fixed it now with the above commits, could you try using the latest master branch of discord.js and see if the issue persists?

Thanks!

**Comment by amishshah** [comment]
I'm going to close this issue as it seems inactive, if you can still reproduce it then please reopen it
