### ISSUE TITLE
TypeError with User#setNote

### ISSUE THREAD

**Issue by Personinblack** [discordjs/discord.js#2576]
**Please describe the problem you are having in as much detail as possible:**
setNote method of the User crashes the bot and produces the following error:

```
projectDir/node_modules/discord.js/src/client/rest/APIRequest.js:9
    this.path = path.toString();
                     ^

TypeError: Cannot read property 'toString' of undefined
    at new APIRequest (projectDir/node_modules/discord.js/src/client/rest/APIRequest.js:9:22)
    at RESTManager.makeRequest (projectDir/node_modules/discord.js/src/client/rest/RESTManager.js:46:24)
    at RESTMethods.setNote (projectDir/node_modules/discord.js/src/client/rest/RESTMethods.js:933:22)
    at ClientUser.setNote (projectDir/node_modules/discord.js/src/structures/User.js:261:37)
    at Client.index_1.CLIENT.on (projectDir/src/index.js:9:16)
    at Client.emit (events.js:187:15)
    at MessageCreateHandler.handle (projectDir/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (projectDir/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (projectDir/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (projectDir/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
```

**Include a reproducible code sample here, if possible:**
```js
CLIENT.on("message", (message) => message.author.setNote("hello world"));
```

**Further details:**

- discord.js version: ^11.3.2
- node.js version: v10.3.0
- Operating system: Arch Linux
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
![image](https://user-images.githubusercontent.com/20760160/40863116-0b4033ce-65ef-11e8-862a-4a9a78aa1a72.png)

**Comment by Personinblack** [comment]
:/ Sorry for bothering. Didn't look at the docs close enough...
