### ISSUE TITLE
VoiceRecorder cannot decrypt voice data

### ISSUE THREAD

**Issue by DasCodeMonster** [discordjs/discord.js#2595]
**Please describe the problem you are having in as much detail as possible:**

The VoiceReceiver is not able to decrypt voice data. This also appears when libsodium-wrappers are installed:
Without libsodium-wrappers
```
Error: Failed to decrypt voice packet
    at PacketHandler.parseBuffer (C:\node_modules\discord.js\src\client\voice\receiver\PacketHandler.js:34:25)
    at PacketHandler.push (C:\node_modules\discord.js\src\client\voice\receiver\PacketHandler.js:63:29)
    at Socket.VoiceReceiver.connection.sockets.udp.socket.on.buffer (C:\node_modules\discord.js\src\client\voice\receiver\Receiver.js:24:77)
    at Socket.emit (events.js:182:13)
    at UDP.onMessage [as onmessage] (dgram.js:673:8)
```

With libsodium-wrappers:
```
Error: wrong secret key for the given ciphertext
    at v (C:\...\node_modules\libsodium-wrappers\dist\modules\libsodium-wrappers.js:1:2743)
    at Object.Ne [as open] (C:\...\node_modules\libsodium-wrappers\dist\modules\libsodium-wrappers.js:1:34057)
    at PacketHandler.parseBuffer (C:\...\node_modules\discord.js\src\client\voice\receiver\PacketHandler.js:33:36)
    at PacketHandler.push (C:\...\node_modules\discord.js\src\client\voice\receiver\PacketHandler.js:63:29)
    at Socket.VoiceReceiver.connection.sockets.udp.socket.on.buffer (C:\...\node_modules\discord.js\src\client\voice\receiver\Receiver.js:24:77)
    at Socket.emit (events.js:182:13)
    at UDP.onMessage [as onmessage] (dgram.js:670:8)
```
**Include a reproducible code sample here, if possible:**
```js
const {Client} = require("discord.js");
const ytdl = require("ytdl-core");
const client = new Client();

client.on("message", async message=>{
    if(message.member.voiceChannel){
        await message.member.voiceChannel.join();
        message.guild.voiceConnection.play(ytdl("Any Valid Link", {filter: "audioonly"}));
        const receiver = message.guild.voiceConnection.createReceiver();
        receiver.on("debug", info=>{
            console.log(info);
        });
        let stream = receiver.createStream(message.member, {mode: "pcm", end: "silence"});
        stream.on("error", err=>{
            console.log(err);
        });
        stream.on("data", data=>{
            console.log(data);
        });
    }
});
client.on("error", err=>{
    console.log(err);
});
client.login("BOT_TOKEN");
process.on("SIGINT", ()=>{
    client.destroy();
});
```

**Further details:**

- discord.js version: 12.0.0-dev
- node.js version: v10.4.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: low/medium (I really want to use it but i think for most people this has low priority)

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: eb4607c8adee0a2c83899c44b7541d738dacef74

**Comment by hydrabolt** [comment]
This is because I forgot to add receive support for different voice modes after enabling them, will fix this asap

**Comment by hydrabolt** [comment]
I believe this is fixed in https://github.com/discordjs/discord.js/commit/d69e906027b82a36f91ead7f4cbe08bf4425d422, can you try it out and tell me if it worked? Thanks!

**Comment by DasCodeMonster** [comment]
Yes it works now!
Thank you for fixing this so fast
