### ISSUE TITLE
DiscordAPI error 

### ISSUE THREAD

**Issue by emilvsn** [discordjs/discord.js#2633]
- discord.js version: The Lastest
- node.js version: The Latest of V9
- Operating system: Linux UNIX
- Priority this issue should have – please be realistic and elaborate if possible:
When I saw my bot was down I was checking the console it came with this:
(node:1667) UnhandledPromiseRejectionWarning: DiscordAPIError

    at item.request.gen.end (/rbd/pnpm-volume/28d61cb8-91ec-4589-9f9b-ea41ca411dad/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)

    at then (/rbd/pnpm-volume/28d61cb8-91ec-4589-9f9b-ea41ca411dad/node_modules/.registry.npmjs.org/snekfetch/3.6.4/node_modules/snekfetch/src/index.js:215:21)

    at <anonymous>

    at process._tickCallback (internal/process/next_tick.js:188:7)

(node:1667) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

(node:1667) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Also I dont see any bug reporting channels in the server so its why I posted it here

**Comment by Gawdl3y** [comment]
This is almost certainly not a bug with discord.js, but an issue with your code/bot. `process.on('unhandledRejection', console.error);` will get you more details about the error.
