### ISSUE TITLE
PLZ HELP

### ISSUE THREAD

**Issue by Mrsasha45op** [discordjs/discord.js#2634]
Help plz
const dispatcher = connection.playFile('D:/superman/music.mp3');
                           ^

ReferenceError: connection is not defined
    at Client.robot.on (D:\superman\index.js:27:28)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (D:\superman\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (D:\superman\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (D:\superman\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (D:\superman\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (D:\superman\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
const Discord = require('discord.js');
const robot = new Discord.Client();

const responseObject = {
    "/youtube": "Yes it's good",
    "/wat": "What?",
    "/тортик": "Тортик это топчик",
    "/help": "/тортик /youtube /hello /ping /wat /help /avatar",
    "/hello": "Здраствуйте дорогой пикачу",
    "/ping": "Пинг 0ms",
    
  };

robot.login("NDYxNjE3MTQ2OTQ2OTEyMjU2.DhYUyw.yiy4Bm7freGp5SKym1ioIIppM0A");

robot.on('message',(message) => {

    if(responseObject[message.content]) {
        message.channel.send(responseObject[message.content]);
      }
      if (message.content === '/avatar') {
        // Send the user's avatar URL
        message.reply(message.author.avatarURL);
      }
      if(message.content === '/play'){
        const dispatcher = connection.playFile('D:/superman/music.mp3');
      }
      if (message.content === '/join') {
        // Only try to join the sender's voice channel if they are in one themselves
        if (message.member.voiceChannel) {
          message.member.voiceChannel.join()
            .then(connection => { // Connection is an instance of VoiceConnection
              message.reply('I have successfully connected to the channel!');
              
            })
            .catch(console.log);
        } else {
          message.reply('You need to join a voice channel first!');
        }
      }
});
Versions:
node v 8.11.3

**Comment by SpaceEEC** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
You also want to reset your token.

**Comment by kyranet** [comment]
And you may want to reset your token in the [Discord Developers](https://discordapp.com/developers/applications/me) page.

**Comment by Mrsasha45op** [comment]
sry
