### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: cache.get is not a function

### ISSUE THREAD

**Issue by Elanis** [discordjs/discord.js#2647]
I decided to update all my apps to be compatible with node v10 but many warning appears with discord.js

**Code:**
```js
(discord.js)
// Import the discord.js module
const Discord = require('discord.js');

// Create an instance of a Discord client
const client = new Discord.Client();

// The token of your bot - https://discordapp.com/developers/applications/me
const token = 'token';

module.exports = {
	connect: function() {
		client.login(token);
	},
};

(app.js)
global.Discord   = require('./discord');

https.listen(globalCfg["serverPort"], function () {
	Discord.connect();
	console.log('Server is listening on *:' + globalCfg["serverPort"]);
});
```
After commenting and testing, it appears that warnings draw when client.login() is called.

**Logs:**
```
(node:15504) UnhandledPromiseRejectionWarning: TypeError: cache.get is not a function
    at stat (internal/modules/cjs/loader.js:87:26)
    at Function.Module._findPath (internal/modules/cjs/loader.js:244:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:591:25)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (G:\path\to\node\server\node_modules\discord.js\src\client\websocket\packets\handlers\Ready.js:1:87)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at new WebSocketPacketManager (G:\path\to\node\server\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketMana
ger.js:19:45)
    at new WebSocketConnection (G:\path\to\node\server\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:70:26)
(node:15504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an asyn
c function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not
 handled will terminate the Node.js process with a non-zero exit code.
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: 10.5.0
- Operating system: Windows 10 & Git Bash
- Priority this issue should have: Medium, it don't make crash scripts but spam warnings.

- [ ] I found this issue while running code on a __user account__
- [X] I have also tested the issue on latest master, commit hash: 95b2dd3fe63ec9b6c7cec4f63f8276f4d907f228

NB: A simple "TypeError: cache.get is not a function" appear sometimes in logs but i didn't identify from where it come from.

NB2: "ready" event isn't called

**Comment by PLASMAchicken** [comment]
- [x ] `node: v10.5.0
 discord.js@11.3.2
 npm@6.1.0
cmd 
`


app.js
```
global.Discord   = require('./discord');

Discord.connect();

```
works fine could you please provide more reproduceble code

**Comment by Elanis** [comment]
Indeed, my previous code didn't throw, here's a newer version:

(discord.js)
```js
// Import the discord.js module
const Discord = require('discord.js');

// Create an instance of a Discord client
const client = new Discord.Client();

// The token of your bot - https://discordapp.com/developers/applications/me
const token = 'token';

module.exports = {
	connect: function() {
		client.login(token);
	},
};
```
(map.js)
```js
module.exports = class Map { };
```
(Yes we need this to throw the bug)

(app.js)
```js
/**
 * Npm libs
 */
global.fs = require('fs');
let options = {
	key: fs.readFileSync(process.cwd() + '/keys/privkey.pem'),
	cert: fs.readFileSync(process.cwd() + '/keys/cert.pem')
};
let express = require('express');
let app = express();
global.https = require('https').createServer(options, app);
global.io = require('socket.io')(https);

require('./config')();

global.Discord   = require('./discord');
global.Map       = require('./map');

Discord.connect();
console.log('Server is listening on *:' + globalCfg["serverPort"]);
```

**Comment by iCrawl** [comment]
I hope you are not surprised as to why this is happening.

**Comment by appellation** [comment]
Overriding JS globals will result in undefined behaviour and is not a situation that this library does nor should handle.

**Comment by Elanis** [comment]
Oh ... I feel bad ... Sorry i forgot Map is a reserved word. Well this isn't an issue.
