### ISSUE TITLE
Error if a channel updates

### ISSUE THREAD

**Issue by DwarfLop** [discordjs/discord.js#2658]
**Please describe the problem you are having in as much detail as possible:**
I get the following Error if I give the "Bots"-Role (the bot has got this role) new permissions to a channel or add/remove the "Bots"-Role to the channel without changing anything.

```
[...]\node_modules\discord.js\src\client\actions\ChannelUpdate.js:9
    const channel = client.channels.get(data.id);
                                    ^

TypeError: client.channels.get is not a function
    at ChannelUpdateAction.handle ([...]\node_modules\discord.js\src\client\actions\ChannelUpdate.js:9:37)
    at ChannelUpdateHandler.handle ([...]\node_modules\discord.js\src\client\websocket\packets\handlers\ChannelUpdate.js:7:34)
    at WebSocketPacketManager.handle ([...]\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket ([...]\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage ([...]\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage ([...]\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage ([...]\node_modules\ws\lib\websocket.js:137:47)
    at Receiver.dataMessage ([...]\node_modules\ws\lib\receiver.js:409:14)
    at Receiver.getData ([...]\node_modules\ws\lib\receiver.js:347:12)
```

**The code that has to do with the problem**
```js
client.channels = {
        log: client.guild.channels.get(process.env.LOG),
        modlog: client.guild.channels.get(process.env.MODLOG),
        memberlog: client.guild.channels.get(process.env.MEMBERLOG)
};
    
for (let channel in client.channels) {
        if (!client.channels[channel] || !client.channels[channel].permissionsFor(client.guild.me).has(['VIEW_CHANNEL', 'SEND_MESSAGES', 'EMBED_LINKS', 'MANAGE_MESSAGES'])) {
            console.log('[Fehler] Ein Channel aus der .env wurde nicht gefunden oder dem Bot fehlen entsprechende Permissions.');
            process.exit(0);
        }
}
```

**Further details:**

- discord.js version: 11.3.2
- node.js version: v10.0.0
- Operating system: Windows 10 x64
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by TishDev** [comment]
lmfao
