### ISSUE TITLE
Checking Permissions Issue

### ISSUE THREAD

**Issue by KyleBoyer** [discordjs/discord.js#2710]
**Please describe the problem you are having in as much detail as possible:**
When I try to check my permissions, I get this error:

(node:59331) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'client' of undefined
    at new RoleStore (/Users/Kyle/git/Monstacord/node_modules/discord.js/src/stores/RoleStore.js:12:17)
    at Map.filter (/Users/Kyle/git/Monstacord/node_modules/discord.js/src/util/Collection.js:223:21)
    at Map.get _filtered [as _filtered] (/Users/Kyle/git/Monstacord/node_modules/discord.js/src/stores/GuildMemberRoleStore.js:24:29)
    at Map.store.(anonymous function) [as map] (/Users/Kyle/git/Monstacord/node_modules/discord.js/src/util/Util.js:420:34)
    at TextChannel.memberPermissions (/Users/Kyle/git/Monstacord/node_modules/discord.js/src/structures/GuildChannel.js:143:47)
    at TextChannel.permissionsFor (/Users/Kyle/git/Monstacord/node_modules/discord.js/src/structures/GuildChannel.js:101:29)

**Include a reproducible code sample here, if possible:**
```js
if (message.guild) {
      const permissions = ['ADD_REACTIONS', 'MANAGE_MESSAGES', 'EMBED_LINKS'];
      const missing = message.channel.permissionsFor(message.client.user).missing(permissions);
}
```

**Further details:**

- discord.js version: Latest
- node.js version: Latest
- Operating system: Ubuntu 18
- Priority this issue should have – please be realistic and elaborate if possible: Critical?

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
Hi, this is an issue on the latest master branch due to https://github.com/discordjs/discord.js/commit/c10b4feeeb7705903593ba134df128c57a823ff1, we're in the process of fixing it ASAP!

**Comment by KyleBoyer** [comment]
Thank you!

**Comment by amishshah** [comment]
The breaking change has been reverted, thanks for bringing up the issue anyway!
