### ISSUE TITLE
guild#createChannel not accepting a PermissionOverwrites collection

### ISSUE THREAD

**Issue by RighteousPotato** [discordjs/discord.js#2753]
**Please describe the problem you are having in as much detail as possible:**
A RangeError is thrown when trying to create a new text channel using the permissionOverwrites collection of an existing channel.

**Error thrown:**
```
warn:    Uncaught Promise Rejection:
RangeError: Invalid permission string or number.
    at Function.resolve (\Jessie2\node_modules\discord.js\src\util\Permissions.js:194:65)
    at overwrites.map.overwrite (\Jessie2\node_modules\discord.js\src\structures\shared\resolvePermissions.js:17:28)
    at Map.map (\Jessie2\node_modules\discord.js\src\util\Collection.js:343:47)
    at RESTMethods.resolvePermissions (\Jessie2\node_modules\discord.js\src\structures\shared\resolvePermissions.js:6:29)
    at RESTMethods.createChannel (\Jessie2\node_modules\discord.js\src\client\rest\RESTMethods.js:260:49)
    at Guild.createChannel (\Jessie2\node_modules\discord.js\src\structures\Guild.js:1004:37)
    at Object.execute (\Jessie2\botModules\commands\create.js:16:39)
    at Client.execute (\Jessie2\botModules\handlers\message_cmd.js:68:12)
    at emitTwo (events.js:126:13)
    at Client.emit (events.js:214:7)
```

**Include a reproducible code sample here, if possible:**
```js
client.on('message' message=>{
   message.guild.createChannel(args.join('-'), 'TEXT', message.channel.permissionOverwrites);
});
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.9.3
- Operating system: Windows 7 x64
- Priority this issue should have – please be realistic and elaborate if possible: medium

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Fixed with the referenced commit ^
