### ISSUE TITLE
Bot randomly crashing.

### ISSUE THREAD

**Issue by Tagueo** [discordjs/discord.js#2754]
**Please describe the problem you are having in as much detail as possible:**
My bot is randomly crashing and I think it's not related to my code.
An error (see below) is appearing when my bot is idling, often during a night, when nobody is using it.
I've no idea why this is happening, and this seems to be related with discord.js, since the only files appearing in the error log are not part of my bot.

**Error :**
```
events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:171:17)
    at WebSocketConnection.onError (/home/denver/denver-js/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/home/denver/denver-js/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at _receiver.cleanup (/home/denver/denver-js/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/home/denver/denver-js/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/home/denver/denver-js/node_modules/ws/lib/websocket.js:206:20)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
```

**Further details:**
- discord.js version: 11.3.2
- Node.js version: 10.8.0
- Operating system: Debian 9.5
- Priority this issue should have – please be realistic and elaborate if possible: High : my bot is randomly crashing with this error, so It's pretty annoying.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

*PS: Sorry for the bad English, I'm French so It's not my native language ^^*

**Comment by iCrawl** [comment]
#2523

**Comment by iSupremeInGithub** [comment]
france rpz
