### ISSUE TITLE
Can't node app.js after installing discord.js

### ISSUE THREAD

**Issue by MLiranG** [discordjs/discord.js#2771]
**Please describe the problem you are having in as much detail as possible:**
After download discord.js 
> npm i discord.js --save

i can't node app.js(getting err)

**Further details:**
- discord.js version: 11.4.2
- Node.js version: v8.11.4
- Operating system: windows 10 64x bit
- Priority this issue should have – please be realistic and elaborate if possible: HIGH

**The err i'm getting**
```js
events.js:188
      throw err;
      ^

Error: Unhandled "error" event. ([object Object])
    at Client.emit (events.js:186:19)
    at WebSocketConnection.onError (C:\Users\x\Desktop\תכנות\Discord_bots\Shit\test\node_modules\discord.
js\src\client\websocket\WebSocketConnection.js:374:17)
    at WebSocket.onError (C:\Users\x\Desktop\תכנות\Discord_bots\Shit\test\node_modules\ws\lib\event-targe
t.js:128:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at WebSocket.finalize (C:\Users\x\Desktop\תכנות\Discord_bots\Shit\test\node_modules\ws\lib\websocket.
js:185:12)
    at ClientRequest._req.on (C:\Users\x\Desktop\תכנות\Discord_bots\Shit\test\node_modules\ws\lib\websock
et.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
```

**Comment by iCrawl** [comment]
#2523

**Comment by MLiranG** [comment]
@iCrawl 

```js
ErrorEvent {
  target:
   WebSocket {
     domain: null,
     _events:
      { message: [Object],
        open: [Object],
        error: [Object],
        close: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     readyState: 2,
     protocol: '',
     _binaryType: 'nodebuffer',
     _finalize: [Function: bound finalize],
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _finalized: true,
     _closeCode: 1006,
     _extensions: {},
     _isServer: false,
     _receiver: null,
     _sender: null,
     _socket: null,
     _error: null,
     url: 'wss://gateway.discord.gg/?v=6&encoding=json',
     _req: null },
  type: 'error',
  message: 'self signed certificate in certificate chain',
  error: { Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' } }
```

what can i do now??

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
