### ISSUE TITLE
Shard's ChildProcess Exits Before It Became Ready

### ISSUE THREAD

**Issue by rainbownotfound** [discordjs/discord.js#2839]
**Please describe the problem you are having in as much detail as possible:**
I have sharded my bot recently, and now I'm trying to make shard logs through a webhook. I have defined the Discord.Shard property and I put the ShardingManager's token in there too, together with the Shard's ID.

However, when I try to start the bot, an unexpected error occurs:
```
path.js:28

    throw new TypeError('Path must be a string. Received ' + inspect(path));

    ^


TypeError: Path must be a string. Received undefined

    at assertPath (path.js:28:11)

    at Object.resolve (path.js:1174:7)

    at Shard.spawn (/rbd/pnpm-volume/b1008a1b-84fd-432e-b3ef-6bbc83b270b2/node_modules/.registry.npmjs.org/discord.js/11.4.2/node_modules/discord.js/src/sharding/Shard.js:72:43)

    at new Shard (/rbd/pnpm-volume/b1008a1b-84fd-432e-b3ef-6bbc83b270b2/node_modules/.registry.npmjs.org/discord.js/11.4.2/node_modules/discord.js/src/sharding/Shard.js:61:10)

at Object.<anonymous> (/app/server.js:12:15)

    at Module._compile (module.js:573:30)

    at Object.Module._extensions..js (module.js:584:10)

    at Module.load (module.js:507:32)

    at tryModuleLoad (module.js:470:12)

    at Function.Module._load (module.js:462:3)

[ShardingManager] Shard undefined / 1 launched successfully.

(node:11887) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 303): Error: Shard 0's process exited before its Client became ready.
```

**Include a reproducible code sample here, if possible:**
```js
const Discord = require('discord.js');
const webhook = new Discord.WebhookClient("WebhookID", "WebhookToken");
const shard = new Discord.Shard(`ShardingManagerTokenHere`, '0');

shard.on('death', s => {
    webhook.send({
        embed: utils.embed(`ShardingManager`, `Shard ${s.id}'s ChildProcess Exited. Reason Unknown.`)
    });
});

shard.on('reconnecting', s => {
    webhook.send({
        embed: utils.embed(`ShardingManager`, `Shard ${s.id} is attempting to reconnect...`)
    });
});

shard.on('disconnect', s => {
    webhook.send({
        embed: utils.embed(`ShardingManager`, `Shard ${s.id} has disconnected.`)
    });
});

shard.on('ready', s => {
    webhook.send({
        embed: utils.embed(`ShardingManager`, `Shard ${s.id} started successfully.`)
    });
});
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 8.4.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Normal, because this is not a urgent issue.

- [x] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by ShayBox** [comment]
you don't create shards yourself you create a sharding manager, https://anidiots.guide/
