### ISSUE TITLE
Unhandled error at VoiceConnection.emit

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#2846]
**Please describe the problem you are having in as much detail as possible:**
An unhandled error is dropping randomly for no reason.

**The error :**
```js
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at VoiceConnection.emit (events.js:171:17)
    at VoiceWebSocket.ws.on.err (/node_modules/discord.js/src/client/voice/VoiceConnection.js:388:32)
    at VoiceWebSocket.emit (events.js:182:13)
    at VoiceWebSocket.onError (/node_modules/discord.js/src/client/voice/networking/VoiceWebSocket.js:149:10)
    at WebSocket.onError (/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at ClientRequest.req.on (/node_modules/ws/lib/websocket.js:528:10)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Further details:**
- discord.js version: lastest master
- Node.js version: lastest 
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
As noted in the issue above, add an error handler.
