### ISSUE TITLE
Error with guild.setup

### ISSUE THREAD

**Issue by MTGPROD** [discordjs/discord.js#2941]
2018-11-11T14:45:16.179051+00:00 app[worker.1]: /app/node_modules/discord.js/src/structures/Guild.js:235
2018-11-11T14:45:16.179076+00:00 app[worker.1]:           this.channels.get(voiceState.channel_id).members.set(member.user.id, member);
2018-11-11T14:45:16.179077+00:00 app[worker.1]:                                                   ^
2018-11-11T14:45:16.179079+00:00 app[worker.1]: 
2018-11-11T14:45:16.179080+00:00 app[worker.1]: TypeError: Cannot read property 'members' of undefined
2018-11-11T14:45:16.179081+00:00 app[worker.1]:     at Guild.setup (/app/node_modules/discord.js/src/structures/Guild.js:235:51)
2018-11-11T14:45:16.179083+00:00 app[worker.1]:     at GuildCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:12:15)
2018-11-11T14:45:16.179084+00:00 app[worker.1]:     at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
2018-11-11T14:45:16.179086+00:00 app[worker.1]:     at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
2018-11-11T14:45:16.179087+00:00 app[worker.1]:     at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
2018-11-11T14:45:16.179089+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
2018-11-11T14:45:16.179090+00:00 app[worker.1]:     at WebSocket.emit (events.js:182:13)
2018-11-11T14:45:16.179091+00:00 app[worker.1]:     at Receiver._receiver.onmessage (/app/node_modules/ws/lib/websocket.js:137:47)
2018-11-11T14:45:16.179093+00:00 app[worker.1]:     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:397:14)
2018-11-11T14:45:16.179094+00:00 app[worker.1]:     at Receiver.getData (/app/node_modules/ws/lib/receiver.js:347:12)
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2018-11-11T14:45:16.179081+00:00 app[worker.1]:     at Guild.setup (/app/node_modules/discord.js/src/structures/Guild.js:235:51)
2018-11-11T14:45:16.179083+00:00 app[worker.1]:     at GuildCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:12:15)
2018-11-11T14:45:16.179084+00:00 app[worker.1]:     at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
2018-11-11T14:45:16.179086+00:00 app[worker.1]:     at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
2018-11-11T14:45:16.179087+00:00 app[worker.1]:     at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
2018-11-11T14:45:16.179089+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
2018-11-11T14:45:16.179090+00:00 app[worker.1]:     at WebSocket.emit (events.js:182:13)
2018-11-11T14:45:16.179091+00:00 app[worker.1]:     at Receiver._receiver.onmessage (/app/node_modules/ws/lib/websocket.js:137:47)
2018-11-11T14:45:16.179093+00:00 app[worker.1]:     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:397:14)
2018-11-11T14:45:16.179094+00:00 app[worker.1]:     at Receiver.getData (/app/node_modules/ws/lib/receiver.js:347:12)

What's this ?

**Comment by iCrawl** [comment]
>What's this ?

Not a questions tracker.

__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
