### ISSUE TITLE
TypeError: Cannot read property 'client' of undefined in `Util.cleanContent`

### ISSUE THREAD

**Issue by pizzafox** [discordjs/discord.js#2988]
**Please describe the problem you are having in as much detail as possible:**
Attempting to use `Util.cleanContent()` on a string containg a channel mention (like `<#473672486903480320>`) results in the following error:

```
TypeError: Cannot read property 'client' of undefined ,
    at str.replace.replace.replace.input (/usr/src/bot/node_modules/discord.js/src/util/Util.js:412:33),
    at String.replace (<anonymous>),
    at Argument.parse [as parser] (/usr/src/bot/src/commands/fun/command.js:32:28),
    at Function.cleanContent (/usr/src/bot/node_modules/discord.js/src/util/Util.js:411:8),
    at Argument.parse (/usr/src/bot/node_modules/discord.js-commando/src/commands/argument.js:365:31),
    at process._tickCallback (internal/process/next_tick.js:68:7),
    at Argument.obtain (/usr/src/bot/node_modules/discord.js-commando/src/commands/argument.js:224:22)
```

**Include a reproducible code sample here, if possible:**
```js
const { Util } = require('discord.js');

Util.cleanContent('<#473672486903480320>');
```

**Further details:**
- discord.js version: Master
- Node.js version: `v10.14.0`
- Operating system: Debian 9
- Priority this issue should have – please be realistic and elaborate if possible: Low

- [x] I have also tested the issue on latest master, commit hash: b5d5c699e65bf14a77065a75aabd24e4972988a9

**Comment by Lewdcario** [comment]
`Util#cleanContent` takes a `message` object for the second parameter as per the docs: https://discord.js.org/#/docs/main/master/class/Util?scrollTo=s-cleanContent
