### ISSUE TITLE
rest error `includes` of undefined

### ISSUE THREAD

**Issue by BannerBomb** [discordjs/discord.js#2989]
**Please describe the problem you are having in as much detail as possible:**
For any request sent to `this.client.rest.request()` throws an error
```prolog
TypeError: Cannot read property 'includes' of undefined
    at RequestHandler.execute (/media/ubuntu/discordbot/node_modules/discord.js/src/rest/RequestHandler.js:123:30)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```
I have messed with the RequestHandler.js file a bit to figure out the issue, and I have determined that it's doing this because once `item.request.route` gets called while issuing the rest request it receives undefined which it shouldn't be doing that. It can easily be fixed by changing the block of code from
```js
// https://github.com/discordapp/discord-api-docs/issues/182
if (item.request.route.includes('reactions')) {
    this.reset = new Date(serverDate).getTime() - getAPIOffset(serverDate) + 250;
}
```
to
```js
// https://github.com/discordapp/discord-api-docs/issues/182
if (item.request.route && item.request.route.includes('reactions')) {
    this.reset = new Date(serverDate).getTime() - getAPIOffset(serverDate) + 250;
}
```

**Include a reproducible code sample here, if possible:**
```js
this.client.rest.request('GET',`/channels/${msg.channel.id}/messages`);
```

**Further details:**
- discord.js version: discord.js-master (latest)
- Node.js version: v11.4.0
- Operating system: Ubuntu 18.04.1 LTS
- Priority this issue should have – please be realistic and elaborate if possible:
I think it should get looked at because it should not be showing as undefined at the moment it gets called.

- [x] I have also tested the issue on latest master, commit hash: `b5d5c699e65bf14a77065a75aabd24e4972988a9`

**Comment by BannerBomb** [comment]
I know about the this.client.rest.api[...].get(); method, but I thought it was supposed to be allowed to be accessed using this.client.rest also. But, ok never mind then.
