### ISSUE TITLE
.replacePermissionOverwrites doesn't accept .permissionOverwrites

### ISSUE THREAD

**Issue by Andreybest** [discordjs/discord.js#3000]
**Please describe the problem you are having in as much detail as possible:**
Im making a bot for preventing from deleating roles on channels, but as im trying to overwrite roles to a previous state, nothing happends.

**Include a reproducible code sample here, if possible:**
```js
client.on("channelUpdate", (oldChannel, newChannel) => {
    var oldChannelPermissionsArray = oldChannel.permissionOverwrites.array();
    var newChannelPermissionsArray = newChannel.permissionOverwrites.array();
    if (newChannelPermissionsArray.length < oldChannelPermissionsArray.length) {
        console.log(oldChannel.permissionOverwrites);
        newChannel.replacePermissionOverwrites({
            overwrites: [oldChannel.permissionOverwrites],
        });
    }
});
```

Also after 15-20 seconds im getting this error:
```
(node:3026) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
permission_overwrites[0].id: This field is required
```

**Further details:**
- discord.js version: 11.4.2
- Node.js version: 9.8.0
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash:

**Comment by kyranet** [comment]
Try this:

```diff
 client.on("channelUpdate", (oldChannel, newChannel) => {
     var oldChannelPermissionsArray = oldChannel.permissionOverwrites.array();
     var newChannelPermissionsArray = newChannel.permissionOverwrites.array();
     if (newChannelPermissionsArray.length < oldChannelPermissionsArray.length) {
         console.log(oldChannel.permissionOverwrites);
         newChannel.replacePermissionOverwrites({
-            overwrites: [oldChannel.permissionOverwrites],
+            overwrites: oldChannel.permissionOverwrites,
         });
     }
 });
```

Also:

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by Andreybest** [comment]
Nope, dosen't work too:
```js
/home/ubuntu/workspace/node_modules/discord.js/src/util/Permissions.js:194
    if (typeof permission !== 'number' || permission < 0) throw new RangeError(Constants.Errors.NOT_A_PERMISSION);
                                                          ^

RangeError: Invalid permission string or number.
    at Function.resolve (/home/ubuntu/workspace/node_modules/discord.js/src/util/Permissions.js:194:65)
    at overwrites.map.overwrite (/home/ubuntu/workspace/node_modules/discord.js/src/structures/shared/resolvePermissions.js:17:28)
    at Map.map (/home/ubuntu/workspace/node_modules/discord.js/src/util/Collection.js:343:47)
    at RESTMethods.resolvePermissions (/home/ubuntu/workspace/node_modules/discord.js/src/structures/shared/resolvePermissions.js:6:29)
    at RESTMethods.updateChannel (/home/ubuntu/workspace/node_modules/discord.js/src/client/rest/RESTMethods.js:326:26)
    at TextChannel.edit (/home/ubuntu/workspace/node_modules/discord.js/src/structures/GuildChannel.js:302:37)
    at TextChannel.replacePermissionOverwrites (/home/ubuntu/workspace/node_modules/discord.js/src/structures/GuildChannel.js:181:17)
    at Client.client.on (/home/ubuntu/workspace/Role_punisher/test.js:29:20)
    at Client.emit (events.js:180:13)
    at ChannelUpdateAction.handle (/home/ubuntu/workspace/node_modules/discord.js/src/client/actions/ChannelUpdate.js:13:14)
```

**Comment by Monkeyyy11** [comment]
You should join the discord server, they gonna help you!
