### ISSUE TITLE
Cannot find module error on heroku 

### ISSUE THREAD

**Issue by sachinbhutani** [discordjs/discord.js#3015]
Getting cannot find module error on heroku, 
the same code builds and runs successfully on local machine. 

verified with below version on heroku.
node js version :10.15
npm version : 6.5

2019-01-05T05:20:07.555503+00:00 app[web.1]: Error: Cannot find module '../../structures/shared/resolvePermissions'
2019-01-05T05:20:07.555505+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2019-01-05T05:20:07.555506+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2019-01-05T05:20:07.555508+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:637:17)
2019-01-05T05:20:07.555509+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:22:18)
2019-01-05T05:20:07.555511+00:00 app[web.1]: at Object.<anonymous> (/app/node_modules/discord.js/src/client/rest/RESTMethods.js:8:28)
2019-01-05T05:20:07.555512+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:689:30)
2019-01-05T05:20:07.555514+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2019-01-05T05:20:07.555515+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:599:32)
2019-01-05T05:20:07.555517+00:00 app[web.1]: at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2019-01-05T05:20:07.555518+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:530:3)
2019-01-05T05:20:07.649639+00:00 heroku[web.1]: State changed from starting to crashed
2019-01-05T05:20:07.651743+00:00 heroku[web.1]: State changed from crashed to starting
2019-01-05T05:20:11.781326+00:00 heroku[web.1]: Starting process with command `node index.js`
2019-01-05T05:20:14.921163+00:00 heroku[web.1]: Process exited with status 1
2019-01-05T05:20:14.941659+00:00 heroku[web.1]: State changed from starting to crashed
2019-01-05T05:20:14.801070+00:00 app[web.1]: internal/modules/cjs/loader.js:583
2019-01-05T05:20:14.801085+00:00 app[web.1]: throw err;
2019-01-05T05:20:14.801086+00:00 app[web.1]: ^
2019-01-05T05:20:14.801087+00:00 app[web.1]:
2019-01-05T05:20:14.801089+00:00 app[web.1]: Error: Cannot find module '../../structures/shared/resolvePermissions'
2019-01-05T05:20:14.801091+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
2019-01-05T05:20:14.801092+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:507:25)
2019-01-05T05:20:14.801094+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:637:17)
2019-01-05T05:20:14.801096+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:22:18)
2019-01-05T05:20:14.801098+00:00 app[web.1]: at Object.<anonymous> (/app/node_modules/discord.js/src/client/rest/RESTMethods.js:8:28)
2019-01-05T05:20:14.801099+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:689:30)
2019-01-05T05:20:14.801101+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2019-01-05T05:20:14.801102+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:599:32)
2019-01-05T05:20:14.801104+00:00 app[web.1]: at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2019-01-05T05:20:14.801105+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:530:3)
// Place your code here

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
