### ISSUE TITLE
UnhandledPromiseRejectionWarning when discord goes down.

### ISSUE THREAD

**Issue by coranos** [discordjs/discord.js#3020]
```
(node:13354) UnhandledPromiseRejectionWarning: Error: Something took too long to do.
    at timeout.client.setTimeout (./node_modules/discord.js/src/client/ClientManager.js:40:57)
    at Timeout.setTimeout [as _onTimeout] (./node_modules/discord.js/src/client/Client.js:433:7)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
(node:13354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13354) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

looks like the client code doesn't exit properly if the connection to discord times out.

https://github.com/discordjs/discord.js/blob/11.4.2/src/client/ClientManager.js#L40

**Comment by amishshah** [comment]
Try `.catch`ing the login request.
