### ISSUE TITLE
npm command doesn't work: UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by B4ttleMast0r** [discordjs/discord.js#3026]
```
C:\Users\[Username]>cd C:\Users\[Username]\Favorites\Discord Bot\Wumpus's Sensei\Code

C:\Users\[Username]\Favorites\Discord Bot\Wumpus's Sensei\Code>npm install discord.js node-opus
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! errno UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! request to https://registry.npmjs.org/discord.js failed, reason: unable to verify the first certificate

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[Username]\AppData\Roaming\npm-cache\_logs\2019-01-17T16_44_43_234Z-debug.log
```
Log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'discord.js',
1 verbose cli   'node-opus' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose npm-session c3586a922f6bf0bc
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for discord.js@latest request to https://registry.npmjs.org/discord.js failed, reason: unable to verify the first certificate
8 silly fetchPackageMetaData error for node-opus@latest request to https://registry.npmjs.org/node-opus failed, reason: unable to verify the first certificate
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 379ms
11 verbose type system
12 verbose stack FetchError: request to https://registry.npmjs.org/discord.js failed, reason: unable to verify the first certificate
12 verbose stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
12 verbose stack     at ClientRequest.emit (events.js:182:13)
12 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:392:9)
12 verbose stack     at TLSSocket.emit (events.js:182:13)
12 verbose stack     at emitErrorNT (internal/streams/destroy.js:82:8)
12 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
13 verbose cwd C:\Users\[Username]\Favorites\Discord Bot\Wumpus's Sensei\Code
14 verbose Windows_NT 10.0.16299
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord.js" "node-opus"
16 verbose node v10.15.0
17 verbose npm  v6.4.1
18 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
19 error errno UNABLE_TO_VERIFY_LEAF_SIGNATURE
20 error request to https://registry.npmjs.org/discord.js failed, reason: unable to verify the first certificate
21 verbose exit [ 1, true ]

```
Note: obviously i replaced my Username with "[Username]" for privacy reasons.

**Comment by amishshah** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
