### ISSUE TITLE
add play speed option

### ISSUE THREAD

**Issue by ktjd123** [discordjs/discord.js#3151]
**Is your feature request related to a problem? Please describe.**

play speed is not stable on x64 linux with apt installed ffmpeg [ffmpeg-binaries does not work in linux x64 so I copied /usr/bin/ffmpeg to ffmpeg-binaries/bin folder].

**Describe the ideal solution**

1. add play speed option

**Describe alternatives you've considered**

1. change ffmpeg-binaries to other package.
2. add play speed
3. stablize play speed

**Additional context**
Always appreciate your work.

**Comment by amishshah** [comment]
I don't want to add this to Discord.js itself since it seems like a niche, you can always specify your own arguments to FFmpeg with `prism-media` though:

[The example here](https://hydrabolt.me/prism-media/?api#new-core.FFmpeg) provides the arguments required by Discord.js, you can add extra arguments yourself:

```js
const prism = require('prism-media');
// Add your extra arguments here
const transcoder = new prism.FFmpeg({
args: [
  '-analyzeduration', '0',
  '-loglevel', '0',
  '-f', 's16le',
  '-ar', '48000',
  '-ac', '2',
]
});

// v11
connection.playConvertedStream(input.pipe(transcoder))

// v12
connection.play(input.pipe(transcoder), { type: 'converted' })
```

**Comment by ktjd123** [comment]
@amishshah Thanks but I don't get where ```input.pipe()```'s ```input``` come from. is it ReadableStream??

I used ```fs.createReadStream()``` and the following error occured. I have no sense where it's coming from.

```js
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at Socket.Writable.write (_stream_writable.js:291:5)
    at ReadStream.ondata (_stream_readable.js:689:20)
    at ReadStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ReadStream.Readable.push (_stream_readable.js:220:10)
    at lazyFs.read (internal/fs/streams.js:181:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:462:17)
Emitted 'error' event at:
    at FFmpeg.onerror (_stream_readable.js:713:12)
    at FFmpeg.emit (events.js:194:15)
    at Socket.processError (/home/ubuntu/build/node_modules/prism-media/src/core/FFmpeg.js:51:40)
    at Socket.emit (events.js:189:13)
    at writeAfterEnd (_stream_writable.js:245:10)
    at Socket.Writable.write (_stream_writable.js:291:5)
    [... lines matching original stack trace ...]
    at FSReqWrap.wrapper [as oncomplete] (fs.js:462:17)
```
