### ISSUE TITLE
0 of undefined in exports.unpack in websocket

### ISSUE THREAD

**Issue by Deivu** [discordjs/discord.js#3222]
**Please describe the problem you are having in as much detail as possible:**
This issue happened when the bot was running around 2 1/2 days.

StackTrace:
```
TypeError: Cannot read property '0' of undefined
    at Object.exports.unpack.data [as unpack] (/home/admuser/prod/node_modules/discord.js/src/WebSocket.js:24:23)
    at WebSocketShard.onMessage (/home/admuser/prod/node_modules/discord.js/src/client/websocket/WebSocketShard.js:258:26)
    at WebSocket.onMessage (/home/admuser/prod/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/home/admuser/prod/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:189:13)
    at Receiver.dataMessage (/home/admuser/prod/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/home/admuser/prod/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/home/admuser/prod/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/home/admuser/prod/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Receiver.Writable.write (_stream_writable.js:294:11)
    at TLSSocket.socketOnData (/home/admuser/prod/node_modules/ws/lib/websocket.js:864:35)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
```
Line that I think where this happened 
https://github.com/discordjs/discord.js/blob/master/src/WebSocket.js#L24

On how to reproduce,I am not sure due to they rebooted the bot "again" without me knowing it, but I didn't think it stopped the bot from responding 

Optional Deps Installed:
 "bufferutil": "^4.0.1"
 "erlpack": "discordapp/erlpack"

**Further details:**
- discord.js version: 12-dev `b5320299f79c5ccfba8dac95699d2d7202682b56`
- Node.js version: 10.13.0
- Operating system: Ubuntu 18.10
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by amishshah** [comment]
Could you tell us the version of ws/uws you are using?

**Comment by Deivu** [comment]
ws: 6.2.1

**Comment by CatsMiaow** [comment]
same issue
discord.js: de79bba965c5d5200c1ccdc3b8c7d581b23d4a23
node.js: v10.15.3
ws: v6.2.1
os: Linux version 4.14.62-65.117.amzn1.x86_64
```sh
TypeError: Cannot read property '0' of null
    at Object.exports.unpack.data [as unpack] (/home/user/bot/node_modules/discord.js/src/WebSocket.js:24:23)
    at WebSocketShard.onMessage (/home/user/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:258:26)
    at WebSocket.onMessage (/home/user/bot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/home/user/bot/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:189:13)
    at Receiver.dataMessage (/home/user/bot/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/home/user/bot/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/home/user/bot/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/home/user/bot/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Receiver.Writable.write (_stream_writable.js:294:11)
    at TLSSocket.socketOnData (/home/user/bot/node_modules/ws/lib/websocket.js:864:35)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
Error: WebSocket was closed before the connection was established
    at WebSocket.close (/home/user/bot/node_modules/ws/lib/websocket.js:217:14)
    at WebSocketShard.destroy (/home/user/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:593:23)
    at WebSocketShard.sendHeartbeat (/home/user/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:457:12)
    at Timeout.heartbeatInterval.manager.client.setInterval [as _onTimeout] (/home/user/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:446:73)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by amishshah** [comment]
Hi, can either of you still reproduce this issue?

**Comment by Deivu** [comment]
At the moment I don't see anything yet so far, and I can't tell if it would or would not happen again.

**Comment by amishshah** [comment]
@Deivu thanks, I think the best thing to do is to just trial it for a few days and close the issue if you can no longer reproduce. Let's hope #3301 fixed this!

**Comment by Deivu** [comment]
Seems like I cannot reproduce this anymore, the bot is online for 3 days now.
Closing this since I think it is fixed now, I'll just reopen if this happens again.

- Master Commit: `8652e47c14eccd1c8cab27f0d1acb8d7335349e8` right now
