### ISSUE TITLE
Invalid character in header content ["Authorization"]

### ISSUE THREAD

**Issue by LegitBaboulinet** [discordjs/discord.js#3253]
Hi, 
I'm having trouble to run my bot on Linux. It works perfectly well on Windows and crashes on Linux.
I think the issue has to do with the different encoding on Linux because it occurs when Discord.js tries to login to the Discord API, having the token as a header parameter.

**Here's the line that causes the issue:**
``` js
if (this.auth) request.set('Authorization', this.getAuth());
```
**Here's the stacktrace:**
```
(node:24329) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]
    at ClientRequest.setHeader (_http_outgoing.js:485:3)
    at Snekfetch.set (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/snekfetch/src/index.js:75:20)
    at APIRequest.gen (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/discord.js/src/client/rest/APIRequest.js:39:28)
    at resolve (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:59:20)
    at new Promise (<anonymous>)
    at SequentialRequestHandler.execute (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:58:12)
    at SequentialRequestHandler.handle (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:119:10)
    at SequentialRequestHandler.push (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:48:10)
    at Promise (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/discord.js/src/client/rest/RESTManager.js:27:15)
    at new Promise (<anonymous>)
    at RESTManager.push (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/discord.js/src/client/rest/RESTManager.js:26:12)
    at RESTManager.makeRequest (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/discord.js/src/client/rest/RESTManager.js:53:17)
    at RESTMethods.getGateway (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/discord.js/src/client/rest/RESTMethods.js:48:22)
    at ClientManager.connectToWebSocket (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/discord.js/src/client/ClientManager.js:41:30)
    at Promise (/home/lucas/Workspaces/js/udev-discord-bot/node_modules/discord.js/src/client/rest/RESTMethods.js:36:27)
    at new Promise (<anonymous>)
(node:24329) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24329) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

- discord.js version: 11.4.2
- Node.js version: 11.14.0
- Operating system: Linux Manjaro 4.19.36-1
- Priority: medium

**Comment by didinele** [comment]
Cannot reproduce on latest master, latest Manjaro Gnome, node 12.1.0

**Comment by LegitBaboulinet** [comment]
I was getting ready to try with master, before realizing that it might be because I read the token from a file. So I tried starting the client while passing the token directly.
And it worked.

So the issue isn't from discord.js. It's from fs when reading the file.

Sorry for the inconvenience.

**Comment by didinele** [comment]
FYI, you dont have to readFile, if its a .json file you can require it using node
