### ISSUE TITLE
Cannot read property message.member

### ISSUE THREAD

**Issue by rosivanov** [discordjs/discord.js#3297]
It's weird but see below
```
client.on('message', message => {
  console.log( message.member.displayName )
})
```
Error
```
/app/app/index.js:27

  console.log( message.member.displayName )
                              ^
TypeError: Cannot read property 'displayName' of null

at Client.client.on.message (/app/app/index.js:27:31)

    at emitOne (events.js:116:13)

    at Client.emit (events.js:211:7)

    at MessageCreateHandler.handle (/rbd/pnpm-volume/8841fa5b-2426-4fe4-888d-738971003596/node_modules/.registry.npmjs.org/discord.js/11.4.2/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)

    at WebSocketPacketManager.handle (/rbd/pnpm-volume/8841fa5b-2426-4fe4-888d-738971003596/node_modules/.registry.npmjs.org/discord.js/11.4.2/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)

    at WebSocketConnection.onPacket (/rbd/pnpm-volume/8841fa5b-2426-4fe4-888d-738971003596/node_modules/.registry.npmjs.org/discord.js/11.4.2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)

    at WebSocketConnection.onMessage (/rbd/pnpm-volume/8841fa5b-2426-4fe4-888d-738971003596/node_modules/.registry.npmjs.org/discord.js/11.4.2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)

    at WebSocket.onMessage (/rbd/pnpm-volume/8841fa5b-2426-4fe4-888d-738971003596/node_modules/.registry.npmjs.org/ws/4.1.0/node_modules/ws/lib/event-target.js:120:16)

    at emitOne (events.js:116:13)

    at WebSocket.emit (events.js:211:7)
```

```
"discord.js": "^11.4.2"
node v10.15.3
npm v6.4.1
```

The error occurs with any property of `GuildMember Class`.
`Message Class` is readable and `message.id` works fine.
It has been tested on glitch.com and local machine (win10) and the error exists on both.

Why this can happen?

**Comment by SpaceEEC** [comment]
Because the member is uncached or the message was sent in a dm.

**Comment by rosivanov** [comment]
@SpaceEEC Okay how can i get GuildMember in this case? It was TextChannel not DM.
Eventually what do i need is this `message.member.permissions.has(...)`

**Comment by SpaceEEC** [comment]
You can fetch any member of the guild by using [`Guild#fetchMember`](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=fetchMember).

Since the issue tracker is only for bug reports and enhancement suggestions, please ask further questions in our [Discord server](https://discord.gg/bRCvFy9) instead.

**Comment by rosivanov** [comment]
@SpaceEEC thanks
