### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'voiceChannel' of undefined

### ISSUE THREAD

**Issue by Milkywhey** [discordjs/discord.js#3298]
Hey,
I got an error that i don't cleary understand as i see in a video the code work with no problem so i guess the way that is work as changed a bit.
I guess it's from the guild part
Here's my code :
`
const ytdl = require('ytdl-core');

exports.run = async(client, message, args, ops) => {
  
  if (!message.membre.voiceChannel) return message.channel.send('Entrez dans un canal audio !');
  if (message.guild.me.voiceChannel) return message.channel.send('Désolé, le bot est déjà occuper autre part.	(¬‿¬ )');
  if (!args[0]) return message.channel.send('Désolé, veuillez entrez une URL pour executer cette commande.');

  let validate = await ytdl.validateURL(args[0]);
  if (!validate) return message.channel.send('Désolé, veuillez entrez une URL **correcte** pour executer cette commande.');

  let info = await ytdl.getInfo(args[0]);

  let connection = await message.member.voiceChannel.join();

  let dispatcher = await connection.play(ytdl(args[0], { filter : 'audioonly'}));

  message.channel.send(`Lecture en cours : ${info.title}`);
}
`

And this is the output in Terminal :

`(node:31728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:31728) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'voiceChannel' of undefined
    at Object.exports.run (/Users/nop_dont_see_my_name/Onyx/commands/play.js:3:23)
    at Client.<anonymous> (/Users/nop_dont_see_my_name/Onyx/server.js:16:17)
    at Client.emit (events.js:200:13)
    at MessageCreateHandler.handle (/Users/nop_dont_see_my_name/Onyx/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/Users/nop_dont_see_my_name/Onyx/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/Users/nop_dont_see_my_name/Onyx/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/Users/nop_dont_see_my_name/Onyx/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/Users/nop_dont_see_my_name/Onyx/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:200:13)
    at Receiver.receiverOnMessage (/Users/nop_dont_see_my_name/Onyx/node_modules/ws/lib/websocket.js:789:20)
(node:31728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
`
So can someone try to help me with this ?

- discord.js version: discord.js@11.5.0
- Node.js version: v12.3.1
- Operating system: macOS 10.14.5

**Comment by Milkywhey** [comment]
I fix it.

**Comment by julien040** [comment]
How ?

**Comment by Androz2091** [comment]
They use `message.member` instead of `message.membre`.
