### ISSUE TITLE
How would I fix this Error? (Help)

### ISSUE THREAD

**Issue by JakubDynak** [discordjs/discord.js#3340]
(node:32) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Access
at item.request.gen.end (/home/container/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
at then (/home/container/node_modules/discord.js/node_modules/snekfetch/src/index.js:215:21)
at process._tickCallback (internal/process/next_tick.js:68:7)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 67)
events.js:180
throw err; // Unhandled 'error' event
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
at VoiceWebSocket.emit (events.js:178:17)
at VoiceWebSocket.onError (/home/container/node_modules/discord.js/src/client/voice/VoiceWebSocket.js:156:10)
at WebSocket.onError (/home/container/node_modules/ws/lib/event-target.js:128:16)
at WebSocket.emit (events.js:189:13)
at _receiver.cleanup (/home/container/node_modules/ws/lib/websocket.js:211:14)
at Receiver.cleanup (/home/container/node_modules/ws/lib/receiver.js:535:15)
at WebSocket.finalize (/home/container/node_modules/ws/lib/websocket.js:206:20)
at TLSSocket.emit (events.js:189:13)
at emitErrorNT (internal/streams/destroy.js:82:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)

**Comment by anandre** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions.
You won't receive any basic help here.

Or look on the official Discord.js guide:

https://discordjs.guide/popular-topics/permissions-extended.html#implicit-permissions

**Comment by JakubDynak** [comment]
> 
> 
> If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
> https://discord.gg/bRCvFy9
> This issue tracker is only for bug reports and enhancement suggestions.
> You won't receive any basic help here.
> 
> Or look on the official Discord.js guide:
> 
> https://discordjs.guide/popular-topics/permissions-extended.html#implicit-permissions

Lmao, this is a bug, that's why I am here! I know how to install discord.js.

**Comment by JakubDynak** [comment]
Also forgot to mention in my message that it also restarts when that error comes through.

**Comment by bdistin** [comment]
That is not a bug with the library, but with your usage, as such you need to ask for help in the discord server. This issue tracker is not for help and support.

**Comment by JakubDynak** [comment]
Yes, I know, but this has nothing to do with having problems with connecting to the voice channels. I know how my bot works and it would have sent a different error message. My hosting providers said go request an issue here because they don't even know how to fix it and said to report as a bug.

**Comment by JakubDynak** [comment]
But I will go contact the Discord, thank you for your help.
