### ISSUE TITLE
Date being undefined on message

### ISSUE THREAD

**Issue by Koyamie** [discordjs/discord.js#3358]
**Please describe the problem you are having in as much detail as possible:**
Having an error when **data** is undefined on message event
```js
TypeError: Cannot read property 'id' of undefined
    at Map.add (/home/koyamie/Koya/node_modules/discord.js/src/stores/DataStore.js:20:42)
    at ClientApplication._patch (/home/koyamie/Koya/node_modules/discord.js/src/structures/ClientApplication.js:73:83)
    at new ClientApplication (/home/koyamie/Koya/node_modules/discord.js/src/structures/ClientApplication.js:17:10)
    at Message._patch (/home/koyamie/Koya/node_modules/discord.js/src/structures/Message.js:152:43)
    at new Message (/home/koyamie/Koya/node_modules/discord.js/src/structures/Message.js:42:20)
    at Map.add (/home/koyamie/Koya/node_modules/discord.js/src/stores/DataStore.js:24:32)
    at Map.add (/home/koyamie/Koya/node_modules/discord.js/src/stores/MessageStore.js:18:18)
    at MessageCreateAction.handle (/home/koyamie/Koya/node_modules/discord.js/src/client/actions/MessageCreate.js:13:40)
    at Object.module.exports [as MESSAGE_CREATE] (/home/koyamie/Koya/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/koyamie/Koya/node_modules/discord.js/src/client/websocket/WebSocketManager.js:391:31)
    at WebSocketShard.onPacket (/home/koyamie/Koya/node_modules/discord.js/src/client/websocket/WebSocketShard.js:418:22)
    at WebSocketShard.onMessage (/home/koyamie/Koya/node_modules/discord.js/src/client/websocket/WebSocketShard.js:274:10)
    at WebSocket.onMessage (/home/koyamie/Koya/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:193:13)
    at Receiver.receiverOnMessage (/home/koyamie/Koya/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:193:13)
```

**Further details:**
- discord.js version: latest master
- Node.js version: 11.15.0
- Operating system: debian 9
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Should be fixed with the referenced commit
