### ISSUE TITLE
Unhandled Promise Rejection warning in v12

### ISSUE THREAD

**Issue by conorpo** [discordjs/discord.js#3361]
When the .play method on the voice connection is called alot fast then it crashes and gets this error.  I played a short (less than 1 sec) .wav file. This error only happens when you call the function when something has already started playing recently (<200 ms ago) and it is kind of inconsistent.

I get this error in my terminal
```
(node:21916) UnhandledPromiseRejectionWarning: RangeError: Source is too large 
    at Uint16Array.set (<anonymous>)
    at OpusScript.encode (D:\Coding\github\soundboard-bot\node_modules\opusscript\index.js:51:16)        
    at Encoder._encode (D:\Coding\github\soundboard-bot\node_modules\prism-media\src\opus\Opus.js:54:25) 
    at Encoder._transform (D:\Coding\github\soundboard-bot\node_modules\prism-media\src\opus\Opus.js:137:30)
    at Encoder.Transform._read (_stream_transform.js:190:10)
    at Encoder.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Encoder.Writable.write (_stream_writable.js:299:11)
    at VolumeTransformer.ondata (_stream_readable.js:693:20)
(node:21916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either 
by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The error event on the connection object doesn't trigger.

After I get the warning, the connection no longer works, when I try playing a file it doesnt do anything (doesn't give any error for this either)

**Further details:**
- discord.js version: master branch
- Node.js version: 11.9
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
Not that big of a deal, I can implement my own system to limit the rate at which the function is called.

- [x] I have also tested the issue on latest master, commit hash:

**Comment by amishshah** [comment]
Does the issue go away when you use `node-opus`?

**Comment by conorpo** [comment]
Yeah!! Thanks man, I was using `opusscript` before. Switched to `node-opus` and everything is good!
