### ISSUE TITLE
Prism-media not working under discord.js

### ISSUE THREAD

**Issue by Crystalflxme** [discordjs/discord.js#3375]
I'm trying to get my discord bot to speak but I get this error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at Object.spawn (child_process.js:545:16)
    at new FfmpegProcess (C:\Users\BillPoorman\Desktop\Cylbot\node_modules\discord.js\node_modules\prism-media\src\transcoders\ffmpeg\FfmpegProcess.js:14:33)
    at FfmpegTranscoder.transcode (C:\Users\BillPoorman\Desktop\Cylbot\node_modules\discord.js\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:34:18)
    at MediaTranscoder.transcode (C:\Users\BillPoorman\Desktop\Cylbot\node_modules\discord.js\node_modules\prism-media\src\transcoders\MediaTranscoder.js:27:31)
    at Prism.transcode (C:\Users\BillPoorman\Desktop\Cylbot\node_modules\discord.js\node_modules\prism-media\src\Prism.js:13:28)
    at AudioPlayer.playUnknownStream (C:\Users\BillPoorman\Desktop\Cylbot\node_modules\discord.js\src\client\voice\player\AudioPlayer.js:97:35)
    at VoiceConnection.playStream (C:\Users\BillPoorman\Desktop\Cylbot\node_modules\discord.js\src\client\voice\VoiceConnection.js:478:24)
    at Promise.then.connection (C:\Users\BillPoorman\Desktop\Cylbot\node_modules\discord.js-musicbot-addon\index.js:1311:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I have no idea how to fix this. I've already edited bits of prism-media because it wasn't reading the correct ffmpeg module and giving me a different error. Now that it's reading the correct one, I get this problem.

**Comment by SpaceEEC** [comment]
If you are using `ffmpeg-binaries`, uninstall it and try [`ffmpeg-static`] or a regular `FFmpeg` [installation][FFmpeg] instead.

Otherwise I suggest to open an issue at the [prism-media] repository.

[`ffmpeg-static`]:https://www.npmjs.com/package/ffmpeg-static
[FFmpeg]:https://www.ffmpeg.org/download.html
[prism-media]:https://github.com/amishshah/prism-media/issues
