### ISSUE TITLE
Error: Incorrect login details were provided.

### ISSUE THREAD

**Issue by mightybruno** [discordjs/discord.js#3385]
When creating the app in typescript (haven't tried in js tho):
```ts

ENV.CLIENT.login("<token>");

```

```
(node:706) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.client.ws.connection.once.event (~/project/modules/bot/node_modules/discord.js/src/client/ClientManager.js:48:41)
    at Object.onceWrapper (events.js:281:20)
    at WebSocketConnection.emit (events.js:193:13)
    at WebSocketConnection.EventEmitter.emit (domain.js:481:20)
    at WebSocketConnection.onClose (~/project/modules/bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:390:10)
    at WebSocket.onClose (~/project/modules/bot/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:193:13)
    at WebSocket.EventEmitter.emit (domain.js:481:20)
    at WebSocket.emitClose (~/project/modules/bot/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (~/project/modules/bot/node_modules/ws/lib/websocket.js:850:15)
(node:706) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:706) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Low quality, but should give you the idea: https://imgur.com/a/dcuFcFH

**Further details:**
- discord.js version: latest
- npm version: latest
- Node.js version: latest
- Operating system: Manjaro 5.1.15
- Priority this issue should have – please be realistic and elaborate if possible: high if replicable

**I'm sure I have the right token.** I've also tried creating new app.

**Comment by almostSouji** [comment]
If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
  https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by mightybruno** [comment]
copied client secret instead of bot token

**Comment by ytingyeu** [comment]
I have a question about this issue. Is there any way to handle incorrect login? I tried to catch this reject with a simple try..catch block. But it still throws `UnhandledPromiseRejectionWarning`
```
try {
  client.login(discordToken);
} catch (error) {
  console.log(error);
}
```
