### ISSUE TITLE
WebSocket Problem

### ISSUE THREAD

**Issue by CyclicPlus** [discordjs/discord.js#3478]
So, I was making a Discord bot and it went smoothly, until i wrote the commands,

I tried to run the bot with "node ." but it gave me this error:
ReferenceError: message is not defined
    at Client.<anonymous> (C:\Users\X\NewTube\discord\updates\index.js:14:16)
←[90m    at Client.emit (events.js:209:13)←[39m
    at MessageCreateHandler.handle (C:\Users\X\NewTube\discord\updates\node_modules\←[4mdiscord.js←[24m\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\X\NewTube\discord\updates\node_modules\←[4mdiscord.js←[24m\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\Users\X\NewTube\discord\updates\node_modules\←[4mdiscord.js←[24m\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\X\NewTube\discord\updates\node_modules\←[4mdiscord.js←[24m\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\X\NewTube\discord\updates\node_modules\←[4mws←[24m\lib\event-target.js:120:16)
←[90m    at WebSocket.emit (events.js:209:13)←[39m
    at Receiver.receiverOnMessage (C:\Users\X\NewTube\discord\updates\node_modules\←[4mws←[24m\lib\websocket.js:789:20)
←[90m    at Receiver.emit (events.js:209:13)←[39m

Any help is appreciated.

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
