### ISSUE TITLE
I have error on roles collection

### ISSUE THREAD

**Issue by esponjosin** [discordjs/discord.js#3481]
at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'guild' of undefined
    at new GuildMemberRoleStore (/rbd/pnpm-volume/e0139084-8578-4dda-9176-4c5cb07344a6/node_modules/.github.com/discordjs/discord.js/d05334fd3cd8fb913e869654f25eb8230493de11/node_modules/discord.js/src/stores/GuildMemberRoleStore.js:15:25)
    at Map.filter (/rbd/pnpm-volume/e0139084-8578-4dda-9176-4c5cb07344a6/node_modules/.registry.npmjs.org/@discordjs/collection/0.1.3/node_modules/@discordjs/collection/dist/index.js:147:25)

![image](https://user-images.githubusercontent.com/42915103/65392523-40725b00-dd4c-11e9-9910-15c852f2abbd.png)

```js

member.roles.filter(m => m.name !== "@everyone").sort((a, b) => b.position - a.position).map(m => m.toString()).join(" ") || "No one";

```

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
