### ISSUE TITLE
AbortError: The user aborted a request.

### ISSUE THREAD

**Issue by zechaos031** [discordjs/discord.js#3498]
I have this error in log when one command was execute, I already reinstall discord.js

I use Discord.js 12

**Comment by Androz2091** [comment]
I regularly have the same problem, but I can't find the cause...

**Comment by zechaos031** [comment]
Reassuring :/

**Comment by vladfrangu** [comment]
This is a bit of a duplicate of https://github.com/discordjs/discord.js/issues/3471

Also, next time, don't delete the template. It exists for a reason.

**Comment by danbulant** [comment]
Getting the same error. Bot runs just fine for x hours (or even days) but then I get this error.

It's UnhandledRejection, full output:
```
 [REJECTION] HTTPError [AbortError]: The user aborted a request.
     at RequestHandler.execute (PROJECT_PATH/node_modules/discord.js/src/rest/RequestHandler.js:107:21)
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
   code: 500,
   method: 'get',
   path: '/gateway/bot'
}
``` (the `[REJECTION]` is added there by my logger, meaning it's Unhandled rejection)

**Comment by LeManock** [comment]
> Getting the same error. Bot runs just fine for x hours (or even days) but then I get this error.
> 
> It's UnhandledRejection, full output:
> 
> ```
>  [REJECTION] HTTPError [AbortError]: The user aborted a request.
>      at RequestHandler.execute (PROJECT_PATH/node_modules/discord.js/src/rest/RequestHandler.js:107:21)
> at processTicksAndRejections (internal/process/task_queues.js:97:5) {
>    code: 500,
>    method: 'get',
>    path: '/gateway/bot'
> }
> ```
> 
> (the `[REJECTION]` is added there by my logger, meaning it's Unhandled rejection)

I have the same problem and I am waiting for a response from Discord

**Comment by vladfrangu** [comment]
guys, two things

1. This is a closed (duplicate) issue; you can check more and a proposed library fix on #3471
2. This is not necessarily on Discord's end; and most likely you won't notice once we implement the fixes.

**Comment by kety-folf** [comment]
`HTTPError [AbortError]: The user aborted a request.
    at RequestHandler.execute (/home/pi/node_stuff/Kety_folfs_bot_2_0/node_modules/discord.js/src/rest/RequestHandler.js:107:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 500,
  method: 'post',
  path: '/channels/735679498774642749/messages'
}
` i get this with my bot

**Comment by brisdevs** [comment]
This is an error happening within the discord.js library if a web request is stuck for a long time, which might happen due to an outage or bad internet connection. Those connections are killed with that error message to free resources.

Those errors should not be fatal and can be ignored.

**Comment by robin-fc** [comment]
> `HTTPError [AbortError]: The user aborted a request. at RequestHandler.execute (/home/pi/node_stuff/Kety_folfs_bot_2_0/node_modules/discord.js/src/rest/RequestHandler.js:107:21) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5) { code: 500, method: 'post', path: '/channels/735679498774642749/messages' } ` i get this with my bot

Have you resolved this 500 problem?

**Comment by robin-fc** [comment]
> This is an error happening within the discord.js library if a web request is stuck for a long time, which might happen due to an outage or bad internet connection. Those connections are killed with that error message to free resources.
> 
> Those errors should not be fatal and can be ignored.

Have you resolved this problem?

**Comment by NotSoEvilDead** [comment]
> This is an error happening within the discord.js library if a web request is stuck for a long time, which might happen due to an outage or bad internet connection. Those connections are killed with that error message to free resources.
> 
> Those errors should not be fatal and can be ignored.

This is the correct answer.  Whoever maintains discord.js should have fixed this a LONG time ago.
