### ISSUE TITLE
Returns as an error while awaiting messages.

### ISSUE THREAD

**Issue by outlaylol** [discordjs/discord.js#3541]
Discord.js version: 12x
node version: 8.15.1

error: /rbd/pnpm-volume/50bf86ab-412a-480b-b96e-e945c59b5754/node_modules/discord.js/src/structures/interfaces/Collector.js:203
  async *[Symbol.asyncIterator]() {
        ^
SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rbd/pnpm-volume/50bf86ab-412a-480b-b96e-e945c59b5754/node_modules/discord.js/src/structures/MessageCollector.js:3:19)

code:   const msgs = await msg.channel.awaitMessages(res => res.author.id === msg.author.id, {
               max: 1,
               time: 30000
           });

**Comment by Jiralite** [comment]
As stated in the documentation & installation, node.js 10.0.0 or newer is required.

This issue tracker is only for bug reports and enhancement suggestions. Use the support Discord for queries please!

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
