### ISSUE TITLE
TypeError: Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by SolninjaA** [discordjs/discord.js#3608]
Hi! I have been creating a command handler and I have found this problem:

client.commands.set(pull.name, pull);
                                ^

TypeError: Cannot read property 'set' of undefined
    at C:\Users\solni\OneDrive\Desktop\Discord Bot\handler\command.js:15:33
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\solni\OneDrive\Desktop\Discord Bot\handler\command.js:8:32)
    at C:\Users\solni\OneDrive\Desktop\Discord Bot\index.js:16:36
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\solni\OneDrive\Desktop\Discord Bot\index.js:15:13)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)

Please help.

**Comment by Monbrey** [comment]
`client.commands` needs to be defined by you - it's not a property that already exists on `Client`. Most guides detail this step, and you have probably missed it.

The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord](https://discord.gg/bRCvFy9) server instead of opening an issue – you will get redirected there anyway.

**Comment by NameLord** [comment]
thanks for the fix code we wasted the time.
