### ISSUE TITLE
Discord V12 Can't not play stream buffer but v11 does

### ISSUE THREAD

**Issue by HellCatVN** [discordjs/discord.js#3653]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
```js
\node_modules\prism-media\src\opus\Opus.js:58
    return this.encoder.decode(buffer, Opus.name !== 'node-opus' ? this._options.frameSize : null);
                        ^

TypeError: The compressed data passed is corrupted
    at Decoder._decode (\node_modules\prism-media\src\opus\Opus.js:58:25)
    at Decoder._transform (\node_modules\prism-media\src\opus\Opus.js:183:20)
    at Decoder.Transform._read (_stream_transform.js:190:10)
    at Decoder.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Decoder.Writable.write (_stream_writable.js:299:11)
    at PassThrough.ondata (_stream_readable.js:693:20)
    at PassThrough.emit (events.js:198:13)
    at PassThrough.Readable.read (_stream_readable.js:491:10)
    at flow (_stream_readable.js:957:34)
    at resume_ (_stream_readable.js:938:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Further details:**
- discord.js version:  v12 (github:discordjs/discord.js)
- Node.js version: v10.16.0
- Operating system: Win 10
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by Clemens-E** [comment]
The Issue template is there to be filled out, not to be totally ignored like you did.
