### ISSUE TITLE
WebSocket onmessage connection is null

### ISSUE THREAD

**Issue by xKesvaL** [discordjs/discord.js#3706]
**Please describe the problem you are having in as much detail as possible:**
I don't know when, but at some time my bot give me this error:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'onmessage' of null
    at WebSocketShard._cleanupConnection (C:\Projects\Tekato\node_modules\discord.js\src\client\websocket\WebSocketShard.js:718:31)
    at WebSocketShard.<anonymous> (C:\Projects\Tekato\node_modules\discord.js\src\client\websocket\WebSocketManager.js:248:15)
    at WebSocketShard.emit (events.js:210:5)
    at WebSocketShard.destroy (C:\Projects\Tekato\node_modules\discord.js\src\client\websocket\WebSocketShard.js:692:12)
    at WebSocketShard._send (C:\Projects\Tekato\node_modules\discord.js\src\client\websocket\WebSocketShard.js:640:12)
    at WebSocketShard.processQueue (C:\Projects\Tekato\node_modules\discord.js\src\client\websocket\WebSocketShard.js:666:12)
    at WebSocketShard.send (C:\Projects\Tekato\node_modules\discord.js\src\client\websocket\WebSocketShard.js:628:10)
    at WebSocketManager.broadcast (C:\Projects\Tekato\node_modules\discord.js\src\client\websocket\WebSocketManager.js:333:53)
    at ClientPresence.set (C:\Projects\Tekato\node_modules\discord.js\src\structures\ClientPresence.js:21:22)
```

This error appeared when i updated discord.js (i was already in master branch)

- discord.js version: master
- Node.js version: 12.14.0
- Operating system: Windows 10 LTSB
- WebSocket version: 7.2.1
- Priority this issue should have: High priority because i can't do anything in my bot.

- [X] I have also tested the issue on latest master, commit hash: 69c79a4136619e4dcacfffb935aa9bd60aa2081c

**Comment by xKesvaL** [comment]
I added this temporarily to avoid the error if anyone has the same:
```diff
    _cleanupConnection() {
+     if (!this.connection) {
+       this.connection = {}
+     }
    this.connection.onopen =
    this.connection.onclose =
    this.connection.onerror =
    this.connection.onmessage = null;
```
WebSocketShard.js line 715

**Comment by xKesvaL** [comment]
I figured out why this was appening. I had a infinite loop that was fetching too many shard properties at one time. (Just forgot a multiplication)
I'm really dumb, sorry.
