### ISSUE TITLE
Music Bot Problem

### ISSUE THREAD

**Issue by younotcoolbro** [discordjs/discord.js#3735]
i get this error

TypeError: Cannot read property 'voiceChannel' of null
    at Client.<anonymous> (C:\Users\Alex\Desktop\Music-Bot\index.js:8:26)
    at Client.emit (events.js:223:5)
    at MessageCreateHandler.handle (C:\Users\Alex\Desktop\Music-Bot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Alex\Desktop\Music-Bot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\Users\Alex\Desktop\Music-Bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Alex\Desktop\Music-Bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Alex\Desktop\Music-Bot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:223:5)
    at Receiver.receiverOnMessage (C:\Users\Alex\Desktop\Music-Bot\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:223:5)

i get it to join voice channel for a second then it leaves

**Comment by kyranet** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
