### ISSUE TITLE
Discord Rich Embed issue [discord.js 12.0.1]

### ISSUE THREAD

**Issue by oliveradkins13** [discordjs/discord.js#3884]
`TypeError: Discord.RichEmbed is not a constructor
    at Object.execute (C:\Users\oliver\Desktop\DexSoft BOT\commands\about.js:11:17)
    at Client.<anonymous> (C:\Users\oliver\Desktop\DexSoft BOT\index.js:81:11)
    at Client.emit (events.js:321:20)
    at MessageCreateAction.handle (C:\Users\oliver\Desktop\DexSoft BOT\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\oliver\Desktop\DexSoft BOT\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\oliver\Desktop\DexSoft BOT\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\oliver\Desktop\DexSoft BOT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (C:\Users\oliver\Desktop\DexSoft BOT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\oliver\Desktop\DexSoft BOT\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:321:20)`
![image](https://user-images.githubusercontent.com/56483932/75695059-67d93680-5ca1-11ea-8ee8-4d9231e43db9.png)

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by zMigueel** [comment]
is now MessageEmbed
