### ISSUE TITLE
error when trying to add bot to voice

### ISSUE THREAD

**Issue by dragon2522** [discordjs/discord.js#3923]
Im trying to make a joke bot for my friends and i to use and every time i try to use the "voiceChannel.join()" command it wont seem to work and causes an error. I suspect its because of my discord.js file and not having the right files but im not sure. I suspect this because of the fact that i literally copied and pasted a code from a solution i found but i just want to make sure. note i am in a voice channel when executing command, also dont mind the name lol.

ERROR MESSAGE
TypeError: Cannot read property 'join' of undefined
    at Client.<anonymous> (C:\Users\Admin\Desktop\E-Girl Discord Bot\index.js:72:15)
    at Client.emit (events.js:316:20)
    at MessageCreateAction.handle (C:\Users\Admin\Desktop\E-Girl Discord Bot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Admin\Desktop\E-Girl Discord Bot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Admin\Desktop\E-Girl Discord Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\Admin\Desktop\E-Girl Discord Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (C:\Users\Admin\Desktop\E-Girl Discord Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\Admin\Desktop\E-Girl Discord Bot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:316:20)
    at Receiver.receiverOnMessage (C:\Users\Admin\Desktop\E-Girl Discord Bot\node_modules\ws\lib\websocket.js:801:20)

CODE:
const Discord = require('discord.js');
const { prefix, token } = require("./config.json");
const client = new Discord.Client();

client.once('ready', () => { console.log('Ready!!') })
 client.on('message', message => {
    if (message.content === '!play') {
      const channel = message.member.voiceChannel;
      channel.join()
      .then(connection => console.log('Connected!'))
      .catch(console.error);
    }
  });
client.login(token);

**Comment by NotSugden** [comment]
the issue template was not put there to be removed, what version of discord.js are you using? `npm ls discord.js` will tell you this
