### ISSUE TITLE
At new version there's a syntax error

### ISSUE THREAD

**Issue by Kemal-coder** [discordjs/discord.js#3972]
Hello, i made a bot and i upgraded discord.js but at version 12.0.2 There's a error like that;

`/rbd/pnpm-volume/512f7eb4-70cf-4d94-81c1-d6b0fabbb66f/node_modules/.registry.npmjs.org/discord.js/12.0.2/node_modules/discord.js/src/client/Client.js:40
    } catch {
            ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rbd/pnpm-volume/512f7eb4-70cf-4d94-81c1-d6b0fabbb66f/node_modules/.registry.npmjs.org/discord.js/12.0.2/node_modules/discord.js/src/index.js:8:11)
`

What am i going to do?

**Comment by DevYukine** [comment]
Upgrade your node.js version, see #3796 
This is not an issue with discord.js
