### ISSUE TITLE
Bot crashes when moving channel from one category to another

### ISSUE THREAD

**Issue by Raptor2277** [discordjs/discord.js#3981]
**Please describe the problem you are having in as much detail as possible:**
Have a simple bot setup. When moving a text channel (created by the bot) from one category to another, I get this error.

```
C:\Users\Vasile\Desktop\app_bot\node_modules\discord.js\src\client\actions\ChannelUpdate.js:15
      if (ChannelTypes[channel.type.toUpperCase()] !== data.type) {
                                    ^

TypeError: channel.type.toUpperCase is not a function
    at ChannelUpdateAction.handle (C:\Users\Vasile\Desktop\app_bot\node_modules\discord.js\src\client\actions\ChannelUpdate.js:15:37)
    at Object.module.exports [as CHANNEL_UPDATE] (C:\Users\Vasile\Desktop\app_bot\node_modules\discord.js\src\client\websocket\handlers\CHANNEL_UPDATE.js:6:57)
    at WebSocketManager.handlePacket (C:\Users\Vasile\Desktop\app_bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\Vasile\Desktop\app_bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (C:\Users\Vasile\Desktop\app_bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\Vasile\Desktop\app_bot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (C:\Users\Vasile\Desktop\app_bot\node_modules\ws\lib\websocket.js:801:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (C:\Users\Vasile\Desktop\app_bot\node_modules\ws\lib\receiver.js:436:14)
```

**Include a reproducible code sample here, if possible:**
<details>
<summary>Code</summary>

```js 
handle: async function (message) {

        if (message.channel.name != "jeeves_bot") return;
        if (!message.content.startsWith("/createscout")) return;

        var split = message.content.split(" ");
        if(split.length != 2)
        {
            message.channel.send("Cant create app: incorrect command. Ex. /createapp Sooth-Ravencrest");
            return;
        }

        var messages = await message.channel.messages.fetch({limit: 100});
        var appMessage = messages.find(e => {
            if(!e.author.username == "Jeeves Recruitment") return false;
            if(!e.content == "A player is looking for a guild!") return false;
            
            var embed = e.embeds[0];
            if(!embed) return false;

            var title = embed.author.name.replace(/\s/g,'').toLowerCase();
            var match = split[1].toLowerCase();
            console.log(`${title} => ${match}`)
            var match = title.indexOf(match);
            if(match == -1) return false;
            
            return true;
        });

        if(!appMessage)
        {
            message.channel.send("Cant create app: cannot find application. It should be a message from <Jeeves Recruitment> with content <A player is looking for a guild!>")
            return;
        }

        var embed = appMessage.embeds[0];
        var title = embed.author.name.split("|")[0].trim();
        var channel = await guild.channels.create(title, {
            type: "text",
            parent: scoutingCategory,
            permissionOverwrites: [
                {
                    id: guild.roles.everyone,
                    deny: Discord.Permissions.ALL
                },
                {
                    id: guild.roles.cache.find(e => e.name == "Officer"),
                    allow: Discord.Permissions.ALL
                },
            ]
        });
        channel.send({ content: "bot_scout_handle", embed: embed });
    }
``` 
</details>

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by SpaceEEC** [comment]
Could you please fill out the "**Further details**" section?


> When moving a text channel (created by the bot) from one category to another, I get this error.

Could you add the related code for this into the issue too, please?

Please log the channel object before actually moving it:
`client.channels.cache.get('id')`
Especially the `type` property is interesting, since it seems to not be a string for some reason.

**Comment by Raptor2277** [comment]
> Please log the channel object before actually moving it:
> client.channels.cache.get('id')

I moving it in discord manually. That action is what crashes the bot.

**Comment by SpaceEEC** [comment]
That's not stopping you from logging it.

**Comment by Raptor2277** [comment]
Before moving.
```
TextChannel {
  type: 'text',
  deleted: false,
  id: '691361859348987925',
  name: 'jackxz-thrall-us',
  rawPosition: 15,
  parentID: '690445973649883197',
  permissionOverwrites: Collection [Map] {
    '690379773847011368' => PermissionOverwrites {
      id: '690379773847011368',
      type: 'role',
      deny: [Permissions],
      allow: [Permissions]
    },
    '690388886437756938' => PermissionOverwrites {
      id: '690388886437756938',
      type: 'role',
      deny: [Permissions],
      allow: [Permissions]
    }
  },
  topic: null,
  nsfw: false,
  lastMessageID: '691361874662523000',
  rateLimitPerUser: 0,
  lastPinTimestamp: null,
  guild: Guild {
    members: GuildMemberManager {
      cacheType: [Function: Collection],
      cache: [Collection [Map]],
      guild: [Circular]
    },
    channels: GuildChannelManager {
      cacheType: [Function: Collection],
      cache: [Collection [Map]],
      guild: [Circular]
    },
    roles: RoleManager {
      cacheType: [Function: Collection],
      cache: [Collection [Map]],
      guild: [Circular]
    },
    presences: PresenceManager {
      cacheType: [Function: Collection],
      cache: [Collection [Map]]
    },
    voiceStates: VoiceStateManager {
      cacheType: [Function: Collection],
      cache: Collection [Map] {},
      guild: [Circular]
    },
    deleted: false,
    available: true,
    id: '690379773847011368',
    shardID: 0,
    name: 'MKYC Recruiting',
    icon: null,
    splash: null,
    region: 'us-east',
    memberCount: 6,
    large: false,
    features: [],
    applicationID: null,
    afkTimeout: 300,
    afkChannelID: null,
    systemChannelID: '690379773847011371',
    embedEnabled: undefined,
    premiumTier: 0,
    premiumSubscriptionCount: 0,
    verificationLevel: 'NONE',
    explicitContentFilter: 'DISABLED',
    mfaLevel: 0,
    joinedTimestamp: 1584675310004,
    defaultMessageNotifications: 'ALL',
    systemChannelFlags: SystemChannelFlags { bitfield: 0 },
    vanityURLCode: null,
    description: null,
    banner: null,
    rulesChannelID: null,
    publicUpdatesChannelID: null,
    ownerID: '485118363475902474',
    emojis: GuildEmojiManager {
      cacheType: [Function: Collection],
      cache: Collection [Map] {},
      guild: [Circular]
    }
  },
  messages: MessageManager {
    cacheType: [Function: LimitedCollection],
    cache: LimitedCollection [Map] {
      '691361859575742497' => [Message],
      '691361874662523000' => [Message],
      maxSize: 200
    },
    channel: [Circular]
  },
  _typing: Map {}
}
```

Then I move the channel from one category to another. And above mentioned error happens.

**Comment by SpaceEEC** [comment]
>   `type: 'text',`

This looks valid to me, that shouldn't be able to cause that error.


Another approach: Can you try finding the offending channel after the error was thrown?
This here should do the trick:
```js
process.on('uncaughtException', e => {
  console.error('Unhandled exception:', e);
  console.log(
    'Offending channels:',
    client.channels.cache.filter(c => typeof c.type.toUpperCase !== 'function')
  );
  process.exit(1);
});
```

**Comment by Raptor2277** [comment]
```
Offending channels: Collection [Map] {
  '690379773847011370' => CategoryChannel {
    type: false,
    deleted: false,
    id: '690379773847011370',
    name: 'Voice Channels',
    rawPosition: 5,
    parentID: null,
    permissionOverwrites: Collection [Map] {},
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '690379773847011368',
      shardID: 0,
      name: 'MKYC Recruiting',
      icon: null,
      splash: null,
      region: 'us-east',
      memberCount: 6,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '690379773847011371',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1584675310004,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      vanityURLCode: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      ownerID: '485118363475902474',
      emojis: [GuildEmojiManager]
    }
  },
  '690379773847011371' => TextChannel {
    type: false,
    deleted: false,
    id: '690379773847011371',
    name: 'general',
    rawPosition: 15,
    parentID: '690388610498691073',
    permissionOverwrites: Collection [Map] {},
    topic: null,
    nsfw: false,
    lastMessageID: '690577339775451147',
    rateLimitPerUser: 0,
    lastPinTimestamp: null,
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '690379773847011368',
      shardID: 0,
      name: 'MKYC Recruiting',
      icon: null,
      splash: null,
      region: 'us-east',
      memberCount: 6,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '690379773847011371',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1584675310004,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      vanityURLCode: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      ownerID: '485118363475902474',
      emojis: [GuildEmojiManager]
    },
    messages: MessageManager {
      cacheType: [Function: LimitedCollection],
      cache: [LimitedCollection [Map]],
      channel: [Circular]
    },
    _typing: Map {}
  },
  '690379773847011372' => VoiceChannel {
    type: false,
    deleted: false,
    id: '690379773847011372',
    name: 'General',
    rawPosition: 0,
    parentID: '690379773847011370',
    permissionOverwrites: Collection [Map] {},
    bitrate: 64000,
    userLimit: 0,
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '690379773847011368',
      shardID: 0,
      name: 'MKYC Recruiting',
      icon: null,
      splash: null,
      region: 'us-east',
      memberCount: 6,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '690379773847011371',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1584675310004,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      vanityURLCode: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      ownerID: '485118363475902474',
      emojis: [GuildEmojiManager]
    }
  },
  '690388610498691073' => CategoryChannel {
    type: false,
    deleted: false,
    id: '690388610498691073',
    name: 'Welcome',
    rawPosition: 4,
    parentID: null,
    permissionOverwrites: Collection [Map] {},
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '690379773847011368',
      shardID: 0,
      name: 'MKYC Recruiting',
      icon: null,
      splash: null,
      region: 'us-east',
      memberCount: 6,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '690379773847011371',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1584675310004,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      vanityURLCode: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      ownerID: '485118363475902474',
      emojis: [GuildEmojiManager]
    }
  },
  '690388762487685180' => TextChannel {
    type: false,
    deleted: false,
    id: '690388762487685180',
    name: 'read-me',
    rawPosition: 14,
    parentID: '690388610498691073',
    permissionOverwrites: Collection [Map] {
      '690379773847011368' => [PermissionOverwrites],
      '690388886437756938' => [PermissionOverwrites]
    },
    topic: null,
    nsfw: false,
    lastMessageID: '691102757855166474',
    rateLimitPerUser: 0,
    lastPinTimestamp: null,
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '690379773847011368',
      shardID: 0,
      name: 'MKYC Recruiting',
      icon: null,
      splash: null,
      region: 'us-east',
      memberCount: 6,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '690379773847011371',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1584675310004,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      vanityURLCode: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      ownerID: '485118363475902474',
      emojis: [GuildEmojiManager]
    },
    messages: MessageManager {
      cacheType: [Function: LimitedCollection],
      cache: [LimitedCollection [Map]],
      channel: [Circular]
    },
    _typing: Map {}
  },
  '690392922301923428' => CategoryChannel {
    type: false,
    deleted: false,
    id: '690392922301923428',
    name: 'recruiting',
    rawPosition: 3,
    parentID: null,
    permissionOverwrites: Collection [Map] {},
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '690379773847011368',
      shardID: 0,
      name: 'MKYC Recruiting',
      icon: null,
      splash: null,
      region: 'us-east',
      memberCount: 6,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '690379773847011371',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1584675310004,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      vanityURLCode: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      ownerID: '485118363475902474',
      emojis: [GuildEmojiManager]
    }
  },
  '690397515966840872' => TextChannel {
    type: false,
    deleted: false,
    id: '690397515966840872',
    name: 'docs_webhook',
    rawPosition: 12,
    parentID: '690392922301923428',
    permissionOverwrites: Collection [Map] {
      '690379773847011368' => [PermissionOverwrites],
      '690388886437756938' => [PermissionOverwrites]
    },
    topic: null,
    nsfw: false,
    lastMessageID: '690439711126192138',
    rateLimitPerUser: 0,
    lastPinTimestamp: null,
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '690379773847011368',
      shardID: 0,
      name: 'MKYC Recruiting',
      icon: null,
      splash: null,
      region: 'us-east',
      memberCount: 6,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '690379773847011371',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1584675310004,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      vanityURLCode: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      ownerID: '485118363475902474',
      emojis: [GuildEmojiManager]
    },
    messages: MessageManager {
      cacheType: [Function: LimitedCollection],
      cache: [LimitedCollection [Map]],
      channel: [Circular]
    },
    _typing: Map {}
  },
  '690444127514656820' => TextChannel {
    type: false,
    deleted: false,
    id: '690444127514656820',
    name: 'officer_talk',
    rawPosition: 8,
    parentID: '690392922301923428',
    permissionOverwrites: Collection [Map] {
      '690379773847011368' => [PermissionOverwrites],
      '690388886437756938' => [PermissionOverwrites]
    },
    topic: null,
    nsfw: false,
    lastMessageID: '690454782716149772',
    rateLimitPerUser: 0,
    lastPinTimestamp: null,
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '690379773847011368',
      shardID: 0,
      name: 'MKYC Recruiting',
      icon: null,
      splash: null,
      region: 'us-east',
      memberCount: 6,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '690379773847011371',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1584675310004,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      vanityURLCode: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      ownerID: '485118363475902474',
      emojis: [GuildEmojiManager]
    },
    messages: MessageManager {
      cacheType: [Function: LimitedCollection],
      cache: [LimitedCollection [Map]],
      channel: [Circular]
    },
    _typing: Map {}
  },
  '690445558631891004' => CategoryChannel {
    type: false,
    deleted: false,
    id: '690445558631891004',
    name: 'Applications',
    rawPosition: 0,
    parentID: null,
    permissionOverwrites: Collection [Map] {
      '690379773847011368' => [PermissionOverwrites],
      '690388886437756938' => [PermissionOverwrites]
    },
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '690379773847011368',
      shardID: 0,
      name: 'MKYC Recruiting',
      icon: null,
      splash: null,
      region: 'us-east',
      memberCount: 6,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '690379773847011371',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1584675310004,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      vanityURLCode: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      ownerID: '485118363475902474',
      emojis: [GuildEmojiManager]
    }
  },
  '690445973649883197' => CategoryChannel {
    type: true,
    deleted: false,
    id: '690445973649883197',
    name: 'Scouting Logs',
    rawPosition: 1,
    parentID: null,
    permissionOverwrites: Collection [Map] {
      '690379773847011368' => [PermissionOverwrites],
      '690388886437756938' => [PermissionOverwrites]
    },
    guild: Guild {
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      roles: [RoleManager],
      presences: [PresenceManager],
      voiceStates: [VoiceStateManager],
      deleted: false,
      available: true,
      id: '690379773847011368',
      shardID: 0,
      name: 'MKYC Recruiting',
      icon: null,
      splash: null,
      region: 'us-east',
      memberCount: 6,
      large: false,
      features: [],
      applicationID: null,
      afkTimeout: 300,
      afkChannelID: null,
      systemChannelID: '690379773847011371',
      embedEnabled: undefined,
      premiumTier: 0,
      premiumSubscriptionCount: 0,
      verificationLevel: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 0,
      joinedTimestamp: 1584675310004,
      defaultMessageNotifications: 'ALL',
      systemChannelFlags: [SystemChannelFlags],
      vanityURLCode: null,
      description: null,
      banner: null,
      rulesChannelID: null,
      publicUpdatesChannelID: null,
      ownerID: '485118363475902474',
      emojis: [GuildEmojiManager]
    }
  }
}
```

**Comment by SpaceEEC** [comment]
> `type: false,`

This here is causing that error.

I really do not see any chance for discord.js to ever assign anything to `Channel#type` outside of these two cases:
https://github.com/discordjs/discord.js/blob/215740157bb85837e0f2c4bc9a7ce373b4bf1eb1/src/structures/DMChannel.js#L19-L20


https://github.com/discordjs/discord.js/blob/215740157bb85837e0f2c4bc9a7ce373b4bf1eb1/src/structures/Channel.js#L15
https://github.com/discordjs/discord.js/blob/215740157bb85837e0f2c4bc9a7ce373b4bf1eb1/src/structures/Channel.js#L27
And neither are able to assign `false`.

---

I think this assignment is happening somewhere on your end.

Try looking through your code, you likely are accidentally assigning to `Channel#type` somewhere.

Since you seem to be using `==` I have a possible explanation:

One error I commonly see is assigning when actually intending to compare using "not equals":
`channel.type =! 'foo'` instead of `channel.type != 'foo'`
(This wouldn't be possible to happen if you used `===` and `!==`)

If you use eslint you also want to enable the [`no-cond-assign`](https://eslint.org/docs/rules/no-cond-assign) rule. It would catch that.
(If you are not, you might want to start using it to avoid such in the future.)

**Comment by Raptor2277** [comment]
> I think this assignment is happening somewhere on your end.
You're right.
```js
    appCategory = guild.channels.cache.find(e => e.type = "category" && e.name == "Applications");
    scoutingCategory = guild.channels.cache.find(e => e.type = "category" && e.name == "Scouting Logs");
```
