### ISSUE TITLE
channelUpdate.js - Error

### ISSUE THREAD

**Issue by CyberLinx** [discordjs/discord.js#3999]
**Please describe the problem you are having in as much detail as possible:**
I'm trying to update a channel, it updates, but i recive this error:
```js
/rbd/pnpm-volume/52240f0a-133e-45e2-a0b4-044d88301e29/node_modules/.registry.npmjs.org/discord.js/12.0.2/node_modules/discord.js/src/client/actions/ChannelUpdate.js:17
        for (const [id, message] of channel.messages.cache) newChannel.messages.cache.set(id, message);
                                                     ^
TypeError: Cannot read property 'cache' of undefined
    at ChannelUpdateAction.handle (/rbd/pnpm-volume/52240f0a-133e-45e2-a0b4-044d88301e29/node_modules/.registry.npmjs.org/discord.js/12.0.2/node_modules/discord.js/src/client/actions/ChannelUpdate.js:17:54)
    at Object.module.exports [as CHANNEL_UPDATE] (/rbd/pnpm-volume/52240f0a-133e-45e2-a0b4-044d88301e29/node_modules/.registry.npmjs.org/discord.js/12.0.2/node_modules/discord.js/src/client/websocket/handlers/CHANNEL_UPDATE.js:6:57)
    at WebSocketManager.handlePacket (/rbd/pnpm-volume/52240f0a-133e-45e2-a0b4-044d88301e29/node_modules/.registry.npmjs.org/discord.js/12.0.2/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/rbd/pnpm-volume/52240f0a-133e-45e2-a0b4-044d88301e29/node_modules/.registry.npmjs.org/discord.js/12.0.2/node_modules/discord.js/src/client/websocket/WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (/rbd/pnpm-volume/52240f0a-133e-45e2-a0b4-044d88301e29/node_modules/.registry.npmjs.org/discord.js/12.0.2/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/rbd/pnpm-volume/52240f0a-133e-45e2-a0b4-044d88301e29/node_modules/.registry.npmjs.org/ws/7.2.3/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:196:13)
    at Receiver.receiverOnMessage (/rbd/pnpm-volume/52240f0a-133e-45e2-a0b4-044d88301e29/node_modules/.registry.npmjs.org/ws/7.2.3/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (events.js:196:13)
    at Receiver.dataMessage (/rbd/pnpm-volume/52240f0a-133e-45e2-a0b4-044d88301e29/node_modules/.registry.npmjs.org/ws/7.2.3/node_modules/ws/lib/receiver.js:436:14)
```

**Include a reproducible code sample here, if possible:**

```js
message.channel.permissionOverwrites.get(message.mentions.members.first().id).delete();
```

**Further details:**

- discord.js version: 12.0.2
- Node.js version: 12.0.0
- Operating system: Ubuntu 16.04.6 LTS xenial
- Priority this issue should have – please be realistic and elaborate if possible:

- [] I have also tested the issue on latest master, commit hash:

**Comment by Monbrey** [comment]
**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by CyberLinx** [comment]
@Monbrey but this is a bug report

**Comment by SpaceEEC** [comment]
I can not reproduce this using the provided code.

---

Can you log the data provided by discord as well as the channel before the update?

Something like this should do:
```js
client.on('raw', packet => {
	if (packet.t === 'CHANNEL_UPDATE') {
		console.log(packet.d, client.channels.cache.get(packet.d.id));
	}
});
```

**Comment by CyberLinx** [comment]
@SpaceEEC here it is
```js
{
  type: 4,
  position: 8,
  permission_overwrites: [
    {
      type: 'member',
      id: '682572949219180547',
      deny: 0,
      allow: 66322000
    },
    { type: 'role', id: '689881325121175556', deny: 1024, allow: 0 },
    {
      type: 'member',
      id: '682580009767927843',
      deny: 29503505,
      allow: 36818496
    }
  ],
  parent_id: null,
  nsfw: false,
  name: "Cyber's room",
  id: '692681020121808947',
  guild_id: '689881325121175556'
} CategoryChannel {
  type: 'category',
  deleted: false,
  id: '692681020121808947',
  name: "Cyber's room",
  rawPosition: 8,
  parentID: null,
  permissionOverwrites: Collection [Map] {
    '682572949219180547' => PermissionOverwrites {
      id: '682572949219180547',
      type: 'member',
      deny: [Permissions],
      allow: [Permissions]
    },
    '689881325121175556' => PermissionOverwrites {
      id: '689881325121175556',
      type: 'role',
      deny: [Permissions],
      allow: [Permissions]
    }
  },
  guild: Guild {
    members: GuildMemberManager {
      cacheType: [Function: Collection],
      cache: [Collection],
      guild: [Circular]
    },
    channels: GuildChannelManager {
      cacheType: [Function: Collection],
      cache: [Collection],
      guild: [Circular]
    },
    roles: RoleManager {
      cacheType: [Function: Collection],
      cache: [Collection],
      guild: [Circular]
    },
    presences: PresenceManager {
      cacheType: [Function: Collection],
      cache: [Collection]
    },
    voiceStates: VoiceStateManager {
      cacheType: [Function: Collection],
      cache: Collection [Map] {},
      guild: [Circular]
    },
    deleted: false,
    available: true,
    id: '689881325121175556',
    shardID: 0,
    name: 'ROOM-BOT',
    icon: null,
    splash: null,
    region: 'europe',
    memberCount: 2,
    large: false,
    features: [],
    applicationID: null,
    afkTimeout: 300,
    afkChannelID: null,
    systemChannelID: '689881578843013204',
    embedEnabled: undefined,
    premiumTier: 0,
    premiumSubscriptionCount: 0,
    verificationLevel: 'NONE',
    explicitContentFilter: 'DISABLED',
    mfaLevel: 0,
    joinedTimestamp: 1584658981715,
    defaultMessageNotifications: 'ALL',
    systemChannelFlags: SystemChannelFlags { bitfield: 0 },
    vanityURLCode: null,
    description: null,
    banner: null,
    rulesChannelID: null,
    publicUpdatesChannelID: null,
    ownerID: '682572949219180547',
    emojis: GuildEmojiManager {
      cacheType: [Function: Collection],
      cache: Collection [Map] {},
      guild: [Circular]
    }
  }
}
{
  type: 0,
  topic: null,
  rate_limit_per_user: 0,
  position: 13,
  permission_overwrites: [
    {
      type: 'member',
      id: '682572949219180547',
      deny: 0,
      allow: 66322000
    },
    { type: 'role', id: '689881325121175556', deny: 1024, allow: 0 },
    {
      type: 'member',
      id: '682580009767927843',
      deny: 29503505,
      allow: 36818496
    }
  ],
  parent_id: '692681020121808947',
  nsfw: false,
  name: 'cyber',
  last_message_id: '692681101994623068',
  id: '692681021446946897',
  guild_id: '689881325121175556'
} TextChannel {
  type: 'category',
  deleted: false,
  id: '692681021446946897',
  name: 'cyber',
  rawPosition: 13,
  parentID: '692681020121808947',
  permissionOverwrites: Collection [Map] {
    '682572949219180547' => PermissionOverwrites {
      id: '682572949219180547',
      type: 'member',
      deny: [Permissions],
      allow: [Permissions]
    },
    '689881325121175556' => PermissionOverwrites {
      id: '689881325121175556',
      type: 'role',
      deny: [Permissions],
      allow: [Permissions]
    }
  },
  topic: null,
  nsfw: false,
  lastMessageID: '692681101994623068',
  rateLimitPerUser: 0,
  lastPinTimestamp: null,
  guild: Guild {
    members: GuildMemberManager {
      cacheType: [Function: Collection],
      cache: [Collection],
      guild: [Circular]
    },
    channels: GuildChannelManager {
      cacheType: [Function: Collection],
      cache: [Collection],
      guild: [Circular]
    },
    roles: RoleManager {
      cacheType: [Function: Collection],
      cache: [Collection],
      guild: [Circular]
    },
    presences: PresenceManager {
      cacheType: [Function: Collection],
      cache: [Collection]
    },
    voiceStates: VoiceStateManager {
      cacheType: [Function: Collection],
      cache: Collection [Map] {},
      guild: [Circular]
    },
    deleted: false,
    available: true,
    id: '689881325121175556',
    shardID: 0,
    name: 'ROOM-BOT',
    icon: null,
    splash: null,
    region: 'europe',
    memberCount: 2,
    large: false,
    features: [],
    applicationID: null,
    afkTimeout: 300,
    afkChannelID: null,
    systemChannelID: '689881578843013204',
    embedEnabled: undefined,
    premiumTier: 0,
    premiumSubscriptionCount: 0,
    verificationLevel: 'NONE',
    explicitContentFilter: 'DISABLED',
    mfaLevel: 0,
    joinedTimestamp: 1584658981715,
    defaultMessageNotifications: 'ALL',
    systemChannelFlags: SystemChannelFlags { bitfield: 0 },
    vanityURLCode: null,
    description: null,
    banner: null,
    rulesChannelID: null,
    publicUpdatesChannelID: null,
    ownerID: '682572949219180547',
    emojis: GuildEmojiManager {
      cacheType: [Function: Collection],
      cache: Collection [Map] {},
      guild: [Circular]
    }
  },
  messages: MessageManager {
    cacheType: [Function: LimitedCollection],
    cache: LimitedCollection [Map] {
      '692681079261364234' => [Message],
      '692681101767868457' => [Message],
      '692681101994623068' => [Message],
      maxSize: 200
    },
    channel: [Circular]
  },
  _typing: Map {}
}
{
  user_limit: 0,
  type: 2,
  position: 0,
  permission_overwrites: [
    {
      type: 'member',
      id: '682572949219180547',
      deny: 0,
      allow: 66322000
    },
    { type: 'role', id: '689881325121175556', deny: 1024, allow: 0 },
    {
      type: 'member',
      id: '682580009767927843',
      deny: 29503505,
      allow: 36818496
    }
  ],
  parent_id: '692681020121808947',
  nsfw: false,
  name: 'Cyber',
  id: '692681022449385522',
  guild_id: '689881325121175556',
  bitrate: 64000
} VoiceChannel {
  type: 'category',
  deleted: false,
  id: '692681022449385522',
  name: 'Cyber',
  rawPosition: 0,
  parentID: '692681020121808947',
  permissionOverwrites: Collection [Map] {
    '682572949219180547' => PermissionOverwrites {
      id: '682572949219180547',
      type: 'member',
      deny: [Permissions],
      allow: [Permissions]
    },
    '689881325121175556' => PermissionOverwrites {
      id: '689881325121175556',
      type: 'role',
      deny: [Permissions],
      allow: [Permissions]
    }
  },
  bitrate: 64000,
  userLimit: 0,
  guild: Guild {
    members: GuildMemberManager {
      cacheType: [Function: Collection],
      cache: [Collection],
      guild: [Circular]
    },
    channels: GuildChannelManager {
      cacheType: [Function: Collection],
      cache: [Collection],
      guild: [Circular]
    },
    roles: RoleManager {
      cacheType: [Function: Collection],
      cache: [Collection],
      guild: [Circular]
    },
    presences: PresenceManager {
      cacheType: [Function: Collection],
      cache: [Collection]
    },
    voiceStates: VoiceStateManager {
      cacheType: [Function: Collection],
      cache: Collection [Map] {},
      guild: [Circular]
    },
    deleted: false,
    available: true,
    id: '689881325121175556',
    shardID: 0,
    name: 'ROOM-BOT',
    icon: null,
    splash: null,
    region: 'europe',
    memberCount: 2,
    large: false,
    features: [],
    applicationID: null,
    afkTimeout: 300,
    afkChannelID: null,
    systemChannelID: '689881578843013204',
    embedEnabled: undefined,
    premiumTier: 0,
    premiumSubscriptionCount: 0,
    verificationLevel: 'NONE',
    explicitContentFilter: 'DISABLED',
    mfaLevel: 0,
    joinedTimestamp: 1584658981715,
    defaultMessageNotifications: 'ALL',
    systemChannelFlags: SystemChannelFlags { bitfield: 0 },
    vanityURLCode: null,
    description: null,
    banner: null,
    rulesChannelID: null,
    publicUpdatesChannelID: null,
    ownerID: '682572949219180547',
    emojis: GuildEmojiManager {
      cacheType: [Function: Collection],
      cache: Collection [Map] {},
      guild: [Circular]
    }
  }
}
```

**Comment by SpaceEEC** [comment]
It seems like you are overwriting the `type` property of channels somewhere on your end:
```js
VoiceChannel {
  type: 'category',
  // ...
}
```
```js
TextChannel {
  type: 'category',
  // ...
}
```

Look through your code, you probably have a single `=` instead of (hopfully) three `===`.

See also: https://github.com/discordjs/discord.js/issues/3981#issuecomment-602267520

**Comment by CyberLinx** [comment]
@SpaceEEC worked, thanks
