### ISSUE TITLE
Error when running discord.js

### ISSUE THREAD

**Issue by luke110206** [discordjs/discord.js#4100]
I am attempting to run my index.js and I get this
`/rbd/pnpm-volume/2a0eb8aa-b246-4301-bb19-4b8c9c1e9f2f/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/client/Client.js:41
    } catch {
            ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rbd/pnpm-volume/2a0eb8aa-b246-4301-bb19-4b8c9c1e9f2f/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/index.js:8:11)`

**Comment by ItsPapaia** [comment]
The issue tracker is just for bug reports, if you need support, head to the [support server](https://discord.gg/bRCvFy9).

In short: update your Node version, discord.js 12 requires Node 12+.

**Comment by ItsPapaia** [comment]
Forgot to mention, please don't ignore the issue template, it's there for a reason.
