### ISSUE TITLE
Old GLIBC_2.29 dependency crashes Opus

### ISSUE THREAD

**Issue by isolin** [discordjs/discord.js#4148]
I am not able to play music, since after calling `play` on a voice channel I get:

```
(node:12145) UnhandledPromiseRejectionWarning: Error: Could not find an Opus module! Please install @discordjs/opus, node-opus, or opusscript.
    at new OpusStream (/home/user/DiscordBot/node_modules/prism-media/src/opus/Opus.js:42:13)
    at new Encoder (/home/user/DiscordBot/node_modules/prism-media/src/opus/Opus.js:130:5)
    at AudioPlayer.playPCMStream (/home/user/DiscordBot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:58:34)
    at AudioPlayer.playUnknown (/home/user/DiscordBot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:53:17)
    at VoiceConnection.play (/home/user/DiscordBot/node_modules/discord.js/src/client/voice/util/PlayInterface.js:71:28)
    at play (/home/user/DiscordBot/index.js:10:29)
    at targetChannel.join.then.connection (/home/user/DiscordBot/index.js:39:61)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:12145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I examined that closer by starting `node` and calling `require("@discordjs/opus")` with the following result:
```
Error: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/user/DiscordBot/node_modules/@discordjs/opus/prebuild/node-v67-linux-x64-glibc/opus.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```

I am at Ubuntu Focal Fossa, having `libc6` installed... however it's version 2.31. This is quite awkward. How to deal with that / shouldn't it be fixed?

**Comment by iCrawl** [comment]
Guess I'll have to build the module against a higher libc6 version
