### ISSUE TITLE
MessageEmbed() Is not a constructor

### ISSUE THREAD

**Issue by boxconsole** [discordjs/discord.js#4282]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
const embed = new Discord.MessageEmbed()
                ^
TypeError: Discord.MessageEmbed is not a constructor
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 10.15.3
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible: Middle

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
There's some other issues going on here, you can't even use discord.js v12 with nodejs v10.

Chances are you aren't using v12

**Comment by Antimatterr** [comment]
> There's some other issues going on here, you can't even use discord.js v12 with nodejs v10.
> 
> Chances are you aren't using v12

i am using v12 but still it shows that error

**Comment by Alkosik** [comment]
I've got the exact same problem with Node: 15.10.0 and Discord.js: 12.5.1 on Windows

`C:\Users\Alkos\Desktop\fixin\hau2\commands\poll.js:11
                    const PollEmbed = new Discord.MessageEmbed()
                                      ^

TypeError: Discord.MessageEmbed is not a constructor
    at C:\Users\Alkos\Desktop\fixin\hau2\commands\poll.js:11:25
    at Object.execute (C:\Users\Alkos\Desktop\fixin\hau2\commands\poll.js:38:11)
    at Client.<anonymous> (C:\Users\Alkos\Desktop\fixin\hau2\index.js:235:21)
    at Client.emit (node:events:390:22)
    at MessageCreateAction.handle (C:\Users\Alkos\Desktop\fixin\hau2\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Alkos\Desktop\fixin\hau2\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Alkos\Desktop\fixin\hau2\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\Alkos\Desktop\fixin\hau2\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Alkos\Desktop\fixin\hau2\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Alkos\Desktop\fixin\hau2\node_modules\ws\lib\event-target.js:132:16)`

**Comment by advaith1** [comment]
Have you tried uninstalling and reinstalling discord.js?

**Comment by Alkosik** [comment]
> Have you tried uninstalling and reinstalling discord.js?

Well I updated node to 15 because of this, but I just fixed it by requiring Discord directly in the Poll.js instead of passing it from index.js

**Comment by Nedinator** [comment]
> 
> 
> Have you tried uninstalling and reinstalling discord.js?

Can confirm for one of the members of server I'm in this worked for them.

`npm uninstall -S discord.js` and then `npm i discord.js --save` was ran.
