### ISSUE TITLE
node_modules/discord.js/src/util/Util.js:584 SyntaxError: Invalid regular expression flags

### ISSUE THREAD

**Issue by alx365** [discordjs/discord.js#4298]
So i want to run my discord bot on my rasberry pi,  but when ever i start the bot, it crashes with the following error:
```js
/path/to/the/project/node_modules/discord.js/src/util/Util.js:584
      str = str.replace(/@([^<>@ ]*)/gmsu, (match, target) => {
                        ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Github/moustache-bot/node_modules/discord.js/src/index.js:3:14)
```

Since this is not a issue with my code i will not be linking my code here,

Cheers

**Comment by tipakA** [comment]
Have you considered filling out the issue template you completely ignored? it would provide actually helpful informations, like node version.

**Comment by Monbrey** [comment]
> like node version.

Exactly this. Discord.js requires Node 12 or higher.
