### ISSUE TITLE
TypeError: Cannot read property 'members' of null

### ISSUE THREAD

**Issue by BeamKunGzMARK** [discordjs/discord.js#4322]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have also tested the issue on latest master, commit hash:

const membersfetch = message.guild.members.fetch();
membersfetch.forEach((member) => member.send(Embed))

--- In console it say ---
reason: TypeError: Cannot read property 'members' of null
    at Client.<anonymous> (C:\Users\nawap\OneDrive\Desktop\Discord\bot all\nirtogiven\bot.js:65:38)
    at Client.emit (events.js:311:20)
    at MessageCreateAction.handle (C:\Users\nawap\OneDrive\Desktop\Discord\bot all\nirtogiven\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\nawap\OneDrive\Desktop\Discord\bot all\nirtogiven\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\nawap\OneDrive\Desktop\Discord\bot all\nirtogiven\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\nawap\OneDrive\Desktop\Discord\bot all\nirtogiven\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (C:\Users\nawap\OneDrive\Desktop\Discord\bot all\nirtogiven\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\nawap\OneDrive\Desktop\Discord\bot all\nirtogiven\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (C:\Users\nawap\OneDrive\Desktop\Discord\bot all\nirtogiven\node_modules\ws\lib\websocket.js:800:20)

**Comment by SketchyLxve** [comment]
This is not an issue with the library. `Message#guild` is null when the channel the message was received from is a DMChannel.
Please use the [discord server](https://discord.gg/bRCvFy9) for support, the issue tracker is not for such.
