### ISSUE TITLE
Error on MessageCollector when user sending message

### ISSUE THREAD

**Issue by zechaos031** [discordjs/discord.js#4336]
**Please describe the problem you are having in as much detail as possible:**
I trying for make a capchat system when a user join a guild, I make a collector to retrieve a message but when sending it I get an error.

**Include a reproducible code sample here, if possible:**

```js
//channels is equals to one channel

let collector = newMember.guild.channels.cache.get(channels.id).createMessageCollector(newMember.id,{time : 60000})
                        collector.on("collect", message =>{
                            console.log(message)
                            if (message.content === code) {
                                newMember.roles.remove(capchatRole).then(() => {
                                    message.delete()
                                    newMember.roles.add(roles)
                                })
                            }
                        })
```

The error
```
C:\Users\user\Desktop\NoNameBot\node_modules\discord.js\src\structures\interfaces\Collector.js:91
    if (collect && this.filter(...args, this.collected)) {
                                             ^

TypeError: Function.prototype.apply was called on 441345567327780875, which is a string and not a function
    at MessageCollector.handleCollect (C:\Users\user\Desktop\NoNameBot\node_modules\discord.js\src\structures\interfaces\Collector.js:91:46)
    at StructureBot.emit (events.js:228:7)
    at MessageCreateAction.handle (C:\Users\user\Desktop\NoNameBot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\user\Desktop\NoNameBot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\user\Desktop\NoNameBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\user\Desktop\NoNameBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (C:\Users\user\Desktop\NoNameBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\user\Desktop\NoNameBot\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:223:5)
    at Receiver.receiverOnMessage (C:\Users\user\Desktop\NoNameBot\node_modules\ws\lib\websocket.js:800:20)
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: 12.14.1
- Operating system: Windows 10
- Priority this issue should have – 3/10

**Comment by SpaceEEC** [comment]
[`TextBasedChannel#createMessageCollector`](https://discord.js.org/#/docs/main/stable/class/TextBasedChannel?scrollTo=createMessageCollector) expects as its first parameter a [`CollectorFilter`](https://discord.js.org/#/docs/main/stable/typedef/CollectorFilter).
You are passing it a, I assume, [`GuildMember#id`](https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=id), which is not compatible with the aforementioned typedef.

---

If you have further questions, please ask them in the [Discord server](https://discord.gg/bRCvFy9) instead, as this issue tracker is only for bug reports and enhancement suggestions.
