### ISSUE TITLE
I cant create embed

### ISSUE THREAD

**Issue by bagou4502** [discordjs/discord.js#4625]
**Please describe the problem you are having in as much detail as possible:**
I cant create embed

**Include a reproducible code sample here, if possible:**

The error
```js
/srv/daemon-data/f1e653f3-b776-4e0e-ad4f-74e7f1ad0ff7/bot1/node_modules/discord.js/src/structures/MessageEmbed.js:12
    Object.defineProperty(this, 'client', { value: message.client });
                                                           ^

TypeError: Cannot read property 'client' of undefined
    at new MessageEmbed (/srv/daemon-data/f1e653f3-b776-4e0e-ad4f-74e7f1ad0ff7/bot1/node_modules/discord.js/src/structures/MessageEmbed.js:12:60)
    at Client.client.on (/srv/daemon-data/f1e653f3-b776-4e0e-ad4f-74e7f1ad0ff7/bot1/index.js:28:16)
    at Client.emit (events.js:203:15)
    at WebSocketManager._emitReady (/srv/daemon-data/f1e653f3-b776-4e0e-ad4f-74e7f1ad0ff7/bot1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:325:17)    at WebSocketManager.checkIfReady (/srv/daemon-data/f1e653f3-b776-4e0e-ad4f-74e7f1ad0ff7/bot1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:14)
    at GuildCreateHandler.handle (/srv/daemon-data/f1e653f3-b776-4e0e-ad4f-74e7f1ad0ff7/bot1/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/srv/daemon-data/f1e653f3-b776-4e0e-ad4f-74e7f1ad0ff7/bot1/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (/srv/daemon-data/f1e653f3-b776-4e0e-ad4f-74e7f1ad0ff7/bot1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:273:31)
    at WebSocket.onMessage (/srv/daemon-data/f1e653f3-b776-4e0e-ad4f-74e7f1ad0ff7/bot1/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:442:14)
    at WebSocket.emit (events.js:198:13)
```
The code
```js
const embed = new Discord.MessageEmbed()
.setColor("#FE9803")
.setDescription("test")
```

**Further details:**

- discord.js version:  12.2.0
- Node.js version: 12.18.2
- Operating system: Linux (Ubuntu 18.04 LTS) and Windows 10
- Priority this issue should have – please be realistic and elaborate if possible:
Medium

**Comment by bagou4502** [comment]
the MessageEmbed ligne 12 : Object.defineProperty(this, 'client', { value: message.client });

**Comment by NotSugden** [comment]
are you sure you're using version 12?, check using `npm ls discord.js`

**Comment by bagou4502** [comment]
yes is 
12.2.0

**Comment by NotSugden** [comment]
if you check https://github.com/discordjs/discord.js/blob/da39e858a1d4bd23a2af2e693024512426615557/src/structures/MessageEmbed.js#L13 it seems to be v11 code you have referenced, perhaps try re-installing discord.js, `npm uninstall discord.js` & `npm install discord.js`

**Comment by bagou4502** [comment]
ITS WORK thank
