### ISSUE TITLE
Event Get Triggered On Client.destory()

### ISSUE THREAD

**Issue by isuckatprogram** [discordjs/discord.js#4725]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
So I have a bot and I create a command called ``restart`` which does ``client.destory()`` then ``client.login(token)`` and the websocket connection is reset but when it does that the event "shardDisconnected" is triggered, but thats not the issue here. The issue is that the event has a argument but when ``client.destory()`` is called and the "shardDisconnected" event is triggered the argument returns as undefined causing my bot the crash. Here's my terminal:

```bash
C:\Users\oluse\Desktop\Null\src\index.js:447
        e.setDescription(`Shard ${id} has disconnected.`)
                                  ^

ReferenceError: id is not defined
    at Client.<anonymous> (C:\Users\oluse\Desktop\Null\src\index.js:447:35)
    at Client.emit (events.js:315:20)
    at WebSocketShard.<anonymous> (C:\Users\oluse\Desktop\Null\node_modules\discord.js\src\client\websocket\WebSocketManager.js:208:23)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.onClose (C:\Users\oluse\Desktop\Null\node_modules\discord.js\src\client\websocket\WebSocketShard.js:364:10)
    at WebSocket.onClose (C:\Users\oluse\Desktop\Null\node_modules\ws\lib\event-target.js:129:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (C:\Users\oluse\Desktop\Null\node_modules\ws\lib\websocket.js:191:10)
    at TLSSocket.socketOnClose (C:\Users\oluse\Desktop\Null\node_modules\ws\lib\websocket.js:858:15)
```

**Further details:**

- discord.js version: 12.2.0
- Node.js version: v12.18.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible:
This shouldn't really have that much priority but it should be at least priority 2.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ No ] I have also tested the issue on latest master, commit hash:

**Comment by isuckatprogram** [comment]
turned out this was an error in my code not discord. me dumb
