### ISSUE TITLE
Ban function that does not work :(

### ISSUE THREAD

**Issue by Aquaran** [discordjs/discord.js#4740]
Hi, i have a problem with the ban command, the user is not ban and it shows me this error :

```js
0|main     | }
0|main     | Response: Internal Server Error
0|main     |     at RequestHandler.execute (F:\Discord_Bot_V12\node_modules\discord.js\src\rest\RequestHandler.js:158:11)
0|main     |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
0|main     |   code: 500,
0|main     |   method: 'put',
0|main     |   path: '/guilds/747171378792366290/bans/747204861208297535'
0|main     | }
0|main     | Response: Internal Server Error
0|main     |     at RequestHandler.execute (F:\Discord_Bot_V12\node_modules\discord.js\src\rest\RequestHandler.js:158:11)
0|main     |     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
0|main     |   code: 500,
0|main     |   method: 'put',
0|main     |   path: '/guilds/747171378792366290/bans/747502842390249507'
0|main     | }
```
Here is the code of the ban command :

```js
const { MessageEmbed } = require("discord.js");
const { MESSAGES } = require("../../util/constants");

module.exports.run = (client, message, args) => {
    let user = message.mentions.users.first();
    let reason = (args.splice(1).join(' ') || 'Aucune raison spécifiée.');
    user ? message.guild.member(user).ban(reason) : message.channel.send("L'utilisateur mentionné n'existe pas.");

    const embed = new MessageEmbed()
      .setAuthor(`${user.tag} (${user.id})`, user.avatarURL())
      .setColor("#dc143c")
      .setDescription(`**Action** : ban\n**Raison** : ${reason}`)
      .setTimestamp()
      .setFooter(message.author.username, message.author.avatarURL());

    message.channel.send(embed);
};

module.exports.help = MESSAGES.COMMANDS.MODERATION.BAN;
```

Thank you advance for your help ! (I think it's a bug after i don't know ?)

**Comment by anandre** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If
    you have a question, please ask it in the [Discord
    server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.

**Comment by Aquaran** [comment]
Oops, I'm sorry i should have looked that it was not a support, thank you anyway for your answer.
