### ISSUE TITLE
Unexpected token in the Client class

### ISSUE THREAD

**Issue by ObertoIsOBS** [discordjs/discord.js#4809]
**Please describe the problem you are having in as much detail as possible:**
After much procrastination, I have finally decided to update my code from V11 to V12. Once I made all the nessacary updates to my code, I installed the latest discord.js version (12.3.1) and ran my bot. I am confident none of my code is causing this issue, although a system config or npm package error could be the cause.

**Include a reproducible code sample here, if possible:**

The error:
```
SyntaxError: Unexpected token {
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:616:28)
 at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)                       
at require (internal/module.js:11:18)
/root/SoundBackup/node_modules/discord.js/src/client/Client.js:41 
      } catch  {
                  ^
```

**Further details:**
The code works just fine on V11. All updates have been made properly to the code. The issue appears to happen on the stable build as well.

- discord.js version: 12.3.1
- Node.js version: 8.10.0
- Operating system: Ubuntu 18.04
- Priority this issue should have – please be realistic and elaborate if possible: High. Assuming others are having this issue, discord.js is unusable while the error still exists.

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [x] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
Discord.js v12 requires at least Node.js Version 12
