### ISSUE TITLE
Error: Cannot find module './AsyncQueue'

### ISSUE THREAD

**Issue by williamd5** [discordjs/discord.js#5000]
**Please describe the problem you are having in as much detail as possible:**
Unable to start NodeJS server; missing AsyncQueue module inside DiscordJS
**Include a reproducible code sample here, if possible:**

```sh
root@server:~/gsrv-bot# node .
[23:56:44] Booting bot...
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './AsyncQueue'
Require stack:
- /root/gsrv-bot/node_modules/discord.js/src/rest/RequestHandler.js
- /root/gsrv-bot/node_modules/discord.js/src/rest/RESTManager.js
- /root/gsrv-bot/node_modules/discord.js/src/client/BaseClient.js
- /root/gsrv-bot/node_modules/discord.js/src/index.js
- /root/gsrv-bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/gsrv-bot/node_modules/discord.js/src/rest/Reque                                             stHandler.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/gsrv-bot/node_modules/discord.js/src/rest/RequestHandler.js',
    '/root/gsrv-bot/node_modules/discord.js/src/rest/RESTManager.js',
    '/root/gsrv-bot/node_modules/discord.js/src/client/BaseClient.js',
    '/root/gsrv-bot/node_modules/discord.js/src/index.js',
    '/root/gsrv-bot/index.js'
  ]
}

```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 15.1.0 and 10.23.0
- Operating system: Ubuntu 18.04.1 LTS

**Comment by monbrey** [comment]
`AsyncQueue` is defined inside discord.js: https://github.com/discordjs/discord.js/blob/master/src/rest/AsyncQueue.js

I'd suggest you try reinstalling discord.js, or removing any extra build steps (eg babel, webpack) that could potentially break this.

**Comment by williamd5** [comment]
Thanks, I added the file manually. I thought it was some dependency that my system had refused to install for some reason.
