### ISSUE TITLE
Bug when changing channel permission

### ISSUE THREAD

**Issue by SnaiilGaming** [discordjs/discord.js#5029]
**Problem:** When I want to change a permission of a channel created with a command. The permission is changed, but the bot crashes and an error appears. The error comes directly from discord.js module nodes.

**Code:**

```js
if (message.content.toLowerCase() == '!close') {
        message.delete({ timeout: 5000 })
        if (!message.channel.name.includes("ticket")) {
            if (message.author.bot) return;
            message.channel.send("Vous ne pouvez pas faire ça ici !")
                .then(message => {
                    message.delete({ timeout: 5000 })
                })
                .catch(console.error)
        }
        else {
            message.channel.overwritePermissions([
                {
                   id: message.author.id,
                   deny: ['VIEW_CHANNEL'],
                },
              ], 'Needed to change permissions');
        }
    }
```

**Error:**
```
Uncaught TypeError: channel.type.toUpperCase is not a function
node_modules/discord.js/src/client/actions/ChannelUpdate.js:15
Debugger attached.
Waiting for the debugger to disconnect...
c:\Users\Snaii\Desktop\Développement\Discord\Ocesnia\node_modules\discord.js\src\client\actions\ChannelUpdate.js:15
      if (ChannelTypes[channel.type.toUpperCase()] !== data.type) {
                                    ^

TypeError: channel.type.toUpperCase is not a function
    at ChannelUpdateAction.handle (c:\Users\Snaii\Desktop\Développement\Discord\Ocesnia\node_modules\discord.js\src\client\actions\ChannelUpdate.js:15:37)
    at Object.module.exports [as CHANNEL_UPDATE] (c:\Users\Snaii\Desktop\Développement\Discord\Ocesnia\node_modules\discord.js\src\client\websocket\handlers\CHANNEL_UPDATE.js:6:57)
    at WebSocketManager.handlePacket (c:\Users\Snaii\Desktop\Développement\Discord\Ocesnia\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (c:\Users\Snaii\Desktop\Développement\Discord\Ocesnia\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (c:\Users\Snaii\Desktop\Développement\Discord\Ocesnia\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (c:\Users\Snaii\Desktop\Développement\Discord\Ocesnia\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (c:\Users\Snaii\Desktop\Développement\Discord\Ocesnia\node_modules\ws\lib\websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (c:\Users\Snaii\Desktop\Développement\Discord\Ocesnia\node_modules\ws\lib\receiver.js:437:14)
Process exited with code 1
```

**Further details:**

- discord.js version: 12.4.1
- Node.js version: 14.15
- Operating system: Windows 10
- Priority : High

**Comment by monbrey** [comment]
It sure would be helpful of you to also include the error that "comes directly from discord.js module nodes"

**Comment by almostSouji** [comment]
Can not reproduce this on `12.5.1` - earlier versions are not supported.
Either it has been fixed or there are other circumstances not detailed here which cause the issue. Please try to plug your code sample into a fresh bot and remove all unnecessary code. If you can still reproduce please provide the full minimal, reproducible code sample.

Should you be able to reproduce the issue still feel free to re-open.

--- 

Please provide a minimal reproducible code sample so we can attempt to reproduce and verify your issue. This means isolating the erroneous behavior to a fresh bot, or stripping away functionality until you can be sure the code is minimal. Also, include a manual with the steps you take interacting with the code in question which results in the behavior you outlined.

Please try to reproduce the issue yourself on a fresh bot. If you can't reproduce it, it's very likely that we can't either and the code sample in question is not enough.

Boilerplate: https://discord.js.org/#/docs/main/stable/examples/ping
Minimal Reproducible sample: https://stackoverflow.com/help/minimal-reproducible-example
