### ISSUE TITLE
Pkg fails to package discord.js properly

### ISSUE THREAD

**Issue by jyte** [discordjs/discord.js#5053]
Hello,

I like to bundle my nodejs  projects into single binary for people with [pkg](https://github.com/vercel/pkg) 
however, the resulting binary is not working.

Create a file `bug.js` as follow
```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
    console.log(`Logged in as ${client.user.tag}!`);
});
client.login(/* my token */);
```

```
npm init
npm i --save-dev pkg
npm i --save discord.js
npx pkg bug.js
```
last command will generate 3 binary file for windows/osx/linux

And here is what happens when i run node, and the generated build by PKG

```
node bug.js
Logged in as mybot#xxx!
```
```
./bug-linux
(node:22882) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tag' of null
    at Client.<anonymous> (/snapshot/bot/bug.js)
    at Client.emit (events.js:315:20)
    at WebSocketManager.triggerClientReady (/snapshot/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (/snapshot/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (/snapshot/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (/snapshot/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (/snapshot/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (/snapshot/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/snapshot/bot/node_modules/ws/lib/event-target.js:132:16)
(node:22882) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22882) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

- discord.js version: ^12.4.1
- Node.js version: 12.x
- Operating system: Ubuntu 20.10

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by jyte** [comment]
apparently there are options in pkg to manage dynamic imports... found my solution [here](https://github.com/vercel/pkg/issues/910) just in case

**Comment by BjarkeM** [comment]
> apparently there are options in pkg to manage dynamic imports... found my solution [here](https://github.com/vercel/pkg/issues/910) just in case

What imports did you have to include for this to be fixed?
