### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by TheDaekLord1989** [discordjs/discord.js#5061]
**Please describe the problem you are having in as much detail as possible:**
I am making a discord BOT using discord.js and i get a error when i test my BOT. All of my functions works fine but it keep gives my error
Here is the error:
```
(node:12700) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
    at module.exports (C:\Users\cutelemon\Desktop\BOT\events\guild\message.js:14:57)
    at Client.<anonymous> (C:\Users\cutelemon\Desktop\BOT\index.js:32:36)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\cutelemon\Desktop\BOT\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\cutelemon\Desktop\BOT\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\cutelemon\Desktop\BOT\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at Immediate.<anonymous> (C:\Users\cutelemon\Desktop\BOT\node_modules\discord.js\src\client\websocket\WebSocketManager.js:379:14)
    at processImmediate (internal/timers.js:461:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12700) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
    at module.exports (C:\Users\cutelemon\Desktop\BOT\events\guild\message.js:14:57)
    at Client.<anonymous> (C:\Users\cutelemon\Desktop\BOT\index.js:32:36)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\cutelemon\Desktop\BOT\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\cutelemon\Desktop\BOT\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\cutelemon\Desktop\BOT\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\cutelemon\Desktop\BOT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\cutelemon\Desktop\BOT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\cutelemon\Desktop\BOT\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\cutelemon\Desktop\BOT\node_modules\ws\lib\websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\cutelemon\Desktop\BOT\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (C:\Users\cutelemon\Desktop\BOT\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (C:\Users\cutelemon\Desktop\BOT\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (C:\Users\cutelemon\Desktop\BOT\node_modules\ws\lib\receiver.js:78:10)
```

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
const Timeout = new Set();
const { MessageEmbed, message, Client } = require("discord.js");
const { prefix } = require("../../config.json");
const ms = require("ms");
const db = require("../../db");
const custom = require("../../models/custom");
/**
 * @param {Client} bot
 * @param {Message} message
 */
module.exports = async (bot, message) => {
  message.channel.messages.fetch();
  if (message.author.bot) return;
  let newPrefix = (await db.get(`Prefix_${message.guild.id}`))
    ? await db.get(`Prefix_${message.guild.id}`)
    : prefix;
  if (!message.content.toLowerCase().startsWith(newPrefix)) return;
  if (!message.member)
    message.member = await message.guild.fetchMember(message);

  if (!message.guild) return;
  const args = message.content.slice(newPrefix.length).trim().split(/ +/g);
  const cmd = args.shift().toLowerCase();

  if (cmd.length === 0) return;

  let command = bot.commands.get(cmd);
  if (!command) command = bot.commands.get(bot.aliases.get(cmd));

  if (command) {
    if (command.timeout) {
      if (Timeout.has(`${message.author.id}${command.name}`)) {
        return message.reply(
          `You can only use this command every ${ms(command.timeout)}!`
        );
      } else {
        command.run(bot, message, args);
        Timeout.add(`${message.author.id}${command.name}`);
        setTimeout(() => {
          Timeout.delete(`${message.author.id}${command.name}`);
        }, command.timeout);
      }
    } else {
      command.run(bot, message, args);
    }
  } else {
    custom.findOne(
      { Guild: message.guild.id, Command: cmd },
      async (err, data) => {
        if (err) throw err;
        if (data) return message.channel.send(data.Content);
        else return;
      }
    );
  }
};
```

**Further details:**

- discord.js version: 12.5.1
- Node.js version: 14.15.1
- Operating system: Windows 10 Pro
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**
- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by zaida04** [comment]
```js
let newPrefix = (await db.get(`Prefix_${message.guild.id}`)) ? await db.get(`Prefix_${message.guild.id}`)
```
This line is most likely causing you the issue. A possibility here is that the command is being done in DMs or another context in which a guild doesn't exist.

If you need help with discord.js installation or usage, please go to the discord.js Discord server instead:
https://discord.gg/bRCvFy9
This issue tracker is only for bug reports and enhancement suggestions. You won't receive any basic help here.

**Comment by TheDaekLord1989** [comment]
Hi zaida04, 
      Thank you for helping me solve the isseue.
      The isseue was fixed after I cleared all the data in the database,thank you.
