### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by NekoYasui** [discordjs/discord.js#5141]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
/home/runner/Nakajima/node_modules/discord.js/src/client/voice/VoiceConnection.js:171
    return this.channel.guild.me?.voice ?? null;
                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/Nakajima/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[nodemon] app crashed - waiting for file changes before starting...
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
https://github.com/discordjs/discord.js/issues
