### ISSUE TITLE
'fn' is not a function at Map.find()

### ISSUE THREAD

**Issue by xdorxble** [discordjs/discord.js#5181]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
// if (fn(val, key, this))
                ^

TypeError: fn is not a function
    at Map.find (E:\Nanashi\NanashiStable\node_modules\@discordjs\collection\dist\index.js:161:17)
    at E:\Nanashi\NanashiStable\core.js:102:55
    at Array.forEach (<anonymous>)
    at Client.<anonymous> (E:\Nanashi\NanashiStable\core.js:101:15)
    at Client.emit (node:events:388:22)
    at Object.module.exports [as GUILD_MEMBER_ADD] (E:\Nanashi\NanashiStable\node_modules\discord.js\src\client\websocket\handlers\GUILD_MEMBER_ADD.js:16:14)
    at WebSocketManager.handlePacket (E:\Nanashi\NanashiStable\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (E:\Nanashi\NanashiStable\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (E:\Nanashi\NanashiStable\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (E:\Nanashi\NanashiStable\node_modules\ws\lib\event-target.js:125:16)
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__

**Comment by xdorxble** [comment]
This IS a bug report.

**Comment by xdorxble** [comment]
Mister @iCrawl

**Comment by wasdennnoch** [comment]
It looks like in `core.js:102:55` you are improperly calling a method on a collection, which expects a function as its first argument, while you are passing something that's not a function. According to the stack trace the error most probably lies in your code, not Discord.js.
