### ISSUE TITLE
Accessing TextChannel.members throws an error 

### ISSUE THREAD

**Issue by c00kie17** [discordjs/discord.js#5184]
Hi whenever I try to access TextChannel.members I get this error.

```
 const channel = await discordClient.channels.fetch(channelId)
 console.log(channel.members)
```

this is the stackstace for the error 
```
TypeError: Cannot read property 'id' of undefined
      at GuildMemberRoleManager.get _roles [as _roles] (/home/c00kie/Documents/TL/tournamentsapi/node_modules/discord.js/src/managers/GuildMemberRoleManager.js:32:101)
      at GuildMemberRoleManager.get cache [as cache] (/home/c00kie/Documents/TL/tournamentsapi/node_modules/discord.js/src/managers/GuildMemberRoleManager.js:41:17)
      at TextChannel.memberPermissions (/home/c00kie/Documents/TL/tournamentsapi/node_modules/discord.js/src/structures/GuildChannel.js:155:32)
      at TextChannel.permissionsFor (/home/c00kie/Documents/TL/tournamentsapi/node_modules/discord.js/src/structures/GuildChannel.js:114:29)
      at TextChannel.get members [as members] (/home/c00kie/Documents/TL/tournamentsapi/node_modules/discord.js/src/structures/GuildChannel.js:286:16)
      at Object.exports.checkUserInChannel (/home/c00kie/Documents/TL/tournamentsapi/src/workers/discord/discord.ts:115:23)
      at checkUserInChannel (/home/c00kie/Documents/TL/tournamentsapi/src/workers/discord/routers/profiles.ts:19:30)
      at dispatch (/home/c00kie/Documents/TL/tournamentsapi/node_modules/koa-compose/index.js:42:32)
      at /home/c00kie/Documents/TL/tournamentsapi/src/workers/discord/routers/profiles.ts:43:10
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at bodyParser (/home/c00kie/Documents/TL/tournamentsapi/node_modules/koa-bodyparser/index.js:95:5)
      at /home/c00kie/Documents/TL/tournamentsapi/node_modules/koa-compress/lib/index.js:38:5
      at cors (/home/c00kie/Documents/TL/tournamentsapi/node_modules/@koa/cors/index.js:56:32)
      at logger (/home/c00kie/Documents/TL/tournamentsapi/node_modules/koa-logger/index.js:67:7)
      at /home/c00kie/Documents/TL/tournamentsapi/src/workers/discord/runworker.ts:23:5
```

Please let me know if im missing something or if this is a duplicate

**Further details:**

- discord.js version:12.5.1
- Node.js version:12.16.2
- Operating system: Ubuntu 20.04.1 LTS
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: ['USER', 'GUILD_MEMBER', 'MESSAGE', 'REACTION', 'CHANNEL']
- gateway intents: ['GUILD_PRESENCES', 'GUILD_MEMBERS']

Thank You

**Comment by monbrey** [comment]
Are those the only two intents you provide in your constructor? You need several of the non-privileged ones too for discord.js to function correctly eg `GUILDS` to get Guild, Guild Channel and Role information.

**Comment by c00kie17** [comment]
Thanks adding the `GUILDS` Intent fixed the Issue.
