### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by PBJF** [discordjs/discord.js#5204]
```
C:\Users\u\Desktop\project>node .
C:\Users\u\Desktop\project\node_modules\discord.js\src\util\Collection.js:8
    return this.map(e => (typeof e?.toJSON === 'function' ? e.toJSON() : Util.flatten(e)));
                                   ^

SyntaxError: Unexpected token '.'
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1053:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1101:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\Users\u\Desktop\project\node_modules\←[4mdiscord.js←[24m\src\rest\RESTManager.js:7:20)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
```

**Comment by almostSouji** [comment]
You have installed the development branch or a PR derived from it which requires node 14.0.0+ as of 90d458820b145a01d59399f7c99c7364f5f07702 and uses [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).
