### ISSUE TITLE
When sending a message update (`patch`), if the connection is reset during the HTTPRequest, the entire Node app crashes instead of being caught in any type of exception handler.

### ISSUE THREAD

**Issue by rednnnno** [discordjs/discord.js#5206]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
When sending a message update (`patch`), if the connection is reset during the HTTPRequest, the entire Node app crashes instead of being caught in any type of exception handler.

There is no way to catch the error and this is inconsistent since just sending a message seems to work as that times out as expected...

I'm sorry I don't have simple code r/n... but here is the error message:
```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:213:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
 [Connexion error, trying in 10s] ***\node_modules\discord.js\src\rest\RequestHandler.js:94
        throw new HTTPError(error.message, error.constructor.name, error.status, request.method, request.path);
              ^

HTTPError [FetchError]: request to https://discord.com/api/v7/channels/*******************/messages/******************* failed, reason: connect ENETUNREACH 162.159.138.232:443
    at RequestHandler.execute (****\node_modules\discord.js\src\rest\RequestHandler.js:94:15)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async RequestHandler.push (****\node_modules\discord.js\src\rest\RequestHandler.js:39:14) {
  code: 500,
  method: 'patch',
  path: '/channels/*******************/messages/*******************'
}
```

This seems to happen because the `await` thrown Error is handled in a system context (`node:internal/process/task_queues:93:5`), and the reason this happens is because `Message._patch()` method is apparently still called when the `ECONNRESET` happens with an `undefined` `data` parameter , throwing an error when looking for the `id` property

**Reproduce**
Make a application that updates a single message every second; disconnect network; watch app crash even if wrapped in a try/catch or .catch().

** Fugly patch that works for me for now:**
`structures/Message.js:52`
```js
    if (typeof data !== 'object') {
        return;
    }
````

**Further details:**

*See above*

- discord.js version: 12.5.1
- Node.js version: 15.5.1
- Operating system: Windows 10.0.18363.476
- Priority this issue should have – please be realistic and elaborate if possible:
 Low, but important if you want high-reliability on bad connections
**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

[ I highly doubt this was touched in main branch, no changes in code were found in `structures/Message.js`].

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by rednnnno** [comment]
I have checked and the issue has to do with how node/JS handles the event calls; when in a Worker thread, the catch needs to be triggered in the Worker rather than in the event handling / instancing.
