### ISSUE TITLE
Error in Client.js catch instead of catch(err)

### ISSUE THREAD

**Issue by RoverBot-Dev** [discordjs/discord.js#5266]
When i open my bot it says 

```
 ogs
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rbd/pnpm-volume/ccee32f3-ab83-48eb-88ad-c878a97dde23/node_modules/discord.js/src/index.js:8:11)
/rbd/pnpm-volume/ccee32f3-ab83-48eb-88ad-c878a97dde23/node_modules/discord.js/src/client/Client.js:42
    } catch {
            ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rbd/pnpm-volume/ccee32f3-ab83-48eb-88ad-c878a97dde23/node_modules/discord.js/src/index.js:8:11)
/rbd/pnpm-volume/ccee32f3-ab83-48eb-88ad-c878a97dde23/node_modules/discord.js/src/client/Client.js:42
    } catch {
            ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rbd/pnpm-volume/ccee32f3-ab83-48eb-88ad-c878a97dde23/node_modules/discord.js/src/index.js:8:11)
/rbd/pnpm-volume/ccee32f3-ab83-48eb-88ad-c878a97dde23/node_modules/discord.js/src/client/Client.js:42
    } catch {
            ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rbd/pnpm-volume/ccee32f3-ab83-48eb-88ad-c878a97dde23/node_modules/discord.js/src/index.js:8:11)
/rbd/pnpm-volume/ccee32f3-ab83-48eb-88ad-c878a97dde23/node_modules/discord.js/src/client/Client.js:42
    } catch {
            ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rbd/pnpm-volume/ccee32f3-ab83-48eb-88ad-c878a97dde23/node_modules/discord.js/src/index.js:8:11)
/rbd/pnpm-volume/ccee32f3-ab83-48eb-88ad-c878a97dde23/node_modules/discord.js/src/client/Client.js:42
    } catch {
            ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rbd/pnpm-volume/ccee32f3-ab83-48eb-88ad-c878a97dde23/node_modules/discord.js/src/index.js:8:11)
/rbd/pnpm-volume/

```
Which is an error about the Client.js in the module

**Comment by anandre** [comment]
Discord.js requires Node 12 or higher.  Please read the requirements of the packages you're using.
