### ISSUE TITLE
to many error bruhhhh

### ISSUE THREAD

**Issue by ITZRais** [discordjs/discord.js#5285]
hi.. so when i try to run the bot, idk why.. it's showing this error, i can't solve this error....

``Starting the bot...
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\User\Documents\Programs\!Discord Bot\Pterodactyl Bot\Falixnodes Ptero\node_modules\sqlite\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node'
Require stack:
- C:\Users\User\Documents\Programs\!Discord Bot\Pterodactyl Bot\Falixnodes Ptero\node_modules\sqlite\node_modules\sqlite3\lib\sqlite3-binding.js
- C:\Users\User\Documents\Programs\!Discord Bot\Pterodactyl Bot\Falixnodes Ptero\node_modules\sqlite\node_modules\sqlite3\lib\sqlite3.js
- C:\Users\User\Documents\Programs\!Discord Bot\Pterodactyl Bot\Falixnodes Ptero\node_modules\sqlite\main.js
- C:\Users\User\Documents\Programs\!Discord Bot\Pterodactyl Bot\Falixnodes Ptero\commands\control\kill.js
- C:\Users\User\Documents\Programs\!Discord Bot\Pterodactyl Bot\Falixnodes Ptero\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\User\Documents\Programs\!Discord Bot\Pterodactyl Bot\Falixnodes Ptero\node_modules\sqlite\node_modules\sqlite3\lib\sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\Documents\\Programs\\!Discord Bot\\Pterodactyl Bot\\Falixnodes Ptero\\node_modules\\sqlite\\node_modules\\sqlite3\\lib\\sqlite3-binding.js',
    'C:\\Users\\User\\Documents\\Programs\\!Discord Bot\\Pterodactyl Bot\\Falixnodes Ptero\\node_modules\\sqlite\\node_modules\\sqlite3\\lib\\sqlite3.js',
    'C:\\Users\\User\\Documents\\Programs\\!Discord Bot\\Pterodactyl Bot\\Falixnodes Ptero\\node_modules\\sqlite\\main.js',
    'C:\\Users\\User\\Documents\\Programs\\!Discord Bot\\Pterodactyl Bot\\Falixnodes Ptero\\commands\\control\\kill.js',
    'C:\\Users\\User\\Documents\\Programs\\!Discord Bot\\Pterodactyl Bot\\Falixnodes Ptero\\index.js'
  ]
}``

i use 12.5.1 discord.js version. and 14.15.4 node.js version. and i use sqlite module too.. but when i use node.js version 9.11.1... this error appeared

``Starting the bot...
C:\Users\User\Documents\Programs\!Discord Bot\Pterodactyl Bot\Falixnodes Ptero\node_modules\discord.js\src\client\Client.js:42
    } catch {
            ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)`` 
    
    how i can fix it?

**Comment by kyranet** [comment]
discord.js v12 requires Node.js v12. Please don't remove the template, and your error is related to sqlite, something we don't include in this project.

---

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**
