### ISSUE TITLE
TypeError: channelClass is not a constructor

### ISSUE THREAD

**Issue by obcinapzz** [discordjs/discord.js#5340]
/home/container/node_modules/discord.js/src/client/actions/ChannelUpdate.js:42
const newChannel = new channelClass(channel.guild, data);
TypeError: channelClass is not a constructor
at ChannelUpdateAction.handle (/home/container/node_modules/discord.js/src/client/actions/ChannelUpdate.js:42:28)
at ChannelUpdateHandler.handle (/home/container/node_modules/discord.js/src/client/websocket/packets/handlers/ChannelUpdate.js:7:34)
at WebSocketPacketManager.handle (/home/container/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
at WebSocketConnection.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
at WebSocketConnection.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:120:16)
at WebSocket.emit (events.js:315:20)
at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:789:20)
at Receiver.emit (events.js:315:20)
at Receiver.dataMessage (/home/container/node_modules/ws/lib/receiver.js:422:14)

This error right here happens randomly throughout the day I dont have `const newChannel = new channelClass(channel.guild, data);` in my code anywhere and no command seems to be causing the issue so I'm just confused.

**Comment by WeDevelop-OS** [comment]
Its because you cant code man, just get good.

**Comment by advaith1** [comment]
Don't delete the issue template, fill it out, it includes information you must provide:

```
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

<!--
Remove the comment and fill out the commit hash if this applies to you:
(While it's not a requirement to test your issue on the master branch, it would make fixing the problem a lot easier for us, so please do so if possible.)

- I have also tested the issue on latest master, commit hash: `xxx`
-->
```

**Comment by BannerBomb** [comment]
The only branch I see `new channelClass` used in, is discord.js 11. If you're using v11 it's deprecated and no longer receives updates. https://github.com/discordjs/discord.js/blob/da39e858a1d4bd23a2af2e693024512426615557/src/client/actions/ChannelUpdate.js#L42

**Comment by polygonee** [comment]
The way you don't use a codeblock and the way you word it makes me think you don't know JS. Also, you obviously have that in your code because node literally points the error to that. If you really think that you don't have it in your code, just run a quick `CTRL` + `F` and see it.

**Comment by vBread** [comment]
> You obviously have that in your code
No. It's from the library.

**Comment by WeDevelop-OS** [comment]
@polygonee Incase your illiterate, He was using v11. No part of that error points toward a file outside of node modules, now go crawl back to bot ghost.com instead of commenting on closed discord.js issues.

**Comment by obcinapzz** [comment]
> The way you don't use a codeblock and the way you word it makes me think you don't know JS. Also, you obviously have that in your code because node literally points the error to that. If you really think that you don't have it in your code, just run a quick `CTRL` + `F` and see it.

I literally did that stupid retard dont ever and i mean ever try to pull some shit like this again
