### ISSUE TITLE
DiscordAPIError: Missing Permissions 

### ISSUE THREAD

**Issue by ashikuri** [discordjs/discord.js#5568]
```
C:\Lab\akimitsu-bot\node_modules\discord.js\src\rest\RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Missing Permissions
    at RequestHandler.execute (C:\Lab\akimitsu-bot\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async RequestHandler.push (C:\Lab\akimitsu-bot\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async GuildMemberRoleManager.remove (C:\Lab\akimitsu-bot\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:125:7) {
  method: 'delete',
  path: '/guilds/836199669049589813/members/567795611911454731/roles/837234086930022412',
  code: 50013,
  httpStatus: 403
}
```

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
