### ISSUE TITLE
Interactions API Error: Command name is invalid

### ISSUE THREAD

**Issue by gruselhaus** [discordjs/discord.js#5597]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

Command Data which I pass into `client.guilds.cache.get(#id)?.commands.set();`: 
```js
[
  NameInteraction {
    options: [ [Object], [Object] ],
    bot: Bot {
      config: [Object],
      client: [Client],
      blacklist: Collection(0) [Map] {},
      MongoConnector: [MongoConnector],
      db: undefined,
      logger: [LogHandler],
      jobs: [JobHandler],
      events: [EventHandler],
      commands: [CommandHandler],
      interactions: [InteractionHandler],
      twitchClient: [ChatClient]
    },
    name: 'name',
    description: 'Generiere deinen eigenen Charakternamen',
    category: 'Interactions'
  },
  NicknameInteraction {
    options: [ [Object] ],
    bot: Bot {
      config: [Object],
      client: [Client],
      blacklist: Collection(0) [Map] {},
      MongoConnector: [MongoConnector],
      db: undefined,
      logger: [LogHandler],
      jobs: [JobHandler],
      events: [EventHandler],
      commands: [CommandHandler],
      interactions: [InteractionHandler],
      twitchClient: [ChatClient]
    },
    name: 'nickname',
    description: 'Nicknamen auf diesem Server setzen',
    category: 'Interactions'
  },
  RollInteraction {
    options: [ [Object] ],
    bot: Bot {
      config: [Object],
      client: [Client],
      blacklist: Collection(0) [Map] {},
      MongoConnector: [MongoConnector],
      db: undefined,
      logger: [LogHandler],
      jobs: [JobHandler],
      events: [EventHandler],
      commands: [CommandHandler],
      interactions: [InteractionHandler],
      twitchClient: [ChatClient]
    },
    name: 'roll',
    description: 'powered by RollButler',
    category: 'Interactions'
  }
]
```

API Response:
```
DiscordAPIError: Invalid Form Body
0.options[0].name: Command name is invalid
0.options[1].name: Command name is invalid
2.options[0].name: Command name is invalid
    at RequestHandler.execute (/Users/nico/Documents/pegabot/node_modules/discord.js/src/rest/RequestHandler.js:243:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/Users/nico/Documents/pegabot/node_modules/discord.js/src/rest/RequestHandler.js:49:14)
    at async GuildApplicationCommandManager.set (/Users/nico/Documents/pegabot/node_modules/discord.js/src/managers/ApplicationCommandManager.js:119:18) {
  method: 'put',
  path: '/applications/815936432102309898/guilds/732224027661172757/commands',
  code: 50035,
  httpStatus: 400
}
```

**Further details:**

- discord.js version: 9f74f95f69f4aa8a9a23c160e25dc61010c0a8e0
- Priority this issue should have – please be realistic and elaborate if possible: high

**Relevant client options:**

- gateway intents: all

@vaporox do you have any ideas?

**Comment by adrifcastr** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.

**Comment by gruselhaus** [comment]
This is related to the interactions feature merged into `master` yesterday. Maybe there is a tiny problem?

**Comment by DiscordCatto** [comment]
Is all of the option names lowercase?

**Comment by VincentThomas06** [comment]
> Can I use UPPERCASE command name?

No you can't
