### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by PixelByteDrive** [discordjs/discord.js#5741]
**Please describe the problem you are having in as much detail as possible:**

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/rbd/pnpm-volume/c5a2c49e-e6a6-462b-bc27-6589c7056565/node_modules/.registry.npmjs.org/discord.js/12.5.3/node_modules/discord.js/src/index.js:8:11)

**Include a reproducible code sample here, if possible:**

```js
const Discord = require('discord.js');
const client = new Discord.Client();

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

client.on('message', msg => {
  if (msg.content === 'ping') {
    msg.reply('Pong!');
  }
});

client.login(process.env.token);
```

**Further details:**

- discord.js version: ^12.5.3
- Node.js version: 8.x
- Operating system: Ubuntu (www.glitch.com)
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by itzoreomc** [comment]
Node.js 14.0.0 or newer is required.
