### ISSUE TITLE
TypeError: Options is not iterable when an interaction is recieved

### ISSUE THREAD

**Issue by HippoBaguette** [discordjs/discord.js#5949]
**Please describe the problem you are having in as much detail as possible:**
When an interaction is sent and an `INTERACTION_CREATE` event happens, this error occurs:
```
C:\Users\user\Documents\GitHub\DiscordBot\node_modules\discord.js\src\structures\CommandInteraction.js:264
    for (const option of options) {
                         ^

TypeError: options is not iterable
    at CommandInteraction._createOptionsCollection (C:\Users\user\Documents\GitHub\DiscordBot\node_modules\discord.js\src\structures\CommandInteraction.js:264:26)
    at new CommandInteraction (C:\Users\user\Documents\GitHub\DiscordBot\node_modules\discord.js\src\structures\CommandInteraction.js:48:25)
    at Object.module.exports [as INTERACTION_CREATE] (C:\Users\user\Documents\GitHub\DiscordBot\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:11:25)
    at WebSocketManager.handlePacket (C:\Users\user\Documents\GitHub\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (C:\Users\user\Documents\GitHub\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (C:\Users\user\Documents\GitHub\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:300:10)
    at WebSocket.onMessage (C:\Users\user\Documents\GitHub\DiscordBot\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:376:20)
    at Receiver.receiverOnMessage (C:\Users\user\Documents\GitHub\DiscordBot\node_modules\ws\lib\websocket.js:833:20)
    at Receiver.emit (events.js:376:20)
```
**Include a reproducible code sample here, if possible:**

```js
client.once('ready', async () => {
       let ping = {
        	name: 'ping',
		description: 'pong',
	}
       const guild = client.guilds.cache.get('1234567891011');
       guild.commands.create(ping);
});
client.on('interaction', async interaction => {
	if (!interaction.isCommand()) return;
	if (interaction.commandName === 'ping') await interaction.reply('Pong!');
});
```

**Further details:**

- discord.js version: 13.0.0-dev
- Node.js version: 14.17.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: `['MESSAGE', 'CHANNEL', 'REACTION']`
- gateway intents: `Discord.Intents.ALL`
- other:
```
allowedMentions: {
		parse: ['users', 'roles'],
		repliedUser: true
	}
```

**Comment by DTrombett** [comment]
What commit are you in? Did you try to update to the latest?

**Comment by iCrawl** [comment]
__The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.__
