### ISSUE TITLE
Send mp3 file and recive this error = [AbortError]: The user aborted a request.

### ISSUE THREAD

**Issue by AmirHSD57** [discordjs/discord.js#6118]
This is code:
```js
message.channel.send({files: [./downloader/music/${musictitle}_Edo-Music.mp3]});
``` 
// or
```js
Const musicfile = new Discord.Attechment(./downloader/music/${musictitle}_Edo-Music.mp3);
Message.channel.send("mp3 file", musicfile);
```
And i recive this error:
how to fix this?

```js
(node:7036) UnhandledPromiseRejectionWarning: AbortError: The user aborted a request.
    at RequestHandler.execute (C:\Users\Lion\Desktop\Music Discord - V4\node_modules\discord.js\src\rest\RequestHandler.js:93:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processTimers (internal/timers.js:494:9)
    at async RequestHandler.push (C:\Users\Lion\Desktop\Music Discord - V4\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To 
terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:7036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by vBread** [comment]
> The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.
