### ISSUE TITLE
AbortController is not defined

### ISSUE THREAD

**Issue by ThePedroo** [discordjs/discord.js#6318]
Some time this errors appers out of blue

```js
(node:26) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:172:15)
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:176:19)
    at RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:50:25)
```

**Further details:**

- discord.js version: latest (13.0.0)
- Node.js version: v14
- Operating system: Linux (in container)
- Priority this issue should have: low

**Relevant client options:**

- partials: ?
- gateway intents: server intents

**Comment by kyranet** [comment]
You need Node.js v16.

**Comment by AustrianDev** [comment]
IIRC `AbortController` was introduced in Node v16. By the way discord.js needs Node v16 or more. Try updating
