### ISSUE TITLE
Type Error when running code

### ISSUE THREAD

**Issue by theblobscp** [discordjs/discord.js#6340]
**Please describe the problem you are having in as much detail as possible:**
When I tried to run my bot's source code, I receive this error:

```powershell
C:\Users\User\Documents\GitHub\Discord-Bot\node_modules\discord.js\src\client\Client.js:544
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Users\User\Documents\GitHub\Discord-Bot\node_modules\discord.js\src\client\Client.js:544:13)
    at new Client (C:\Users\User\Documents\GitHub\Discord-Bot\node_modules\discord.js\src\client\Client.js:73:10)
    at Object.<anonymous> (C:\Users\User\Documents\GitHub\Discord-Bot\commands\index.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}
```

**Further details:**

- discord.js version: 13.0.1
- Node.js version: 16.6.1
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: High, running bots is important

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by kyranet** [comment]
As the error says:

> Valid intents must be provided for the Client.

Please read the [migration guide](https://discordjs.guide/additional-info/changes-in-v13.html) for more information.
