### ISSUE TITLE
embeds: this.options.embeds?.map(embed => new MessageEmbed(embed).toJSON()

### ISSUE THREAD

**Issue by NotTimIsReal** [discordjs/discord.js#6356]
Hello when I try to make my bot send embeds it sends the embed but the next embed doesn't get sent and I get this error,
```
home/ubuntu/bbarevamp/node_modules/discord.js/src/structures/MessagePayload.js:184
      embeds: this.options.embeds?.map(embed => new MessageEmbed(embed).toJSON()),
                                   ^

TypeError: this.options.embeds?.map is not a function
    at MessagePayload.resolveData (/home/ubuntu/bbarevamp/node_modules/discord.js/src/structures/MessagePayload.js:184:36)
    at TextChannel.send (/home/ubuntu/bbarevamp/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:167:61)
    at module.exports (/home/ubuntu/bbarevamp/events/guild/message.js:70:36)
    at Client.emit (node:events:377:35)
    at MessageCreateAction.handle (/home/ubuntu/bbarevamp/node_modules/discord.js/src/client/actions/MessageCreate.js:31:18)
    at Object.module.exports [as MESSAGE_CREATE] (/home/ubuntu/bbarevamp/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/ubuntu/bbarevamp/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/home/ubuntu/bbarevamp/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/home/ubuntu/bbarevamp/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/home/ubuntu/bbarevamp/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:365:28)
    at Receiver.receiverOnMessage (/home/ubuntu/bbarevamp/node_modules/ws/lib/websocket.js:970:20)
    at Receiver.emit (node:events:365:28)
    at Receiver.dataMessage (/home/ubuntu/bbarevamp/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/home/ubuntu/bbarevamp/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/home/ubuntu/bbarevamp/node_modules/ws/lib/receiver.js:143:22)
```
I am using Discord.js V13 and Node 16.6.0.

Code:

```https://pastebin.com/hzqww4Lg```

The import from exports imports a function like this

```
function reply(content, mention, message){
    message.reply({ content:content, allowedMentions: { repliedUser: mention }})
  }
```

**Comment by monbrey** [comment]
Embeds are sent as an array: `embeds: [embed1, embed2, ...embed10]`

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by NotTimIsReal** [comment]
> Embeds are sent as an array: `embeds: [embed1, embed2, ..., embed10]`
> 
> **The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

I have all my commands with embeds are sent like this

**Comment by monbrey** [comment]
The error comes from line 70 of `/home/ubuntu/bbarevamp/events/guild/message.js:70:36` - on that line it seems you arent.

**Comment by NotTimIsReal** [comment]
That line is like message.channel.send(embeds:new Discord.MessageEmbed) is there a way I can keep it that way without entirely needing to make a new variable?

**Comment by NotTimIsReal** [comment]
if there isn't I will fix up my code and close the issue

**Comment by monbrey** [comment]
Just put it in an array. Issue should have been closed and taken to the server already.

**Comment by NotTimIsReal** [comment]
Thank you for the help anyways
