### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined

### ISSUE THREAD

**Issue by idkroff** [discordjs/discord.js#6364]
Discord.js don't work with the foloowing code, and throws out this error: 

> UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
    at RequestHandler.execute (K:\GitHub\taxibot\node_modules\discord.js\src\rest\RequestHandler.js:172:15)
    at RequestHandler.execute (K:\GitHub\taxibot\node_modules\discord.js\src\rest\RequestHandler.js:176:19)
    at RequestHandler.push (K:\GitHub\taxibot\node_modules\discord.js\src\rest\RequestHandler.js:50:25)
    at async WebSocketManager.connect (K:\GitHub\taxibot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128:9)
    at async Client.login (K:\GitHub\taxibot\node_modules\discord.js\src\client\Client.js:245:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:20720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Here's my code: 
```js
let token = 'my-token';
let prefix = '!';

const { Client, Intents } = require('discord.js');

const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES] });

client.once('ready', (msg) => {
	console.log('Ready!');
});

client.login(token);
```

**Further details:**

- discord.js version: 13.0.1
- Node.js version: v14.16.0
- Windows 10
- Medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by Poly-Pixel** [comment]
You must be using Node 16.6.0 or higher to use Discord.js v13
