### ISSUE TITLE
abortcontroller is not defined

### ISSUE THREAD

**Issue by crypto-rgb** [discordjs/discord.js#6373]
(node:9680) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
    at RequestHandler.execute (C:\Users\user\bot\node_modules\discord.js\src\rest\RequestHandler.js:172:15)  
    at RequestHandler.execute (C:\Users\user\bot\node_modules\discord.js\src\rest\RequestHandler.js:176:19)  
    at RequestHandler.push (C:\Users\user\bot\node_modules\discord.js\src\rest\RequestHandler.js:50:25)      
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async WebSocketManager.connect (C:\Users\user\bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128:9)
    at async Client.login (C:\Users\huyma\user\bot\discord.js\src\client\Client.js:245:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DTrombett** [comment]
>>> • Discord.js v13 requires Node.js version 16.6 or newer to run!
• If you run your bot through a process manager, make sure to restart the daemon process to use the new node version
• Unsure you are using the right one? Log console.log(process.version) in your code
