### ISSUE TITLE
RangeError [BITFIELD_INVALID]

### ISSUE THREAD

**Issue by L0SER8228** [discordjs/discord.js#6415]
**Please describe the problem you are having in as much detail as possible:**
```
RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number: DJS.Permissions.FLAGS.CREATE_INSTANT_INVITE.
    at Function.resolve (/app/node_modules/discord.js/src/util/BitField.js:152:11)
    at Permissions.has (/app/node_modules/discord.js/src/util/BitField.js:44:28)
    at Permissions.has (/app/node_modules/discord.js/src/util/Permissions.js:54:85)
```
**Include a reproducible code sample here, if possible:**
```js
const DJS = require("discord.js");
DJS.Permissions.FLAGS.CREATE_INSTANT_INVITE
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: >=16.6.0
- Operating system: Linux
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by kyranet** [comment]
The reproducible code sample does work as intended, the issue here is a mis-use of `Permissions#has`, where it seems you're passing a string instead of the enum value (unless you edited the error message).

**Comment by kyranet** [comment]
Closing due to inactivity and lack of a reproducible code sample.
