### ISSUE TITLE
GuildStickerManager.create() doesn't work with URL | TypeError [REQ_RESOURCE_TYPE]: The resource must be a string, Buffer or a valid file stream.

### ISSUE THREAD

**Issue by IvanGodinez21** [discordjs/discord.js#6432]
**Please describe the problem you are having in as much detail as possible:**
I was trying to add a sticker to a guild using this example:

_Notes:_ I've tested it just using a URL
```js
guild.stickers.create('https://i.imgur.com/w3duR07.png', 'rip')
  .then(sticker => console.log(`Created new sticker with name ${sticker.name}!`))
  .catch(console.error);
```
Source: https://discord.js.org/#/docs/main/13.1.0/class/GuildStickerManager?scrollTo=create

But I'm getting this error
```
C:\Users\ivano\Repositorios\GitHubDesktop\EmojiPackager\node_modules\discord.js\src\util\DataResolver.js:125
    throw new TypeError('REQ_RESOURCE_TYPE');
          ^

TypeError [REQ_RESOURCE_TYPE]: The resource must be a string, Buffer or a valid file stream.
    at Function.resolveFile (C:\Users\ivano\Repositorios\GitHubDesktop\EmojiPackager\node_modules\discord.js\src\util\DataResolver.js:125:11)
    at Function.resolveFile (C:\Users\ivano\Repositorios\GitHubDesktop\EmojiPackager\node_modules\discord.js\src\structures\MessagePayload.js:240:41)
    at GuildStickerManager.create (C:\Users\ivano\Repositorios\GitHubDesktop\EmojiPackager\node_modules\discord.js\src\managers\GuildStickerManager.js:60:39)
    at Object.module.exports.run (C:\Users\ivano\Repositorios\GitHubDesktop\EmojiPackager\src\apps\global\importStickers.js:13:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (C:\Users\ivano\Repositorios\GitHubDesktop\EmojiPackager\src\events\interactionCreate.js:18:21) {
  [Symbol(code)]: 'REQ_RESOURCE_TYPE'
}
[nodemon] app crashed - waiting for file changes before starting...
```
**Include a reproducible code sample here, if possible:**

```js
module.exports.run = async (client, interaction) => {
   await interaction.guild.stickers.create({file: 'https://i.imgur.com/w3duR07.png', name: 'rip'});
}
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 16.6.1
- Operating system: Windows 10 Home
- Priority this issue should have – please be realistic and elaborate if possible: Low

**Relevant client options:**

- partials: 'USER', 'CHANNEL', 'GUILD_MEMBER', 'MESSAGE', 'REACTION'
- gateway intents: Intents.FLAGS.DIRECT_MESSAGES, Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_EMOJIS_AND_STICKERS, Intents.FLAGS.GUILD_INTEGRATIONS, Intents.FLAGS.GUILD_MEMBERS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_MESSAGE_REACTIONS, Intents.FLAGS.GUILD_WEBHOOKS
- other: none

**Comment by Keke27210** [comment]
You are not supposed to pass an object to `GuildStickerManager#create`, but as documentation suggests (and the example you literally posted in the message shows), several parameters corresponding respectively to the sticker data, its name, its tag and extra options.

**Please use the Discord server for those issues in the future as this is not a bug in itself.**
