### ISSUE TITLE
AbortController is not defined

### ISSUE THREAD

**Issue by Danipro2007** [discordjs/discord.js#6470]
Whatever I do, with the latest version of discord.js, the code doesn't work for me, I always get the error:

```js
(node:37728) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
    at RequestHandler.execute (C:\Users\mella\Desktop\MisPruebas\node_modules\discord.js\src\rest\RequestHandler.js:172:15)
    at RequestHandler.execute (C:\Users\mella\Desktop\MisPruebas\node_modules\discord.js\src\rest\RequestHandler.js:176:19)
    at RequestHandler.push (C:\Users\mella\Desktop\MisPruebas\node_modules\discord.js\src\rest\RequestHandler.js:50:25)
    at async WebSocketManager.connect (C:\Users\mella\Desktop\MisPruebas\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128:9)
    at async Client.login (C:\Users\mella\Desktop\MisPruebas\node_modules\discord.js\src\client\Client.js:245:7)
```

**Comment by vladfrangu** [comment]
Discord.js 13 requires nodejs 16

__**This issue tracker is only for bug reports and suggesting enhancements.**__

If you have a question, please ask it in the **[Discord Server](https://discord.gg/djs) or in [GitHub Discussions](https://github.com/discordjs/discord.js/discussions)** instead of opening an issue – you'll be redirected there anyways.
