### ISSUE TITLE
Bot crash while it updates itself

### ISSUE THREAD

**Issue by Positive2022** [discordjs/discord.js#6510]
**Please describe the problem you are having in as much detail as possible:**
I was updating my bot's pfp and I had my bots console opened cuz I was updating it. Just when i updated the bot's pfp, the bot crashed giving out an error.

Error:
```js
/home/container/node_modules/discord.js/src/client/actions/UserUpdate.js:11
    const oldUser = newUser._update(data);
                            ^

TypeError: Cannot read property '_update' of undefined
    at UserUpdateAction.handle (/home/container/node_modules/discord.js/src/client/actions/UserUpdate.js:11:29)
    at Object.module.exports [as USER_UPDATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/USER_UPDATE.js:4:29)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/home/container/node_modules/ws/lib/websocket.js:970:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/home/container/node_modules/ws/lib/receiver.js:517:14)
```

**Further details:**

- discord.js version: 13.1.0
- Node.js version: 16.1.0
- Operating system: LInux
- Priority this issue should have – please be realistic and elaborate if possible: Medium

**Relevant client options:**

- partials: none
- gateway intents: none
- other: All non privilleged intents.

**Comment by Positive2022** [comment]
Note: Also happened when I changed the bots username.
Note 2: The pfp error that occured when I changed application's pfp which ofcourse changes bot user's pfp.
