### ISSUE TITLE
Error that made the application crash after 1h30 of operation

### ISSUE THREAD

**Issue by Xamez** [discordjs/discord.js#6542]
**Code:**
```js
const Discord = require('discord.js-selfbot');
const client = new Discord.Client({ intents: ["GUILDS", "MESSAGES", "GUILD_MESSAGES", "DIRECT_MESSAGES"] });

client.on('ready', () => {
	console.log(`Connected as ${client.user.tag}`);
});

client.on('message', msg => {
	if (msg.channel.id === settings.channelId) {
		if (msg.author.id === settings.userId) {
			if (msg.embeds.length > 0){
				const embed = msg.embeds[0];
				if (embed.description !== undefined){
					const description = msg.embeds[0].description;
					// The rest is code that no longer uses the discord.js api
```

**Error:**
```
2021-08-28T13:34:53.569426+00:00 app[worker.1]: /app/node_modules/discord.js-selfbot/src/client/actions/MessageCreate.js:11
2021-08-28T13:34:53.569452+00:00 app[worker.1]:       const existing = channel.messages.cache.get(data.id);
2021-08-28T13:34:53.569453+00:00 app[worker.1]:                                         ^
2021-08-28T13:34:53.569454+00:00 app[worker.1]: 
2021-08-28T13:34:53.569454+00:00 app[worker.1]: TypeError: Cannot read property 'cache' of undefined
2021-08-28T13:34:53.569455+00:00 app[worker.1]:     at MessageCreateAction.handle (/app/node_modules/discord.js-selfbot/src/client/actions/MessageCreate.js:11:41)
2021-08-28T13:34:53.569456+00:00 app[worker.1]:     at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js-selfbot/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
2021-08-28T13:34:53.569456+00:00 app[worker.1]:     at WebSocketManager.handlePacket (/app/node_modules/discord.js-selfbot/src/client/websocket/WebSocketManager.js:386:31)
2021-08-28T13:34:53.569456+00:00 app[worker.1]:     at WebSocketShard.onPacket (/app/node_modules/discord.js-selfbot/src/client/websocket/WebSocketShard.js:435:22)
2021-08-28T13:34:53.569456+00:00 app[worker.1]:     at WebSocketShard.onMessage (/app/node_modules/discord.js-selfbot/src/client/websocket/WebSocketShard.js:293:10)
2021-08-28T13:34:53.569457+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:132:16)
2021-08-28T13:34:53.569457+00:00 app[worker.1]:     at WebSocket.emit (events.js:400:28)
2021-08-28T13:34:53.569458+00:00 app[worker.1]:     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:970:20)
2021-08-28T13:34:53.569458+00:00 app[worker.1]:     at Receiver.emit (events.js:400:28)
2021-08-28T13:34:53.569458+00:00 app[worker.1]:     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:517:14)
```

**Description:**

After about 1h30 of use, the application just crashed with this error message.
**(I just specify that I put only the code related to the api of discord)**

**Further details:**

- discord.js version: 13.0.1
- discord.js-selfbot version: 12.0.2 
- Node.js version: 14.17.4
- Operating system: Windows & Heroku (so Linux i guess)
- Priority this issue should have: Medium/High

**Relevant client options:**

- gateway intents: "GUILDS", "MESSAGES", "GUILD_MESSAGES", "DIRECT_MESSAGES"

**Comment by Jiralite** [comment]
1. Not discord.js-related
2. The name of the package you are using is screaming that you're breaking Discord's Terms of Service
