### ISSUE TITLE
Bug: Cannot read property 'client' of undefined at MessagePayload.resolveData

### ISSUE THREAD

**Issue by ky28059** [discordjs/discord.js#6582]
### Issue description

I have a discord bot that is trying to support both slash commands and text based messages. I am attempting to use some utility functions to make type-specific method calling easier:
```ts
export async function reply(target: Message | CommandInteraction, content: string | MessageOptions) {
    const callback = target instanceof CommandInteraction ? target.followUp : target.channel.send;
    return callback(content);
}
```
Attempting to use this with embeds gives a cryptic error about property 'client' in MessagePayload.
```ts
    async execute(target: Message | CommandInteraction, parsed: {comic: string}) {
        // ...
        await reply(target, {embeds: [xkcdEmbed]});
    }
```
```
  TypeError: Cannot read property 'client' of undefined
    at MessagePayload.resolveData (C:\Users\kevin\OneDrive\Documents\GitHub\RBot\node_modules\discord.js\src\structures\MessagePayload.js:159:23)
    at send (C:\Users\kevin\OneDrive\Documents\GitHub\RBot\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:167:61)
    at reply (C:\Users\kevin\OneDrive\Documents\GitHub\RBot\utils\messageUtils.ts:10:12)
    at Object.execute (C:\Users\kevin\OneDrive\Documents\GitHub\RBot\commands\normal\xkcd.ts:35:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.<anonymous> (C:\Users\kevin\OneDrive\Documents\GitHub\RBot\bot.ts:253:13)
```
Strangely, removing the union type of target and replacing `reply` with `target.channel.send` seems to fix this issue, even though `reply` should be calling `target.channel.send` anyways as the type of target is Message in this context.
```ts
    async execute(target: Message, parsed: {comic: string}) {
        // ...
        await target.channel.send({embeds: [xkcdEmbed]}); // works!
    }
```
It seems the issue is with this line of MessagePayload, but why would `this.target` be undefined?
```js
    let allowedMentions =
      typeof this.options.allowedMentions === 'undefined'
        ? this.target.client.options.allowedMentions
        : this.options.allowedMentions;
```

### Codesample

```typescript
import { Client, Message, CommandInteraction, MessageOptions, MessageEmbed } from 'discord.js'

const client = new Client({
    intents: [
        "GUILDS",
        "GUILD_MESSAGES",
        "GUILD_PRESENCES",
        "GUILD_MEMBERS",
        "GUILD_EMOJIS_AND_STICKERS",
        "GUILD_VOICE_STATES",
        "GUILD_MESSAGE_REACTIONS",
        "DIRECT_MESSAGES"
    ],
    presence: {activities: [{name: '!help', type: "LISTENING"}]}
});

async function reply(target: Message | CommandInteraction, content: string | MessageOptions) {
    const callback = target instanceof CommandInteraction ? target.followUp : target.channel.send;
    return callback(content);
}

client.on('messageCreate', async message => {
    const testEmbed = new MessageEmbed()
        .setColor(0x7f0000)
        .setAuthor(message.author.tag, message.author.displayAvatarURL())
        .setDescription(message.content)
    await reply(message, {embeds: [testEmbed]});
});

client.login('token');
```

### discord.js version

13.1.0

### Node.js version

16.7.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, DIRECT_MESSAGES

**Comment by ky28059** [comment]
Also, the issue template doesn't have an option for "no partials".

**Comment by monbrey** [comment]
`const callback = target instanceof CommandInteraction ? target.followUp : target.channel.send;`

This line is why it's undefined, you've detached the function from its class.

**Comment by ky28059** [comment]
Interesting, thanks!
```ts
export async function reply(target: Message | CommandInteraction, content: string | MessageOptions) {
    return target instanceof CommandInteraction
        ? target.followUp(content)
        : target.channel.send(content);
}
```
Changing the function to this seems to have helped.
