### ISSUE TITLE
Bug: TypeError: this.client.users.add is not a function

### ISSUE THREAD

**Issue by DomeQalt** [discordjs/discord.js#6593]
### Issue description

1. Fetch guild stickers with Guild#stickers.fetch();
2. Get error:
```js
node_modules\discord.js\src\structures\Sticker.js:81
    this.user = sticker.user ? this.client.users.add(sticker.user) : null;
                                                 ^

TypeError: this.client.users.add is not a function
    at Sticker._patch (node_modules\discord.js\src\structures\Sticker.js:81:50)
    at new Sticker (node_modules\discord.js\src\structures\Sticker.js:19:10)
    at GuildStickerManager._add (node_modules\discord.js\src\managers\CachedManager.js:51:32)
    at GuildStickerManager._add (node_modules\discord.js\src\managers\GuildStickerManager.js:31:18)
    at node_modules\discord.js\src\managers\GuildStickerManager.js:161:65
    at Array.map (<anonymous>)
    at GuildStickerManager.fetch (node_modules\discord.js\src\managers\GuildStickerManager.js:161:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

### Codesample

```typescript
let stickers = await message.guild.stickers.fetch();
```

### discord.js version

13.1.0

### Node.js version

16.7.0

### Operating system

Windows 11

### Priority this issue should have

High (immediate attention needed)

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_WEBHOOKS, GUILD_MESSAGES

**Comment by Jiralite** [comment]
Fixed in main: 2c449b6b48f5cbc88e666afa852055b873994ca5
