### ISSUE TITLE
jeez like what the

### ISSUE THREAD

**Issue by nitin-ojha1** [discordjs/discord.js#6606]
```js
#jeez like what the

~ $ node storage/shared/stuff/hazy/hazy.js
(node:5452) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
    at RequestHandler.execute (/storage/emulated/0/stuff/hazy/node_modules/discord.js/src/rest/RequestHandler.js:172:15)
    at RequestHandler.execute (/storage/emulated/0/stuff/hazy/node_modules/discord.js/src/rest/RequestHandler.js:176:19)
    at RequestHandler.push (/storage/emulated/0/stuff/hazy/node_modules/discord.js/src/rest/RequestHandler.js:50:25)
    at async WebSocketManager.connect (/storage/emulated/0/stuff/hazy/node_modules/discord.js/src/client/websocket/WebSocketManager.js:128:9)
    at async Client.login (/storage/emulated/0/stuff/hazy/node_modules/discord.js/src/client/Client.js:245:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### discord.js version

dont know, maybe the newest

### Node.js version

dont know, maybe thhhe newest

### Operating system

android (termux application)

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE, REACTION

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_EMOJIS_AND_STICKERS, GUILD_INTEGRATIONS, GUILD_WEBHOOKS, GUILD_INVITES, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_REACTIONS, GUILD_MESSAGE_TYPING, DIRECT_MESSAGES, DIRECT_MESSAGE_REACTIONS, DIRECT_MESSAGE_TYPING

### I have tested this issue on a development release

i dont know what is this

**Comment by Megatank58** [comment]
You need node.js version 16.6+ for discord.js v13

**Comment by nitin-ojha1** [comment]
okay lemme check then

**Comment by almostSouji** [comment]
The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/djs) instead of opening an issue – you will get redirected there anyway.

**Comment by nitin-ojha1** [comment]
naah, they arent helping on the discord server, they are just being rude to me and said me to stop, anyways

**Comment by NMW03** [comment]
They told you to update node.js...?
![image](https://user-images.githubusercontent.com/50991261/132357917-f7da2844-53e4-4ccc-8f34-8ca436a027c9.png)
![image](https://user-images.githubusercontent.com/50991261/132358268-3ce2db66-58fd-4704-947d-c461cd9cd68e.png)

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by kekkodance** [comment]
e

**Comment by nomyTx** [comment]
e

**Comment by GangsterFox** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by smartfrigde** [comment]
L

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by smartfrigde** [comment]
L

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by papycochon** [comment]
e

**Comment by nomyTx** [comment]
e
e
e
e
e
e
e
e
e
e

**Comment by kekkodance** [comment]
e

**Comment by nitin-ojha1** [comment]
you didnt see the harrasing one tho, its still there

**Comment by kekkodance** [comment]
> 
> 
> you didnt see the harrasing one tho, its still there

gobble gobble sex offender

**Comment by papycochon** [comment]
rajhastan virus

**Comment by papycochon** [comment]
rajhastan virus

**Comment by nomyTx** [comment]
> you didnt see the harrasing one tho, its still there

sex offender

**Comment by kekkodance** [comment]
**seggsfgds**

**Comment by smartfrigde** [comment]
> you didnt see the harrasing one tho, its still there

Show it then

**Comment by kekkodance** [comment]
u moaoma

**Comment by papycochon** [comment]
rajhastan uLfEK

**Comment by papycochon** [comment]
rajhastan RPpnD

**Comment by papycochon** [comment]
rajhastan vRZW5

**Comment by papycochon** [comment]
rajhastan 4Pmtk

**Comment by papycochon** [comment]
rajhastan T0k25

**Comment by papycochon** [comment]
rajhastan zt4V7

**Comment by papycochon** [comment]
rajhastan u3knQ

**Comment by papycochon** [comment]
rajhastan ltPBU

**Comment by papycochon** [comment]
rajhastan U6lq5

**Comment by papycochon** [comment]
rajhastan uiLlz

**Comment by papycochon** [comment]
rajhastan y6Zlg

**Comment by papycochon** [comment]
rajhastan 2UUcH

**Comment by papycochon** [comment]
rajhastan F73af

**Comment by papycochon** [comment]
rajhastan Dqxff

**Comment by papycochon** [comment]
rajhastan tvUqS

**Comment by papycochon** [comment]
rajhastan LAPKb

**Comment by papycochon** [comment]
rajhastan oNrIN

**Comment by papycochon** [comment]
rajhastan mo7Pz

**Comment by papycochon** [comment]
rajhastan 3bn4f

**Comment by papycochon** [comment]
rajhastan jZlsx

**Comment by papycochon** [comment]
rajhastan xfPeR

**Comment by papycochon** [comment]
rajhastan paKPJ

**Comment by papycochon** [comment]
rajhastan 2kSVh

**Comment by papycochon** [comment]
rajhastan b2Nh1

**Comment by papycochon** [comment]
rajhastan arnPJ

**Comment by papycochon** [comment]
rajhastan xEH7D

**Comment by papycochon** [comment]
rajhastan EC4MK

**Comment by papycochon** [comment]
rajhastan 1vXnM

**Comment by papycochon** [comment]
rajhastan UZi5i

**Comment by papycochon** [comment]
rajhastan kaMe9

**Comment by papycochon** [comment]
rajhastan lHanq

**Comment by papycochon** [comment]
rajhastan olmo1

**Comment by papycochon** [comment]
rajhastan orHY7

**Comment by papycochon** [comment]
rajhastan LZuck

**Comment by papycochon** [comment]
rajhastan iOBkX

**Comment by papycochon** [comment]
rajhastan K9ulV

**Comment by papycochon** [comment]
rajhastan 9YIOM

**Comment by papycochon** [comment]
rajhastan kDGF3

**Comment by papycochon** [comment]
rajhastan ZUVcz

**Comment by papycochon** [comment]
rajhastan xEYWw

**Comment by papycochon** [comment]
rajhastan zLsvr

**Comment by papycochon** [comment]
rajhastan tMbBT

**Comment by papycochon** [comment]
rajhastan PWdOl

**Comment by papycochon** [comment]
rajhastan oWz9z

**Comment by papycochon** [comment]
rajhastan DtroM

**Comment by papycochon** [comment]
rajhastan EHR0A

**Comment by papycochon** [comment]
rajhastan AT3c2

**Comment by papycochon** [comment]
rajhastan 07ykb

**Comment by papycochon** [comment]
rajhastan R4Pk2

**Comment by papycochon** [comment]
rajhastan J851W

**Comment by papycochon** [comment]
rajhastan 7O1vL

**Comment by papycochon** [comment]
rajhastan 6U0jD

**Comment by papycochon** [comment]
rajhastan fr8mf

**Comment by papycochon** [comment]
rajhastan pIi8h

**Comment by papycochon** [comment]
rajhastan 0RfqF

**Comment by papycochon** [comment]
rajhastan wWfSP

**Comment by papycochon** [comment]
rajhastan bTmfl

**Comment by papycochon** [comment]
rajhastan BQ07v

**Comment by papycochon** [comment]
rajhastan s0JdP

**Comment by papycochon** [comment]
rajhastan H63cy

**Comment by papycochon** [comment]
rajhastan yr4ue

**Comment by papycochon** [comment]
rajhastan YvA9w

**Comment by papycochon** [comment]
rajhastan 3Bb45

**Comment by papycochon** [comment]
rajhastan PmUtU

**Comment by papycochon** [comment]
rajhastan 9ztNc

**Comment by papycochon** [comment]
rajhastan M6xbV

**Comment by papycochon** [comment]
rajhastan mlCrd

**Comment by papycochon** [comment]
rajhastan tOUqw

**Comment by papycochon** [comment]
rajhastan lfCuU

**Comment by papycochon** [comment]
rajhastan 5BPSd

**Comment by papycochon** [comment]
rajhastan dQRYw

**Comment by papycochon** [comment]
rajhastan zmlLO

**Comment by papycochon** [comment]
rajhastan 0oIuv

**Comment by papycochon** [comment]
rajhastan FAvT8

**Comment by papycochon** [comment]
rajhastan tOptc

**Comment by papycochon** [comment]
rajhastan 5Lu3v

**Comment by papycochon** [comment]
rajhastan zebgz

**Comment by papycochon** [comment]
rajhastan uxpyR

**Comment by papycochon** [comment]
rajhastan yuIYV

**Comment by papycochon** [comment]
rajhastan ysWnF

**Comment by papycochon** [comment]
rajhastan CSkyV

**Comment by papycochon** [comment]
rajhastan jPsUD

**Comment by papycochon** [comment]
rajhastan O09kx

**Comment by papycochon** [comment]
rajhastan wOvoL

**Comment by papycochon** [comment]
rajhastan qorVR

**Comment by papycochon** [comment]
rajhastan FQ5yU

**Comment by papycochon** [comment]
rajhastan qHMDT

**Comment by papycochon** [comment]
rajhastan 2Cboz

**Comment by papycochon** [comment]
rajhastan lz4GS

**Comment by papycochon** [comment]
rajhastan iwhWm

**Comment by papycochon** [comment]
rajhastan wtxpB

**Comment by papycochon** [comment]
rajhastan vnIxG

**Comment by papycochon** [comment]
rajhastan S7Yh2

**Comment by papycochon** [comment]
rajhastan MHm59

**Comment by papycochon** [comment]
rajhastan YBuZx

**Comment by papycochon** [comment]
rajhastan QIFOL

**Comment by papycochon** [comment]
rajhastan pyQDi

**Comment by papycochon** [comment]
rajhastan XIG1B

**Comment by papycochon** [comment]
rajhastan zwJ8F

**Comment by papycochon** [comment]
rajhastan tJF1r

**Comment by papycochon** [comment]
rajhastan F4u92

**Comment by papycochon** [comment]
rajhastan mK3NJ

**Comment by papycochon** [comment]
rajhastan LJmlc

**Comment by papycochon** [comment]
rajhastan Iiqcs

**Comment by papycochon** [comment]
rajhastan 93bWS

**Comment by papycochon** [comment]
rajhastan xSABQ

**Comment by papycochon** [comment]
rajhastan khBez

**Comment by papycochon** [comment]
rajhastan OGFsk

**Comment by papycochon** [comment]
rajhastan D2bzp

**Comment by papycochon** [comment]
rajhastan ohv7t

**Comment by papycochon** [comment]
rajhastan ZzoSN

**Comment by papycochon** [comment]
rajhastan 4lN28

**Comment by papycochon** [comment]
rajhastan bEh1f

**Comment by papycochon** [comment]
rajhastan ftMHw

**Comment by papycochon** [comment]
rajhastan EPU7P

**Comment by papycochon** [comment]
rajhastan mxmot

**Comment by papycochon** [comment]
rajhastan HzSB7

**Comment by papycochon** [comment]
rajhastan rBULx

**Comment by papycochon** [comment]
rajhastan 707OD

**Comment by papycochon** [comment]
rajhastan KMRcX

**Comment by papycochon** [comment]
rajhastan 9NarR

**Comment by papycochon** [comment]
rajhastan Im2Vw

**Comment by papycochon** [comment]
rajhastan e4xvM

**Comment by papycochon** [comment]
rajhastan UPu6Y

**Comment by papycochon** [comment]
rajhastan DIuoT

**Comment by papycochon** [comment]
rajhastan 8iLWe

**Comment by papycochon** [comment]
rajhastan oMY6z

**Comment by papycochon** [comment]
rajhastan d0PZN

**Comment by papycochon** [comment]
rajhastan zoPSx

**Comment by papycochon** [comment]
rajhastan 2jh2G

**Comment by papycochon** [comment]
rajhastan 1mtm3

**Comment by papycochon** [comment]
rajhastan wdg0g

**Comment by papycochon** [comment]
rajhastan YFzSV

**Comment by papycochon** [comment]
rajhastan v6wrT

**Comment by papycochon** [comment]
rajhastan Wqkc3

**Comment by papycochon** [comment]
rajhastan lE9Wo

**Comment by papycochon** [comment]
rajhastan YAc3t

**Comment by papycochon** [comment]
rajhastan MgY3O

**Comment by papycochon** [comment]
rajhastan My14r

**Comment by papycochon** [comment]
rajhastan r9V39

**Comment by papycochon** [comment]
rajhastan 2lE2U

**Comment by papycochon** [comment]
rajhastan 3hQQL

**Comment by papycochon** [comment]
rajhastan Srv1Q

**Comment by papycochon** [comment]
rajhastan GSi9c

**Comment by papycochon** [comment]
rajhastan hIkMM

**Comment by papycochon** [comment]
rajhastan rKcJV

**Comment by papycochon** [comment]
rajhastan OzR7s

**Comment by papycochon** [comment]
rajhastan Vbci6

**Comment by papycochon** [comment]
rajhastan 9g12m

**Comment by papycochon** [comment]
rajhastan B2zE0

**Comment by papycochon** [comment]
rajhastan abeOv

**Comment by papycochon** [comment]
rajhastan Am41G

**Comment by papycochon** [comment]
rajhastan TBA5K

**Comment by papycochon** [comment]
rajhastan 8rIie

**Comment by papycochon** [comment]
rajhastan 6Fupp

**Comment by papycochon** [comment]
rajhastan DLb4s

**Comment by papycochon** [comment]
rajhastan D09RA

**Comment by papycochon** [comment]
rajhastan 1IPNU

**Comment by papycochon** [comment]
rajhastan sTegZ

**Comment by papycochon** [comment]
rajhastan 3cr2o

**Comment by papycochon** [comment]
rajhastan 0a9wK

**Comment by papycochon** [comment]
rajhastan eNyt8

**Comment by papycochon** [comment]
rajhastan iogl1

**Comment by papycochon** [comment]
rajhastan TlZJo

**Comment by papycochon** [comment]
rajhastan EYElu
