### ISSUE TITLE
Bug: Resolving src/client/actions via filesystems breaks bundlers

### ISSUE THREAD

**Issue by alula** [discordjs/discord.js#6681]
### Issue description

Some "smart" person decided that resolving modules statically is too spammy and replaced it with code that scans filesystem at one point: https://github.com/discordjs/discord.js/pull/6102

Therefore using discord.js with bundlers like webpack breaks d.js completely and causes very unexpected behavior, since everything is actually bundled in a single .js file, `__dirname` points to current directory and modules the code is looking for do not actually exist on the filesystem:

```
  18:18:32.925  worker    ERROR    Whoops: Error: Cannot find module './.env.example'
    at webpackContextResolve (webpack://kyoko/./.yarn/cache/discord.js-npm-13.1.0-8440b31213-90f629be62.zip/node_modules/discord.js/src/client/actions/_sync_^\.\/.*$?:109:11)
    at webpackContext (webpack://kyoko/./.yarn/cache/discord.js-npm-13.1.0-8440b31213-90f629be62.zip/node_modules/discord.js/src/client/actions/_sync_^\.\/.*$?:104:11)
    at new ActionsManager (webpack://kyoko/./.yarn/cache/discord.js-npm-13.1.0-8440b31213-90f629be62.zip/node_modules/discord.js/src/client/actions/ActionsManager.js?:13:174)
    at new Client (webpack://kyoko/./.yarn/cache/discord.js-npm-13.1.0-8440b31213-90f629be62.zip/node_modules/discord.js/src/client/Client.js?:100:20)
    at MockMonitorClient.eval (webpack://kyoko/./src/worker/index.ts?:114:24)
    at MockMonitorClient.start (webpack://kyoko/./src/worker/index.ts?:61:85)
    at eval (webpack://kyoko/./src/worker/index.ts?:147:19)
    at eval (webpack://kyoko/./src/worker/index.ts?:148:3)
    at Object../src/worker/index.ts (/home/alula/workspace/kyoko/kyoko-v4/dist/worker.js:118:1)
    at __webpack_require__ (/home/alula/workspace/kyoko/kyoko-v4/dist/worker.js:6662:42) {
  code: 'MODULE_NOT_FOUND'
}
```

The bug can be very easily resolved by reverting #6102.

### Codesample

```typescript
Not applicable
```

### discord.js version

13.1.0

### Node.js version

16.10

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by nrauschcom** [comment]
Very annoying bug, preventing my update to 13.x

**Comment by Megatank58** [comment]
> Very annoying bug, preventing my update to 13.x

discord.js no longer maintains/supports webpack versions

**Comment by 1chiSensei** [comment]
> 
> 
> > Very annoying bug, preventing my update to 13.x
> 
> discord.js no longer maintains/supports webpack versions see [#6680 (comment)](https://github.com/discordjs/discord.js/issues/6680#issuecomment-925751349)

Using a bundler can **_possibly_** reduce your code size and make it run faster.

**Comment by alula** [comment]
The biggest benefit is that it lets you avoid bloat of node_modules, which is especially helpful if you make something that you want to distribute (1 file vs sup with shitton of files).

So far this is the **only** minor issue that prevents d.js from working in webpack **node** environment (proven by making a local patch using `yarn patch` feature) and I really don't have an idea why you are so afraid of that.

**Comment by ImRodry** [comment]
The library is barely 1mb in size and making it all into one file def won’t decrease that to a point where it’s noticeable. This code using fs is much better and I don’t think we should be removing that because some people might wanna use something that is explicitly not supported by the library

**Comment by alula** [comment]
you know that not only discord.js itself is shrunk when you bundle an entire app?

**Comment by nrauschcom** [comment]
Hi there,

I don't really like the discussion in here, so I want to provide a more detailed overview on what I am (and possibly many other people are) doing with discord.js, and why this exact ticket is not just affecting a minority of users.

Honestly I missed the announcement that DJS13 is no longer supporting webpack builds. As @alula already pointed out, this one issue is currently the only one preventing DJS from working with bundlers. The code quality has barely improved by doing a file system check instead of listing all action handlers imo, but that's not my decision to make.

What bothers me is the assumption that using WebPack is not valid for Discord.js. In fact, I'm working on a server application which is communicating with two Web Apps, and only my Backend is using a Discord Integration. The whole project has >30 dependencies, the bundled application is 22MB, the node_modules folder alone would be ~95k files and 1.3GB.

Today, WebPack is not only used for the web, but to provide small and tree-shaken single file applications for easy deployment.
My application is automatically bundled and deployed in my CI Pipeline, which, in my opinion, is a very common use case.

And well, I think most of the DJS users are sticking to v11 or v12 for now, but the Discord API evolves pretty fast at the moment and I can already see a point where the switch to 13 is necessary! 

I can fully understand your point if you want to add more refactorings/features that are blocking bundlers from working, but only for the sake of this single ticket, I don't understand the decision at all.

**Comment by iCrawl** [comment]
Does something like this not exist for webpack at all?

https://www.npmjs.com/package/@rollup/plugin-dynamic-import-vars

If so, we could work around the issue by having a util function close to this without having to manually re-add all those entries and have to double check in the future.

**Comment by nrauschcom** [comment]
I think someone mentioned [webpack.context](https://webpack.js.org/guides/dependency-management/#requirecontext) (but I currently can't find the comment).

If implementing such functionality would be encouraged I'm sure we can get it done :)

**Comment by alula** [comment]
> I think someone mentioned [webpack.context](https://webpack.js.org/guides/dependency-management/#requirecontext) (but I currently can't find the comment).
> 
> If implementing such functionality would be encouraged I'm sure we can get it done :)

I think that I mentioned that on Discord, but the problem with `webpack.context` is that this approach would be webpack-specific.

**Comment by alula** [comment]
If d.js team insists on using filesystem regardless "for cleaner code", adding a separate path using `require.context` would be better than having a broken library tbh.
