### ISSUE TITLE
Unable to delete registered commands (both API and SDK)

### ISSUE THREAD

**Issue by DalderupMaurice** [discordjs/discord.js#6711]
### Issue description

1. Register a slash command
2. Try to delete it
3. Look at the error(s) (there are 2 errors from 2 different approaches, check code example below):

```
Error Number 1
command_id[NUMBER_TYPE_COERCE]: Value "ping" is not snowflake.
    at SequentialHandler.runRequest (D:\Development\bot\node_modules\@discordjs\rest\dist\lib\handlers\lib\handlers\SequentialHandler.ts:215:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at SequentialHandler.queueRequest (D:\Development\bot\node_modules\@discordjs\rest\dist\lib\handlers\lib\handlers\SequentialHandler.ts:111:11)
```

```
Error Number 2
DiscordAPIError: Invalid Form Body
command_id: Value "ping" is not snowflake.
    at RequestHandler.execute (D:\Development\bot\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RequestHandler.push (D:\Development\bot\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at ApplicationCommandManager.delete (D:\Development\bot\node_modules\discord.js\src\managers\ApplicationCommandManager.js:194:5)
[ERROR] 19:55:34 DiscordAPIError: Invalid Form Body
command_id: Value "ping" is not snowflake.
```

### Code sample

```typescript
async registerCommands(): Promise<void> {
    const rest = new REST({ version: "9" }).setToken(this.config.token);
    try {
      this.logger.info("Started refreshing application (/) commands.");

      await rest.put(
        Routes.applicationGuildCommands(
          this.config.applicationId,
          this.config.guildId
        ),
        {
          body: this.commands.mapValues((cmd) => cmd.data.toJSON())
        }
      );

      // This results in error number 1
      this.commands.mapValues((cmd) =>
        rest.delete(
          Routes.applicationGuildCommand(
            this.config.applicationId,
            this.config.guildId,
            cmd.name
          )
        )
      );

      // This variant also does not work and gives the error number 2
      this.commands.mapValues((cmd) =>
        this.client.application.commands.delete(cmd.name)
      );

      this.logger.success("Successfully reloaded application (/) commands.");
    } catch (error) {
      this.logger.error(error);
    }
  }
```

### discord.js version

13.1.0

### Node.js version

v16.10.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by thehackerboi69github** [comment]
You should delete a command by its id, not by its name.

**Comment by ImRodry** [comment]
Please use the Discord server for questions like these, the issue tracker is for bugs within the library
