### ISSUE TITLE
msg.member.voice.channel.join(); is not an function

### ISSUE THREAD

**Issue by bco2135** [discordjs/discord.js#6712]
### Issue description

I was making a music bot but this error keeps happening when I run it?

TypeError: msg.member.voice.channel.join is not a function
    at Client.<anonymous> (C:\Users\ellio\Desktop\SCP-ANNOUNCER\index.js:18:38)
    at Client.emit (node:events:394:28)
    at MessageCreateAction.handle (C:\Users\ellio\Desktop\SCP-ANNOUNCER\node_modules\discord.js\src\client\actions\MessageCreate.js:23:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\ellio\Desktop\SCP-ANNOUNCER\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\ellio\Desktop\SCP-ANNOUNCER\node_modules\discord.js\src\client\websocket\WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (C:\Users\ellio\Desktop\SCP-ANNOUNCER\node_modules\discord.js\src\client\websocket\WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (C:\Users\ellio\Desktop\SCP-ANNOUNCER\node_modules\discord.js\src\client\websocket\WebSocketShard.js:300:10)
    at WebSocket.onMessage (C:\Users\ellio\Desktop\SCP-ANNOUNCER\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (C:\Users\ellio\Desktop\SCP-ANNOUNCER\node_modules\ws\lib\websocket.js:983:20)

can anyone help?

### Code sample

```typescript
const Discord = require('discord.js');
const config = require('./data/Config/config.json');
const client = new Discord.Client({ intents:['GUILDS','GUILD_EMOJIS_AND_STICKERS','GUILD_MESSAGES','GUILD_MESSAGE_REACTIONS','GUILD_MEMBERS','GUILD_VOICE_STATES'] });

client.on('ready', () => {
    console.log(`Logged in as ${client.user.tag}`);

    client.user.setActivity('SCP Secret Laboratory');
})

client.on('messageCreate', msg => {
    if(msg.author.bot) return;
    
    if(msg.content.toLowerCase() === config.prefex + "join_voice_channel") {
        if(msg.member.roles.cache.has('892148183239639120')) {
            

            msg.member.voice.channel.join();
        }
    }
})

client.login(config.token);
```

### discord.js version

13.1.0

### Node.js version

v16.6.1

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by ImRodry** [comment]
Voice-related methods have been moved over to [@discordjs/voice](https://github.com/discordjs/voice) so you can no longer join channels like you used to in v12. Please ask your questions on the Discord server and keep the issue tracker for issues related to the library only. Thanks
