### ISSUE TITLE
Discord.js@13 Cannot find module 'timers/promises'

### ISSUE THREAD

**Issue by yassine955** [discordjs/discord.js#6807]
### Feature

Everything works locally fine! But when i start it on my vps i get this error

```
 Error: Cannot find module 'timers/promises'
0|ServantOfAllah  | Require stack:
0|ServantOfAllah  | - /root/DISCORD/Servant-Of-Allah-Discord-Bot/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js
0|ServantOfAllah  | - /root/DISCORD/Servant-Of-Allah-Discord-Bot/node_modules/@discordjs/rest/dist/lib/RequestManager.js
0|ServantOfAllah  | - /root/DISCORD/Servant-Of-Allah-Discord-Bot/node_modules/@discordjs/rest/dist/index.js
0|ServantOfAllah  | - /root/DISCORD/Servant-Of-Allah-Discord-Bot/dist/client/BotClient.js
0|ServantOfAllah  | - /root/DISCORD/Servant-Of-Allah-Discord-Bot/dist/Bot.js
0|ServantOfAllah  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
0|ServantOfAllah  |     at Module.Hook._require.Module.require (/usr/local/share/.config/yarn/global/node_modules/require-in-the-middle/index.js:61:29)
0|ServantOfAllah  |     at require (internal/modules/cjs/helpers.js:92:18)
0|ServantOfAllah  |     at Object.<anonymous> (/root/DISCORD/Servant-Of-Allah-Discord-Bot/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:6:20)
0|ServantOfAllah  |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
0|ServantOfAllah  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
0|ServantOfAllah  |     at Module.load (internal/modules/cjs/loader.js:937:32)
0|ServantOfAllah  |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
0|ServantOfAllah  |     at Module.require (internal/modules/cjs/loader.js:961:19)
0|ServantOfAllah  |     at Module.Hook._require.Module.require (/usr/local/share/.config/yarn/global/node_modules/require-in-the-middle/index.js:80:39) {
0|ServantOfAllah  |   code: 'MODULE_NOT_FOUND',
0|ServantOfAllah  |   requireStack: [
0|ServantOfAllah  |     '/root/DISCORD/Servant-Of-Allah-Discord-Bot/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js',
0|ServantOfAllah  |     '/root/DISCORD/Servant-Of-Allah-Discord-Bot/node_modules/@discordjs/rest/dist/lib/RequestManager.js',
0|ServantOfAllah  |     '/root/DISCORD/Servant-Of-Allah-Discord-Bot/node_modules/@discordjs/rest/dist/index.js',
0|ServantOfAllah  |     '/root/DISCORD/Servant-Of-Allah-Discord-Bot/dist/client/BotClient.js',
0|ServantOfAllah  |     '/root/DISCORD/Servant-Of-Allah-Discord-Bot/dist/Bot.js'
0|ServantOfAllah  |   ]
0|ServantOfAllah  | }
```

### Ideal solution or implementation

I want to know what the problem is

**Comment by SuperchupuDev** [comment]
Update to Node 16

**Comment by SuperchupuDev** [comment]
> > Update to Node 16, not a discord.js issue
> 
> I updated to node 16 still problem

doesn't look like it, log `process.version` or just do node -v
