### ISSUE TITLE
Problem with checks for roles and permissions and other properties of a member

### ISSUE THREAD

**Issue by xXLoloGameplayXx** [discordjs/discord.js#7167]
### Issue description

1. Get the data of a member of any guild.
2. Registers the highest role of the member in the console and looks for the rawPosition property. (member.roles.highest.rawPosition)
3. Look at the first error granted.

### Code sample

```typescript
// Remember to have a valid client instance.

client.on("messageCreate", async (message) => {

  // The code is very simplified

  const member = await message.guild.members.fetch(message.author.id);

  console.log(member.roles.highest.rawPosition);

}):
```

### discord.js version

13.5.0

### Node.js version

v16.13.1

### Operating system

Ubuntu Server 18.04 LTS

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_EMOJIS_AND_STICKERS, GUILD_INVITES, GUILD_MESSAGES

**Comment by Jiralite** [comment]
What's the error?

**Comment by xXLoloGameplayXx** [comment]
> What's the error?
(node:28874) Warning: Accessing non-existent property 'Symbol(Symbol.hasInstance)' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Function.discordSort (/app/filobot/node_modules/discord.js/src/util/Util.js:487:47)
    at Guild._sortedRoles (/app/filobot/node_modules/discord.js/src/structures/Guild.js:1408:17)
    at Role.get position [as position] (/app/filobot/node_modules/discord.js/src/structures/Role.js:220:31)
    at RoleManager.comparePositions (/app/filobot/node_modules/discord.js/src/managers/RoleManager.js:277:23)
    at Role.comparePositionTo (/app/filobot/node_modules/discord.js/src/structures/Role.js:231:29)
    at /app/filobot/node_modules/discord.js/src/managers/GuildMemberRoleManager.js:78:52
    at Map.reduce (/app/filobot/node_modules/@discordjs/collection/dist/index.js:1:3544)
    at GuildMemberRoleManager.get highest [as highest] (/app/filobot/node_modules/discord.js/src/managers/GuildMemberRoleManager.js:78:23)
    at eval (eval at exports.run (/app/filobot/interactions/commands/developer/eval.js:28:20), <anonymous>:1:14)
    at Object.exports.run (/app/filobot/interactions/commands/developer/eval.js:28:20)
    at module.exports (/app/filobot/events/interactionCreate.js:373:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by xXLoloGameplayXx** [comment]
I am also getting this issue since the last update:
```bash
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Right-hand side of 'instanceof' is not callable
    at Function.discordSort (/app/filobot/node_modules/discord.js/src/util/Util.js:487:47)
    at Guild._sortedRoles (/app/filobot/node_modules/discord.js/src/structures/Guild.js:1408:17)
    at Role.get position [as position] (/app/filobot/node_modules/discord.js/src/structures/Role.js:220:31)
    at RoleManager.comparePositions (/app/filobot/node_modules/discord.js/src/managers/RoleManager.js:277:23)
    at Role.comparePositionTo (/app/filobot/node_modules/discord.js/src/structures/Role.js:231:29)
    at /app/filobot/node_modules/discord.js/src/managers/GuildMemberRoleManager.js:78:52
    at Map.reduce (/app/filobot/node_modules/@discordjs/collection/dist/index.js:1:3544)
    at GuildMemberRoleManager.get highest [as highest] (/app/filobot/node_modules/discord.js/src/managers/GuildMemberRoleManager.js:78:23)
    at processQueue (/app/filobot/core/roles/index.js:24:29)
```

Should I open a new issue to report it?

**Comment by DTrombett** [comment]
Uh, this seems a circular dependency problem, you can update the title/description but no need to create a new issue.

**Comment by xXLoloGameplayXx** [comment]
> Uh, this seems a circular dependency problem, you can update the title/description but no need to create a new issue.

What should I put as a title? (I'm still a bit lost on GitHub)

**Comment by kyranet** [comment]
I cannot reproduce this on v13.5.0, `message.member.roles.highest.rawPosition` returns a value just fine, and the file is already using a circular patch, which is done by requiring files *after* module.exports, as seen before:

https://github.com/discordjs/discord.js/blob/780b7ed39f173a77fd9eae396133980826926906/src/util/Util.js#L608-L611

Are you using a bundler or something? Some of them re-order the imports, which causes circular, and subsequently this issue.

**Comment by xXLoloGameplayXx** [comment]
> I cannot reproduce this on v13.5.0, `message.member.roles.highest.rawPosition` returns a value just fine, and the file is already using a circular patch, which is done by requiring files _after_ module.exports, as seen below:
> 
> https://github.com/discordjs/discord.js/blob/780b7ed39f173a77fd9eae396133980826926906/src/util/Util.js#L608-L611
> 
> Are you using a bundler or something? Some of them re-order the imports, which causes circulars to happen, and subsequently this issue.

Indeed, that seems to be the scenario. Thank you.
