### ISSUE TITLE
Can't attach image to a message

### ISSUE THREAD

**Issue by gamernitro999** [discordjs/discord.js#7187]
### Issue description

when i want to attach an image the way whowed in the guide for image manipulation
i follow everything but when i execute my command that send the message (/user) it crash
with this error : 

(if you want the repo to check all the code : https://github.com/gamernitro999/djs13-bot) and commands/user.js

```
C:\Users\myusername\Dev\Discord\Bot\Nto-Bot-DJS13\node_modules\.pnpm\discord.js@13.5.0\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown interaction
    at RequestHandler.execute (C:\Users\myusername\Dev\Discord\Bot\Nto-Bot-DJS13\node_modules\.pnpm\discord.js@13.5.0\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\myusername\Dev\Discord\Bot\Nto-Bot-DJS13\node_modules\.pnpm\discord.js@13.5.0\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (C:\Users\myusername\Dev\Discord\Bot\Nto-Bot-DJS13\node_modules\.pnpm\discord.js@13.5.0\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:99:5) {
  method: 'post',
  path: '/interactions/928258380668235806/aW50ZXJhY3Rpb246OTI4MjU4MzgwNjY4MjM1ODA2OlVCazJkc2MxNXFJRVVheDF6VFJNUDlaYXRHT1Q4Yk9XSlFFYUw4aWlNdURPTHZsRkRnMmpVU3dYTm9EQUx4RzZEaHVMQjVzR0xxZDNtZGYzUjFtYnVNVVFxdTREV25VWGNBdFJqRXNEWFRpTk9GM003RHFvOGtrQTVjUzJERzR6/callback',
  code: 10062,
  httpStatus: 404,
  requestData: {
    json: {
      type: 4,
      data: {
        content: undefined,
        tts: false,
        nonce: undefined,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: [ { id: '0', description: undefined } ],
        sticker_ids: undefined
      }
    },
    files: [
      {
        attachment: Buffer(284775) [Uint8Array] [
          137,  80,  78,  71,  13,  10,  26,  10,   0,   0,   0,  13,
           73,  72,  68,  82,   0,   0,   2, 188,   0,   0,   0, 250,
            8,   6,   0,   0,   0,  67,  36, 148,  27,   0,   0,   0,
            6,  98,  75,  71,  68,   0, 255,   0, 255,   0, 255, 160,
          189, 167, 147,   0,   0,  32,   0,  73,  68,  65,  84, 120,
          156, 172, 189, 121, 172, 103,  91, 118, 215, 247,  89, 251,
          156, 223, 112, 239, 173, 186,  53, 188, 122, 253, 230, 238,
          126, 253, 122, 178, 219, 110, 219, 109,  26, 108, 108, 183,
            9, 224, 196, 132,
          ... 284675 more items
        ],
        name: 'profile-image.png',
        file: Buffer(284775) [Uint8Array] [
          137,  80,  78,  71,  13,  10,  26,  10,   0,   0,   0,  13,
           73,  72,  68,  82,   0,   0,   2, 188,   0,   0,   0, 250,
            8,   6,   0,   0,   0,  67,  36, 148,  27,   0,   0,   0,
            6,  98,  75,  71,  68,   0, 255,   0, 255,   0, 255, 160,
          189, 167, 147,   0,   0,  32,   0,  73,  68,  65,  84, 120,
          156, 172, 189, 121, 172, 103,  91, 118, 215, 247,  89, 251,
          156, 223, 112, 239, 173, 186,  53, 188, 122, 253, 230, 238,
          126, 253, 122, 178, 219, 110, 219, 109,  26, 108, 108, 183,
            9, 224, 196, 132,
          ... 284675 more items
        ]
      }
    ]
  }
}
 ELIFECYCLE  Command failed with exit code 1.
```

### discord.js version

13.5.0

### Node.js version

16.13.1

### Operating system

Windows 10 build 19044.14.15

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GUILDS

**Comment by ImRodry** [comment]
This is not a library bug and the title is not related to the issue you're experiencing either. The reason you're getting this error is that you're taking too long to respond to the interaction (note that you have up to 3 seconds to reply, unless you defer, which gives you 15 minutes). For questions like this, you should use the [Discord server](discord.gg/djs) instead

**Comment by gamernitro999** [comment]
> 

ok thank you for your response
