### ISSUE TITLE
Message.Delete() Not Working

### ISSUE THREAD

**Issue by TriumphantCreatorX** [discordjs/discord.js#7275]
### Which package is this bug report for?

discord.js

### Issue description

Hello! The discord.js function, [`message.delete()`](https://discord.js.org/#/docs/discord.js/stable/class/Message?scrollTo=delete), has not been working for my Discord bot.
I use a server hosting platform called PebbleHost, and my main script is called `bot.js`, which is where I am having an issue.

`✅` The bot has [`administrator`](https://discord.js.org/#/docs/discord.js/stable/class/Permissions?scrollTo=s-FLAGS) permissions enabled.
`✅` `Message.delete()` has worked before with this bot.

If you look below at the Code Sample, this is where I keep getting the error.
Whenever I try to execute the function, `message.delete()`, in that section of code my entire server shuts down. Here is the usual response that I get in the console:
```
[Bot] /bot.js:1359
[Bot] msg.delete()
[Bot] ^
[Bot] TypeError: msg.delete is not a function
[Bot] at Timeout._onTimeout (/bot.js:1359:39)
[Bot] at listOnTimeout (internal/timers.js:549:17)
[Bot] at processTimers (internal/timers.js:492:7)
[Bot] npm ERR! code ELIFECYCLE
[Bot] npm ERR! errno 1
[Bot] npm ERR! triumph-co@0.0.1 start: `node .`
[Bot] npm ERR! Exit status 1
[Bot] npm ERR! 
[Bot] npm ERR! Failed at the triumph-co@0.0.1 start script.
[Bot] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[Bot] npm ERR! A complete log of this run can be found in:
[Bot] npm ERR!     /tmp/npm/_logs/[LogTimestamp]-debug.log
```
It would be very helpful if this gets fixed soon! (I might not be able to read replies quickly, but I will read them as soon as possible.)
Thanks,
@TriumphantCreatorX

### Code sample

```typescript
// Message object from the message that was sent (this works just fine).
.then(msg => {
    console.log("[Test] Message ID: " + String(msg.id)); // This works.
    setTimeout(function () {
        msg.delete() // > TypeError: msg.delete is not a function (Code: ELIFECYCLE)
            .then(msg => console.log("[Test] Message deleted!"))
            .catch(err => console.error(err)));
    }, 10000) // 10 seconds.
```

### Package version

^12.5.1

### Node.js version

12.16.3

### Operating system

PebbleHost

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

USER, CHANNEL, GUILD_MEMBER, MESSAGE

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_BANS, GUILD_INTEGRATIONS, GUILD_INVITES, GUILD_PRESENCES, GUILD_MESSAGES, DIRECT_MESSAGES

**Comment by ImRodry** [comment]
We do not offer support for v12 of the library nor is this an issue with the library itself. The code sample provided is not enough to reproduce the issue as it starts with a .then with no previous context. For questions like these, please use the [Discord server](discord.gg/djs) and update to v13 of the library as soon as possible. You can find the migrating guide [here](https://discordjs.guide/additional-info/changes-in-v13.html)

**Comment by TriumphantCreatorX** [comment]
Here is the message object:
```
s4d.client.api.channels([ Channel ID ]).messages.post({ [Message Objects (JSON)] }); // This function operates well and sends a message.
```
I updated Discord.JS to version 13.6.0 and updated my Node version to 17.1.0, but my server still crashes every time I run the `message.delete()` function. Is what I am doing correct?

**Comment by ImRodry** [comment]
You're calling the API directly which is not only unsupported but it also does not yield a Message object, therefore you can't use djs functions with it. This is not an issue with the library, it's an issue with your own implementation of the code

**Comment by TriumphantCreatorX** [comment]
That is odd, because `message.delete()` worked before with that API call, just for another project that I had (in the `bot.js` file). I will try to use a Discord.JS function instead. Thank you for your help!

**Comment by ImRodry** [comment]
I can absolutely guarantee you it did not work with the raw API call, the client.api property is private for a reason. Please close this now
