### ISSUE TITLE
Voice channel playback not working

### ISSUE THREAD

**Issue by noryonkr** [discordjs/discord.js#7283]
### Which package is this bug report for?

voice

### Issue description

1. Play text as voice channel as tts
2. Type the command !tts this tts
3. doesn't work
4. Error Log
```powershell
AbortError: The operation was aborted
    at abortListener (node:events:838:14)
    at AbortSignal.<anonymous> (node:events:874:47)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:569:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:511:26)
    at abortSignal (node:internal/abort_controller:290:10)
    at AbortController.abort (node:internal/abort_controller:321:5)
    at Timeout.<anonymous> (C:\Users\Nam\Desktop\HN\node_modules\@discordjs\voice\dist\index.js:9:420)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7) {
  code: 'ABORT_ERR',
  [cause]: DOMException [AbortError]: This operation was aborted
      at AbortController.abort (node:internal/abort_controller:319:18)
      at Timeout.<anonymous> (C:\Users\Nam\Desktop\HN\node_modules\@discordjs\voice\dist\index.js:9:420)
      at listOnTimeout (node:internal/timers:568:17)
      at processTimers (node:internal/timers:510:7)
}
```

### Code sample

```typescript
const stream = tts.getVoiceStream(`${args.join(' ')}`);
const audioResource = createAudioResource(stream);
if(!voiceConnection || voiceConnection?.status === VoiceConnectionStatus.Disconnected){
    voiceConnection = joinVoiceChannel({
        channelId: message.member.voice.channelId,
        guildId: message.guildId,
        adapterCreator: message.guild.voiceAdapterCreator,
    });
    voiceConnection=await entersState(voiceConnection, VoiceConnectionStatus.Connecting, 5_000);
}

if(voiceConnection.status === VoiceConnectionStatus.Connected){
    voiceConnection.subscribe(audioPlayer);
    audioPlayer.play(audioResource);
}
```

### Package version

13

### Node.js version

17

### Operating system

windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

CHANNEL

### Which gateway intents are you subscribing to?

GUILD_MEMBERS, GUILD_VOICE_STATES, GUILD_PRESENCES, GUILD_MESSAGES, GUILD_MESSAGE_TYPING, DIRECT_MESSAGE_REACTIONS

**Comment by amishshah** [comment]
This won’t work since you’re first waiting for the connection to enter the connecting state, then immediately after you check to see if it’s in the ready state.

You need to allow some time for it to enter the ready state. Please see the examples on how to do this.
