### ISSUE TITLE
Can't start bot with CHANNEL partial

### ISSUE THREAD

**Issue by Raiden-Ei** [discordjs/discord.js#7345]
### Which package is this bug report for?

discord.js

### Issue description

1. Install latest development version of discord.js
2. Just run a bot with `CHANNEL` partial

### Code sample

```typescript
const { Client, Intents } = require('discord.js');
const client = new Client({
  intents: [Intents.FLAGS.GUILD, Intents.FLAGS.GUILD_MESSAGES],
  partials: ['CHANNEL'],
});
client.login('token');
```

```log
TypeError: Cannot set property createdTimestamp of [object Object] which has only a getter
    at ThreadChannel._patch (/home/anonymous/bot/node_modules/discord.js/src/structures/ThreadChannel.js:111:31)
    at new ThreadChannel (/home/anonymous/bot/node_modules/discord.js/src/structures/ThreadChannel.js:43:20)
    at Function.create (/home/anonymous/bot/node_modules/discord.js/src/structures/Channel.js:242:23)
    at ChannelManager._add (/home/anonymous/bot/node_modules/discord.js/src/managers/ChannelManager.js:47:29)
    at Guild._patch (/home/anonymous/bot/node_modules/discord.js/src/structures/Guild.js:387:30)
    at Object.module.exports [as GUILD_CREATE] (/home/anonymous/bot/node_modules/discord.js/src/client/websocket/handlers/GUILD_CREATE.js:10:13)
    at WebSocketManager.handlePacket (/home/anonymous/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/home/anonymous/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/anonymous/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/anonymous/bot/node_modules/ws/lib/event-target.js:199:18)
```

### Package version

14.0.0-dev b6402723c31bed3c49f8b8cde873b65b9f373fd7

### Node.js version

17.4.0

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

CHANNEL

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES

### I have tested this issue on a development release

b6402723c31bed3c49f8b8cde873b65b9f373fd7

**Comment by suneettipirneni** [comment]
Note: Caused by 9a1623425ae2d69f5c16f0096af4951ff5096e80

**Comment by suneettipirneni** [comment]
To clarify this isn't because of the `CHANNEL` partial, it's just a bug for any thread creations.
