### ISSUE TITLE
Duplicating shards for unknown reason + ERR_IPC_CHANNEL_CLOSED

### ISSUE THREAD

**Issue by AlexandreDRFT** [discordjs/discord.js#7355]
### Which package is this bug report for?

discord.js

### Issue description

From the 11th of January my djs bot randomly duplicates shards when I had changed nothing in my code.
It happened multiple times last night (during the Discord outage) and a shard has been tripled this time.
In the meantime I've updated from djs 13.3.1 to 13.6.0 but it hasn't changed anything as expected.
It seems like one of the shards dies and ShardingManager starts another shard in its place, but the zombie shard is still up and receiving/sending messages, so it doubles everything.

One way to know it's happening is the zombie shard starts throws ERR_IPC_CHANNEL_CLOSED when calling client.shard.broadcastEval(), though it successfully executes the code inside the broadcastEval() (see code sample).

```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:371:5)
    at process.target.send (node:internal/child_process:721:16)
    at /root/eunseo-bot/node_modules/discord.js/src/sharding/ShardClientUtil.js:85:17
    at new Promise (<anonymous>)
    at ShardClientUtil.send (/root/eunseo-bot/node_modules/discord.js/src/sharding/ShardClientUtil.js:83:12)
    at /root/eunseo-bot/node_modules/discord.js/src/sharding/ShardClientUtil.js:154:12
    at new Promise (<anonymous>)
    at ShardClientUtil.broadcastEval (/root/eunseo-bot/node_modules/discord.js/src/sharding/ShardClientUtil.js:138:12)
    at Function.sendToChannel (/root/eunseo-bot/built/channel.js:27:26)
    at /root/eunseo-bot/built/commands/accept.js:61:71 {
  code: 'ERR_IPC_CHANNEL_CLOSED'
```

After encountering it the first time I've setup a mutex to avoid running the same command twice in a short amount of time, but somehow it bypasses that as well (I can include the code but I don't think it's really relevant).

When detecting a zombie shard that throws ERR_IPC_CHANNEL_CLOSED at each message, I tried to process.kill(0) it, but this just duplicates the zombie shard, so there are 3 bugged shards handling the same servers after that.

I tried really hard but haven't been able to repro it in my debug environment, it only happens in production for now. I haven't been able to pinpoint the culprit but it's likely something in ShardManager ? I've tried to reproduce with just calling process.kill(0) on a normal shard but it does not duplicate, so I'm guessing it only works on zombie shards and I haven't be able to create one myself.

If anyone has an idea on what could be causing it ? I guess that it's probably from my code if other bots haven't been subject to the same bug. A lot of my users have been using this issue to duplicate items etc and others have been losing a lot of the bot's currency by double-paying for items.

### Code sample

```typescript
//index.ts
let sharder : ShardingManager;
sharder = new ShardingManager("built/bot.js", {
		// will create around 8 shards currently on my bot
		token: token
	});
sharder.on("shardCreate", shard => {
    shard.on("ready", () => {
        // Sending the data to the shard.
        shard.send({type: "shardId", data: {shardId: shard.id}});
    });
});
sharder.spawn();

//channel.ts (on a shard)
client.shard.broadcastEval(async (c, { channelId, msg_text }) => {
                const channel = c.channels.cache.get(channelId);
                if (channel) {
                    await (channel as TextChannel).send(msg_text).catch((err) => {});
                    return true;
                }
                return false;
            }, { context: { channelId: channelID, msg_text: msg_text } })
                .catch((err) => {
                    if (!err.name.includes("SHARDING_IN_PROCESS")) {
                        console.log(err) //-> will throw ERR_IPC_CHANNEL_CLOSED on a zombie shard
                        process.kill(0) //-> will create a second zombie, tripling all commands 
                    }
                });

//On the rest of the code pretty much every exception is properly handled in a catch.
//Sometimes something will crash the shard but before that it just restarted as expected.
```

### Package version

Happened on djs 13.3.1 AND 13.6.0

### Node.js version

16.8.0

### Operating system

Centos 8

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

CHANNEL

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MESSAGES, DIRECT_MESSAGES

### I have tested this issue on a development release

Nope

**Comment by AlexandreDRFT** [comment]
For people with the same issue, I was able to find a workaround by switching to worker threads in the sharding configuration.
Just add "mode": "worker" :
```
const sharder = new ShardingManager(BOT_FILE_PATH, { 
	token: token,
	mode: "worker"
});
```
and this fixed the issue in my bot.

The issue only happens when using the default mode 'process' that seems to have some issues killing zombie child processes.
