### ISSUE TITLE
Handle 500 err for POST

### ISSUE THREAD

**Issue by Aergonus** [discordjs/discord.js#7429]
### Which package is this bug report for?

rest

### Issue description

Run discord client and try to POST to channel. On reconnecting, if POST and 500 is uncaught it will abort.
This is a long running task that posts to discord continuously. It failed on a message and stopped

```
/home/me/scripts/discord/node_modules/discord.js/src/rest/RequestHandler.js:357
        throw new HTTPError(res.statusText, res.constructor.name, res.status, request);
              ^

Response: Internal Server Error
    at RequestHandler.execute (/home/me/scripts/discord/node_modules/discord.js/src/rest/RequestHandler.js:357:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/me/scripts/discord/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async TextChannel.send (/home/me/scripts/discord/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:175:15) {
  code: 500,
  method: 'post',
  path: '/channels/94SNIP8783/messages',
  requestData: {
    json: {
      content: 'Simple message',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
```

### Code sample

```typescript
Straight from tutorial without any extra handlers


import { Client, Intents } from 'discord.js'
const bot = new Client({ intents: [
        Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MEMBERS, Intents.FLAGS.GUILD_MESSAGES
]});
var eventChannel;
const EVENT_CHANNEL_ID = '94SNIP8783';
bot.once('ready', c => {
        console.log(`Ready! Logged in as ${c.user.tag}`);
        eventChannel = bot.channels.cache.get(EVENT_CHANNEL_ID);
});

bot.login(DC_TOKEN);

let EVENT_CONSTANT = 'EVENT_CONSTANT'
function postChat(record) {
        if (record == null) {
                console.log("Post failed")
        } else {
                channelCali.send(`<@&9ROLESNIP777>\n${record}`)
        }
}
bot.on(EVENT_CONSTANT, eventMsg => {postChat(eventMsg)});

```

Some other async function calls
`bot.emit(EVENT_CONSTANT, message)`
```


### Package version

npm list scripts@1.0.0 /home/me/scripts/discord ├── discord.js@13.6.0 ├── nodemon@2.0.15 └── request@2.88.2

### Node.js version

$ node --version v17.4.0

### Operating system

ChromeOS

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials, Channel, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMessages

### I have tested this issue on a development release

@13.6.0

**Comment by KhafraDev** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

**Comment by Aergonus** [comment]
Normal discord.js seems to reconnect pretty well so I figured retry logic for message posts would be a feature.
