### ISSUE TITLE
Invite.createInvite failing when specifying a targetUser

### ISSUE THREAD

**Issue by c-shimmer** [discordjs/discord.js#7675]
### Which package is this bug report for?

discord.js

### Issue description

The following code seems to be causing an error within discord.js.

### Code sample

```typescript
Sample code:

const myStageChannel: StageChannel = /* ... */;
const myUser: User = await guild.members.fetch({user: myUserId});
const channelInvite: Invite = await myStageChannel.createInvite({
    targetUser: myUser
});
```

Corresponding error stack:
```
DiscordAPIError: Invalid Form Body
target_user_id: Invalid target user id
    at RequestHandler.execute (/REDACTED/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RequestHandler.push (/REDACTED/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at GuildInviteManager.create (/REDACTED/node_modules/discord.js/src/managers/GuildInviteManager.js:185:20)
    at DiscordBot.setupStageChannel (/REDACTED/discord-bot/src/discord-bot.ts:79:53)
    at /REDACTED/discord-bot/src/index.ts:68:31
```

The failing code in question seems to be the following:

`node_modules/discord.js/src/managers/GuildInviteManager.js`
```
**
   * Create an invite to the guild from the provided channel.
   * @param {GuildInvitableChannelResolvable} channel The options for creating the invite from a channel.
   * @param {CreateInviteOptions} [options={}] The options for creating the invite from a channel.
   * @returns {Promise<Invite>}
   * @example
   * // Create an invite to a selected channel
   * guild.invites.create('599942732013764608')
   *   .then(console.log)
   *   .catch(console.error);
   */
  async create(
    channel,
    { temporary = false, maxAge = 86400, maxUses = 0, unique, targetUser, targetApplication, targetType, reason } = {},
  ) {
    const id = this.guild.channels.resolveId(channel);
    if (!id) throw new Error('GUILD_CHANNEL_RESOLVE');

    const invite = await this.client.api.channels(id).invites.post({
      data: {
        temporary,
        max_age: maxAge,
        max_uses: maxUses,
        unique,
        target_user_id: this.client.users.resolveId(targetUser),  // <--- HERE
        target_application_id: targetApplication?.id ?? targetApplication?.applicationId ?? targetApplication,
        target_type: targetType,
      },
      reason,
    });
    return new Invite(this.client, invite);
  }
```
```


### Package version

13.6.0

### Node.js version

17.4.0

### Operating system

macOS 11.6.3 (20G415)

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildInvites, GuildVoiceStates, GuildMessages

### I have tested this issue on a development release

_No response_

**Comment by imranbarbhuiya** [comment]
If  I'm not wrong then `targetUser` is only required when  `targetType` is 1. Means u need to provide `targetType: 1`.

**Comment by advaith1** [comment]
Target user is only for creating an invite to a specific user's stream in a voice channel. It does not apply to stage channels, since they don't have streams.
