### ISSUE TITLE
discordjs command builder - setChoices and sapphire/shapeshift don't like each other

### ISSUE THREAD

**Issue by UserUNP** [discordjs/discord.js#7769]
### Which package is this bug report for?

builders

### Issue description

Steps to reproduce the error.
1. use discord.js@dev + @discordjs/builders@dev
2. make a basic Client
3. use the slash command builder to make a basic command with options and multiple choices to choose from
4. should give out a CombinedPropertyError: Received one or more errors
5. stringify the error object to look at the entire error

### Code sample

```typescript
const discord = require("discord.js");
const client = new discord.Client({intents: [discord.IntentsBitField.Flags.Guilds]});
const { SlashCommandBuilder } = require('@discordjs/builders');

commands = [
	new SlashCommandBuilder().setName("test")
		.setDescription("test dummy command")
		.addStringOption(option => {
			option.setRequired(true)
				.setName("input")
				.setChoices([
					{ name: "123", value: "choice1" },
					{ name: "456", value: "choice2" },
					{ name: "789", value: "choice3" }
				]);
			return option;
		})
]

client.on("interactionCreate", async (inter)=>{
        if(inter.isCommand()) {
                await inter.deferReply({ ephemeral: true });
                if(inter.commandName === "test") {
			inter.editReply(`${inter.options.getString("input")}`)
                }
        }
});


rest.put(Routes.applicationGuildCommands(process.env.CLIENTID, guild), { body: commands.map(cmd => cmd.json) })
.then(() => console.log(logOrigin, 'Successfully registered application commands.\n'))
.catch(err=>{throw err});

client.on("ready", () => {
	console.log("bot ready")
})

client.login("token")
```

### Package version

discord.js@14.0.0-dev.1649505803-3c0bbac

### Node.js version

v17.4.0

### Operating system

Xubuntu (or just Ubuntu)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds

### I have tested this issue on a development release

3c0bbac

**Comment by vladfrangu** [comment]
And what's the error?

**Comment by UserUNP** [comment]
```
/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@sapphire/shapeshift/dist/index.js:61
    throw this.error;
    ^

CombinedPropertyError: Received one or more errors
    at ArrayValidator.handle (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@sapphire/shapeshift/dist/index.js:400:70)
    at ArrayValidator.parse (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@sapphire/shapeshift/dist/index.js:114:88)
    at MixedClass.setChoices (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@discordjs/builders/dist/index.js:1102:22)
    at /home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/test.js:13:6
    at MixedClass._sharedAddOptionMethod (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@discordjs/builders/dist/index.js:1293:50)
    at MixedClass.addStringOption (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@discordjs/builders/dist/index.js:1282:17)
    at Object.<anonymous> (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/test.js:10:4)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32) {
  errors: [
    [
      0,
      CombinedPropertyError: Received one or more errors
          at ObjectValidator.handleIgnoreStrategy (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@sapphire/shapeshift/dist/index.js:973:66)
          at ObjectValidator.handleStrategy (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@sapphire/shapeshift/dist/index.js:907:47)
          at ObjectValidator.handle (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@sapphire/shapeshift/dist/index.js:951:17)
          at ObjectValidator.run (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@sapphire/shapeshift/dist/index.js:103:23)
          at ArrayValidator.handle (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@sapphire/shapeshift/dist/index.js:394:37)
          at ArrayValidator.parse (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@sapphire/shapeshift/dist/index.js:114:88)
          at MixedClass.setChoices (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@discordjs/builders/dist/index.js:1102:22)
          at /home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/test.js:13:6
          at MixedClass._sharedAddOptionMethod (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@discordjs/builders/dist/index.js:1293:50)
          at MixedClass.addStringOption (/home/userunp/Desktop/code-stuff/javascript/discord-bots/loopef/node_modules/@discordjs/builders/dist/index.js:1282:17) {
        errors: [
          [ 'value', [CombinedError] ],
          [ 'name', [MissingPropertyError] ]
        ]
      }
    ]
  ]
}

Node.js v17.4.0
```

**Comment by vladfrangu** [comment]
Yeah thats because right now builders expect `.set*()` calls to be in the format of `.set*({}, {})` instead of passing an array... I don't know if there's any PR reverting that or if there will be, but for now that's the fix

**Comment by UserUNP** [comment]
oh, okay
so it'll change in the future to be arrays ?

**Comment by vladfrangu** [comment]
> edit: what should the second object have ?

What the first one should, aka name and value


> so it'll change in the future to be arrays ?

Not 100% sure we'll revert back to it so I don't want to say something that may not be true

**Comment by UserUNP** [comment]
alright, thanks :^)

**Comment by suneettipirneni** [comment]
The PR to allow only arrays in builders is here:

- https://github.com/discordjs/discord.js/pull/7759
