### ISSUE TITLE
"entityMetadata" for "GuildScheduledEvent" type is missing "null" when creating an event with "GUILD_VOICE"

### ISSUE THREAD

**Issue by mrjackyliang** [discordjs/discord.js#7907]
### Which package is this bug report for?

discord.js

### Issue description

The `null` type is missing, causing `discord.js` to crash.

<img width="901" alt="Screen Shot 2022-05-10 at 3 14 26 PM" src="https://user-images.githubusercontent.com/9779803/167705211-46eb0c92-660a-477a-8359-2434533c3da0.png">
<img width="346" alt="Screen Shot 2022-05-10 at 3 17 23 PM" src="https://user-images.githubusercontent.com/9779803/167705419-31ba0788-1ca3-48cf-93b9-34902660cd8a.png">

### Code sample

```typescript
discordClient.on('guildScheduledEventCreate', (event) => {
    console.log('=======================================');
    console.log('creator', event.creator);
    console.log('channel', event.channel);
    console.log('name', event.name);
    console.log('description', event.description);
    console.log('scheduledStartAt', event.scheduledStartAt);
    console.log('scheduledEndAt', event.scheduledEndAt);
    console.log('status', event.status);
    console.log('entityType', event.entityType);
    console.log('entityMetadata', event.entityMetadata);
    console.log('=======================================');
  });
```

### Package version

13.6.0

### Node.js version

16.13.2

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessages, GuildScheduledEvents

**Comment by mrjackyliang** [comment]
<img width="305" alt="Screen Shot 2022-05-10 at 3 22 33 PM" src="https://user-images.githubusercontent.com/9779803/167706171-b4dd9ede-b975-4889-bbb3-eb4412f03b57.png">

if it is a stage event, entityMetadata is not null

**Comment by mrjackyliang** [comment]
> And where's the crash log?

Woops, here you go. Hid my home directory for privacy purposes.

```
    console.log('entityMetadata', event.entityMetadata.location);
                                                       ^
TypeError: Cannot read properties of null (reading 'location')
    at Client.<anonymous> (/***/src/modules/initialize.ts:709:56)
    at Client.emit (node:events:390:28)
    at Client.emit (node:domain:475:12)
    at GuildScheduledEventCreateAction.handle (/***/node_modules/discord.js/src/client/actions/GuildScheduledEventCreate.js:18:14)
    at Object.module.exports [as GUILD_SCHEDULED_EVENT_CREATE] (/***/node_modules/discord.js/src/client/websocket/handlers/GUILD_SCHEDULED_EVENT_CREATE.js:4:44)
    at WebSocketManager.handlePacket (/***/node_modules/discord.js/src/client/websocket/WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (/***/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/***/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/***/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:390:28)

Process finished with exit code 1
```

**Comment by ImRodry** [comment]
That's not discord.js crashing, that's your application crashing

**Comment by mrjackyliang** [comment]
> That's not discord.js crashing, that's your application crashing

Thanks, just edited
