### ISSUE TITLE
TypeError: player.subscribe is not a function

### ISSUE THREAD

**Issue by Ibexlol** [discordjs/discord.js#7978]
### Which package is this bug report for?

discord.js

### Issue description

I am making a music command  for my discord bot but i keep on getting  an error

### Code sample

```typescript
Error:
C:\Users\Administrator\Desktop\Simba\discordbotz\node_modules\@discordjs\voice\dist\index.js:1623
    const subscription = player["subscribe"](this);
                                            ^

TypeError: player.subscribe is not a function
    at VoiceConnection2.subscribe (C:\Users\Administrator\Desktop\Simba\discordbotz\node_modules\@discordjs\voice\dist\index.js:1623:45)
    at video_player (C:\Users\Administrator\Desktop\Simba\discordbotz\commands\play.js:99:27)
    at Object.execute (C:\Users\Administrator\Desktop\Simba\discordbotz\commands\play.js:70:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.0.1
play.js code:
const ytdl = require('ytdl-core');
const ytSearch = require('yt-search');
const {
    AudioPlayerStatus,
    createAudioPlayer,
    createAudioResource,
    joinVoiceChannel,
  } = require('@discordjs/voice');
  const ffmpeg = require('ffmpeg-static')

const queue = new Map();
// queue(messageCreate.guild.id, queue_constructor object { voice channel, text channel, connection, song[]});
module.exports = {
    name: 'play',
    aliases: ['skip', 'stop'],
    description: 'Advanced music bot commands',
    async execute(client, messageCreate, args, cmd, Discord){

        const voice_channel = messageCreate.member.voice.channel;
        if (!voice_channel) return messageCreate.channel.send('You need to be in a channel to execute this command!');
        const permissions = voice_channel.permissionsFor(messageCreate.client.user);
        if(!permissions.has('CONNECT')) return messageCreate.channel.send('You dont have the correct permissions');
        if(!permissions.has('SPEAK')) return messageCreate.channel.send('You dont have the correct permissions');

        const server_queue = queue.get(messageCreate.guild.id);

        if (cmd === 'play'){
            if (!args.length) return messageCreate.channel.send('You need to send the second argument!');
            let song = {};

            if (ytdl.validateURL(args[0])) {
                const song_info = await ytdl.getInfo(args[0]);
                song = { title: song_info.videoDetails.title, url: song_info.videoDetails.video_url } 
            } else {
                // idk lol
                const video_finder = async (query) =>{
                    const videoResult = await ytSearch(query);
                    return (videoResult.videos.length > 1) ? videoResult.videos[0] : null;
                }

                const video  = await video_finder(args.join(' '));
                const player = createAudioPlayer();
                
                if(video){
                    song = { title: video.title, url: video.url }
                } else{
                    messageCreate.channel.send('Error finding video.')
                }
            }

            if(!server_queue){

                const queue_constructor = {
                    voice_channel: voice_channel,
                    text_channel: messageCreate.channel,
                    connection: null,
                    songs: []
                }
    
                queue.set(messageCreate.guild.id, queue_constructor);
                queue_constructor.songs.push(song);
    
                try{
                    const connection = joinVoiceChannel({
                        channelId: voice_channel.id,
                        guildId: voice_channel.guild.id,
                        adapterCreator: voice_channel.guild.voiceAdapterCreator,
                      });
                    queue_constructor.connection = connection;
                    video_player(messageCreate.guild, queue_constructor.songs[0]);
                } catch(err) {
                    queue.delete(messageCreate.guild.id);
                    messageCreate.channel.send('There was an error connecting!');
                    throw err;
                }
            } else{
                server_queue.songs.push(song);
                return messageCreate.channel.send(`:thumbs_up: **${song.title}** added to queue!`);
            }
        }

        else if(cmd === 'skip') skip_song(message,server_queue);
        else if(cmd === 'stop') stop_song(message,server_queue);
    }

        
}

const video_player = async (guild, song) =>  {
    const song_queue = queue.get(guild.id);

    if(!song) {
        song_queue.voice_channel.leave();
        queue.delete(guild.id)
        return;
    }
    const stream = ytdl(song.url, { filter: 'audioonly' });
    const resource = createAudioResource(stream);
    song_queue.connection.subscribe(resource, { seek: 0, volume: 0.5 })
    .on('finish', () => {
        song_queue.songs.shift();
        video_player(guild, song_queue.songs[0]);
    });
    await song_queue.text_channel.send(`:musical_note: Now playing **${song.title}**`)
}

const skip_song = (messageCreate, server_queue) => {
    if (!messageCreate.member.voice.channel) return messageCreate.channel.send('You need to be in a channel to execute this command!');
    if(!server_queue){
        messageCreate.channel.send(`There are no songs in the queue :pensive:`);
    }
    server_queue.connection.dispatcher.end();
}

const stop_song = (messageCreate, server_queue) =>{
    if (!messageCreate.member.voice.channel) return messageCreate.channel.send('You need to be in a channel to execute this command!');
    server_queue.songs = [];
    server_queue.connection.dispatcher.end();
}
```

### Package version

v13

### Node.js version

v17.0.1

### Operating system

Windows 10

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

User, Channel, GuildMember, Message

### Which gateway intents are you subscribing to?

GuildMembers, GuildVoiceStates, GuildMessages

**Comment by Ibexlol** [comment]
Nevermind, i've fixed everything
