### ISSUE TITLE
An error occurred while sending the webhook message

### ISSUE THREAD

**Issue by Rygent** [discordjs/discord.js#8031]
### Which package is this bug report for?

discord.js

### Issue description

Got this error while trying to send a webhook message but the message was sent.
```shell
D:\Projects\Discord\Bot\Elvia@canary\node_modules\discord.js\src\structures\Message.js:358
    return this.client.channels.resolve(this.channelId);
                                ^

TypeError: Cannot read properties of undefined (reading 'resolve')
    at get channel [as channel] (D:\Projects\Discord\Bot\Elvia@canary\node_modules\discord.js\src\structures\Message.js:358:33)
    at new Message (D:\Projects\Discord\Bot\Elvia@canary\node_modules\discord.js\src\structures\Message.js:47:42)
    at WebhookClient.send (D:\Projects\Discord\Bot\Elvia@canary\node_modules\discord.js\src\structures\Webhook.js:214:86)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.3.0
```

### Code sample

```typescript
const { WebhookClient } = require('discord.js');

(() => {
	const webhook = new WebhookClient({ url: 'webhook_url' });
	webhook.send({ content: 'Hello World' });
})();
```

### Package version

14.0.0-dev.1654560560-5475767

### Node.js version

18.3.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

No Intents

**Comment by ChrisSch-dev** [comment]
Another bug with the sending Webhook Message is, that when you try to send an attachment (`files: [...]`), you are promoted with this

```
TypeError: Cannot read properties of undefined (reading 'path')
at findName (/home/ghost/eternalgaius/node_modules/discord.js/src/structures/MessagePayload.js:240:17)
at Function.resolveFile (/home/ghost/eternalgaius/node_modules/discord.js/src/structures/MessagePayload.js:254:31)
at /home/ghost/eternalgaius/node_modules/discord.js/src/structures/MessagePayload.js:221:85
at Array.map (<anonymous>)
at MessagePayload.resolveFiles (/home/ghost/eternalgaius/node_modules/discord.js/src/structures/MessagePayload.js:221:56)
at WebhookClient.send (/home/ghost/eternalgaius/node_modules/discord.js/src/structures/Webhook.js:212:50)
at WebhookManager.sendWebhook (/home/ghost/eternalgaius/src/Structures/Base/WebhookManager.js:20:23)
at module.exports.execute (/home/ghost/eternalgaius/src/Commands/Owner/eval.js:57:30)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async module.exports.callback (/home/ghost/eternalgaius/src/Events/Client/InteractionCreate.js:81:17)
```

using same pkg version and node version as this Issue stated
