### ISSUE TITLE
error with discord.js install

### ISSUE THREAD

**Issue by Sid1125** [discordjs/discord.js#8278]
### Which package is this bug report for?

discord.js

### Issue description

I am getting this error while running my bot and it isn't letting my bot to start.
There are no issues with all the packages except discord.js .

### Code sample

```typescript
/app/node_modules/discord-player/src/Player.js:6
if(version.split('.')[0] !== '12') throw new Error("Only the master branch of discord.js library is supported for now. Install it using 'npm install discordjs/discord.js'.");
                                   ^

Error: Only the master branch of discord.js library is supported for now. Install it using 'npm install discordjs/discord.js'.
    at Object.<anonymous> (/app/node_modules/discord-player/src/Player.js:6:42)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/discord-player/index.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

### Package version

13.8.1

### Node.js version

16.11.1

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by imranbarbhuiya** [comment]
this is an issue with discord-player and not discord.js. Report in that package's repo
