### ISSUE TITLE
Error when setting the image of an embed to an empty string

### ISSUE THREAD

**Issue by k2helix** [discordjs/discord.js#8385]
### Which package is this bug report for?

discord.js

### Issue description

Steps to reproduce:
1. Create a new EmbedBuilder
2. use setImage('')
3. Receive error

```
Error: Received one or more errors
at UnionValidator.handle (/app/node_modules/@sapphire/shapeshift/dist/index.js:1085:23)
at UnionValidator.parse (/app/node_modules/@sapphire/shapeshift/dist/index.js:142:88)
at EmbedBuilder.setImage (/app/node_modules/@discordjs/builders/dist/index.js:245:23)
at exports.default (/app/dist/src/events/messageDelete.js:45:100)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code sample

```typescript
new EmbedBuilder().setImage('')
```

### Package version

14.0.3

### Node.js version

17.9.1

### Operating system

Linux

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

### I have tested this issue on a development release

c25e8ad

**Comment by Jiralite** [comment]
I wouldn't say this is a bug. The [documentation](https://discord.com/developers/docs/resources/channel#embed-object-embed-image-structure) states:

> source url of image (only supports http(s) and attachments)

An empty string is not a URL of an image.
