### ISSUE TITLE
"RANDOM" is doesn't  work in EmbedBuilder().setColor()

### ISSUE THREAD

**Issue by whattyu** [discordjs/discord.js#8397]
### Which package is this bug report for?

discord.js

### Issue description

1. Create an EmbedBuilder
2. try .setColor("RANDOM")
3. get this error 
```PowerShell
[12:17:55/ERROR] ColorConvert Unable to convert color to a number.
Trace: [12:17:55/TRACE] TypeError [ColorConvert]: Unable to convert color to a number.
    at resolveColor (/home/runner/CariyePlusBot/node_modules/discord.js/src/util/Util.js:417:39)
    at EmbedBuilder.setColor (/home/runner/CariyePlusBot/node_modules/discord.js/src/structures/EmbedBuilder.js:22:36)
    at run (/home/runner/CariyePlusBot/src/bot/commands/***.js:17:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HandlerManager.InteractionCommandHandler [as interactionCommandHandler] (/home/runner/CariyePlusBot/node_modules/gcommands/dist/handlers/InteractionCommandHandler.js:70:5)
    at async run (/home/runner/CariyePlusBot/node_modules/gcommands/dist/listeners/InteractionCommandHandler.js:11:13)
    at async Listener._run (/home/runner/CariyePlusBot/node_modules/gcommands/dist/lib/structures/Listener.js:52:9)
    at ILogger.invoke (/home/runner/CariyePlusBot/node_modules/gcommands/dist/lib/util/logger/Logger.js:103:24)
    at ILogger.trace (/home/runner/CariyePlusBot/node_modules/gcommands/dist/lib/util/logger/Logger.js:59:14)
    at /home/runner/CariyePlusBot/node_modules/gcommands/dist/handlers/InteractionCommandHandler.js:76:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HandlerManager.InteractionCommandHandler [as interactionCommandHandler] (/home/runner/CariyePlusBot/node_modules/gcommands/dist/handlers/InteractionCommandHandler.js:70:5)
    at async run (/home/runner/CariyePlusBot/node_modules/gcommands/dist/listeners/InteractionCommandHandler.js:11:13)
    at async Listener._run (/home/runner/CariyePlusBot/node_modules/gcommands/dist/lib/structures/Listener.js:52:9)
    

### Code sample

```typescript
const { EmbedBuilder } = require("discord.js");
const a = new EmbedBuilder().setColor("RANDOM")
```

### Package version

14.1.1

### Node.js version

17.9.1

### Operating system

Linux

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by Jiralite** [comment]
This is not an acceptable string. See the [documentation](https://discord.js.org/#/docs/discord.js/main/typedef/ColorResolvable).
