### ISSUE TITLE
Unusual error when running on k8s:  invalid Authorization header

### ISSUE THREAD

**Issue by colin-riddell** [discordjs/discord.js#8710]
### Which package is this bug report for?

discord.js

### Issue description

When running a discord.js client locally, the client logs in correctly. ✅ 
When creating a container, and running that, it logs in correctly. ✅ 
When running that container in a kubernetes cluster    🛑 

```
│ /usr/src/app/node_modules/undici/lib/core/request.js:333                                                                                                                              
│     throw new InvalidArgumentError(`invalid ${key} header`)                                                                                                                           
│           ^   
│ InvalidArgumentError: invalid Authorization header                                                                                                                                    
│     at processHeader (/usr/src/app/node_modules/undici/lib/core/request.js:333:11)                                                                                                    
│     at new Request (/usr/src/app/node_modules/undici/lib/core/request.js:161:9)                                                                                                       
│     at Client.[dispatch] (/usr/src/app/node_modules/undici/lib/client.js:263:21)                                                                                                      
│     at Intercept (/usr/src/app/node_modules/undici/lib/interceptor/redirectInterceptor.js:11:16)                                                                                      
│     at Client.[Intercepted Dispatch] (/usr/src/app/node_modules/undici/lib/dispatcher-base.js:157:12)                                                                                 
│     at Client.dispatch (/usr/src/app/node_modules/undici/lib/dispatcher-base.js:178:40)                                                                                               
│     at Pool.[dispatch] (/usr/src/app/node_modules/undici/lib/pool-base.js:143:28)                                                                                                     
│     at Pool.[Intercepted Dispatch] (/usr/src/app/node_modules/undici/lib/dispatcher-base.js:149:29)                                                                                   
│     at Pool.dispatch (/usr/src/app/node_modules/undici/lib/dispatcher-base.js:178:40)                                                                                                 
│     at Agent.[dispatch] (/usr/src/app/node_modules/undici/lib/agent.js:118:23) {                                                                                                      
│   code: 'UND_ERR_INVALID_ARG'                                                                                                                                                         │
│ }  
```

Things I've tried:
* I've *tried* to re-create this on the container. No success
* Changing node versions.
* Changing discord.js versions
* Debugging undici.. but I'm unable to understand what's going on.

I'm also running express in the same application..Might that cause problems?

This is really hard to re-create since it's only happening when the container runs in k8s and not when running locally.
Is it maybe something to do with TLS, HTTP(s) versions? Should I need to open up any other ports so the websocket stuff works or something. 
I'll also provide my `package.json` and `Dockerfile` incase that's of help.

package.json:
```json
{
  "name": "a-test-bot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "tsc -p . && node -r dotenv/config built/index.js",
    "build": "tsc -p . ",
    "dev": "nodemon -r dotenv/config src/index.ts"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.27.2",
    "body-parser": "^1.20.0",
    "discord-bot-cdk-construct": "^0.3.3",
    "discord.js": "^14.5.0",
    "dotenv": "^16.0.2",
    "express": "^4.18.1"
  },
  "devDependencies": {
    "@types/express": "^4.17.14",
    "@types/node": "^13.13.5",
    "aws-sdk": "^2.655.0",
    "nodemon": "^2.0.20",
    "ts-node": "^10.9.1",
    "typescript": "^4.5.5"
  }
}
```

Dockerfile:

```Dockerfile
FROM node:16-alpine3.16
WORKDIR /usr/src/app
COPY package*.json ./
COPY . .
RUN npm install
RUN npm run build
EXPOSE 8080
CMD [ "node", "./built/index.js" ]
```

### Code sample

```typescript
import { Client, GatewayIntentBits, GuildMember, Interaction } from 'discord.js';

let  thisClient:Client;

export const getClient = () => {

    const client: Client = new Client({
        intents: [
            GatewayIntentBits.Guilds,
            GatewayIntentBits.GuildMembers,
        ]
    })
    
    client.on('ready', () => {
        console.log(`Logged in as ${client.user.tag}!`);
    });
    
    const options = [
        '🐭',
        'https://media.giphy.com/media/wJZTbXayokOgbCfyQe/giphy.gif',
        'https://media.giphy.com/media/QXh9XnIJetPi0/giphy.gif',
        'https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy-downsized.gif',
        '🐁',
    ];
    
    
    client.on('interactionCreate', async (interaction: Interaction | any) => {
        if (!interaction.isCommand()) return;
    
    
        if (interaction.commandName === 'foo') {
            await interaction.reply(options[Math.floor(Math.random() * options.length)]);
        }
       
    });
    
    client.on('interactionCreate', async interaction => {
        if (!interaction.isSelectMenu()) return;
    
        if (interaction.customId === 'select') {
            await interaction.update({ content: 'Something was selected! second', components: [] });
        }
    });
    
    
    client.login(process.env.BOT_TOKEN);
    
    thisClient = client;
    return client;
}


export const getMemberByTag = async (tag: string,) => {
    const Guilds = thisClient.guilds.cache.map((guild) => guild);

    const members = await Guilds[0].members.fetch()

    const foundGuildMembers = members.filter((guildMember: GuildMember) => {
        const combined = `${guildMember.user.username}#${guildMember.user.discriminator}`
        return (combined === tag)
    })
    if (foundGuildMembers.at(0) === undefined) {
        return {}
    }
    return foundGuildMembers.at(0).user;
}
```

### Package version

14.5.0

### Node.js version

16   ts-node@10.9.1 typescript@4.5.5 typescript@4.5.5

### Operating system

node16 and node:16-alpine3.16  (containers)

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers

### I have tested this issue on a development release

e745b95.0

**Comment by didinele** [comment]
This just sounds like your Discord bot token is set to a weird value (assuming its an environmental variable)

**Comment by colin-riddell** [comment]
My secret had a newline at the end which I didn't previously notice.

Unrelated to this library... but before supplying your secret to be hashed it will need to be converted to base64. 
Doing this with ` echo -n 'secretstringhere' | base64` will omit the `\n`. where ` echo -n 'secretstringhere' | base64` will include a `\n`!!!!
