### ISSUE TITLE
CombinedPropertyError with addFields and setFields

### ISSUE THREAD

**Issue by StanByes** [discordjs/discord.js#8747]
### Which package is this bug report for?

discord.js

### Issue description

Create an embed with EmbedBuilder.
Do addFields or setFields with an array

### Code sample

```typescript
function randomParameters(params) {
    let fields = [];
    for (let param of Object.values(params)) {
        fields.push({name: param.title, value: param.options[Math.floor(Math.random() * param.options.length)], inline: true});
    }

    return fields;
}

function randomPlayers() {
    let embed = new EmbedBuilder()
        .setDescription('Random')
        .addFields(randomParameters(data.player))
        .setColor(3092790)
        .setTimestamp();
        
    return embed;
}
```

### Package version

14.6.0

### Node.js version

18.6.0

### Operating system

Raspbian 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Channel, GuildMember, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildVoiceStates, GuildMessages, GuildMessageReactions, DirectMessages, MessageContent

**Comment by StanByes** [comment]
The error is:
```
CombinedPropertyError: Received one or more errors
    at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:427:70)
    at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
    at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
    at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
    at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
    at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    [
      0,
      CombinedPropertyError: Received one or more errors
          at ObjectValidator.handleIgnoreStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1219:70)
          at ObjectValidator.handleStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1075:47)
          at ObjectValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1172:17)
          at ObjectValidator.run (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:99:23)
          at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:421:37)
          at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
          at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
          at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
          at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
          at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        errors: [ [ 'value', [ValidationError] ] ]
      }
    ],
    [
      1,
      CombinedPropertyError: Received one or more errors
          at ObjectValidator.handleIgnoreStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1219:70)
          at ObjectValidator.handleStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1075:47)
          at ObjectValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1172:17)
          at ObjectValidator.run (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:99:23)
          at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:421:37)
          at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
          at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
          at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
          at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
          at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        errors: [ [ 'value', [ValidationError] ] ]
      }
    ],
    [
      2,
      CombinedPropertyError: Received one or more errors
          at ObjectValidator.handleIgnoreStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1219:70)
          at ObjectValidator.handleStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1075:47)
          at ObjectValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1172:17)
          at ObjectValidator.run (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:99:23)
          at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:421:37)
          at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
          at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
          at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
          at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
          at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        errors: [ [ 'value', [ValidationError] ] ]
      }
    ],
    [
      5,
      CombinedPropertyError: Received one or more errors
          at ObjectValidator.handleIgnoreStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1219:70)
          at ObjectValidator.handleStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1075:47)
          at ObjectValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1172:17)
          at ObjectValidator.run (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:99:23)
          at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:421:37)
          at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
          at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
          at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
          at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
          at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        errors: [ [ 'value', [ValidationError] ] ]
      }
    ],
    [
      6,
      CombinedPropertyError: Received one or more errors
          at ObjectValidator.handleIgnoreStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1219:70)
          at ObjectValidator.handleStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1075:47)
          at ObjectValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1172:17)
          at ObjectValidator.run (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:99:23)
          at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:421:37)
          at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
          at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
          at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
          at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
          at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        errors: [ [ 'value', [ValidationError] ] ]
      }
    ]
  ]
```

**Comment by StanByes** [comment]
The error is:
```
CombinedPropertyError: Received one or more errors
    at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:427:70)
    at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
    at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
    at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
    at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
    at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    [
      0,
      CombinedPropertyError: Received one or more errors
          at ObjectValidator.handleIgnoreStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1219:70)
          at ObjectValidator.handleStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1075:47)
          at ObjectValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1172:17)
          at ObjectValidator.run (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:99:23)
          at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:421:37)
          at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
          at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
          at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
          at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
          at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        errors: [ [ 'value', [ValidationError] ] ]
      }
    ],
    [
      1,
      CombinedPropertyError: Received one or more errors
          at ObjectValidator.handleIgnoreStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1219:70)
          at ObjectValidator.handleStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1075:47)
          at ObjectValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1172:17)
          at ObjectValidator.run (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:99:23)
          at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:421:37)
          at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
          at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
          at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
          at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
          at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        errors: [ [ 'value', [ValidationError] ] ]
      }
    ],
    [
      2,
      CombinedPropertyError: Received one or more errors
          at ObjectValidator.handleIgnoreStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1219:70)
          at ObjectValidator.handleStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1075:47)
          at ObjectValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1172:17)
          at ObjectValidator.run (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:99:23)
          at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:421:37)
          at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
          at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
          at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
          at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
          at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        errors: [ [ 'value', [ValidationError] ] ]
      }
    ],
    [
      5,
      CombinedPropertyError: Received one or more errors
          at ObjectValidator.handleIgnoreStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1219:70)
          at ObjectValidator.handleStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1075:47)
          at ObjectValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1172:17)
          at ObjectValidator.run (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:99:23)
          at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:421:37)
          at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
          at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
          at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
          at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
          at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        errors: [ [ 'value', [ValidationError] ] ]
      }
    ],
    [
      6,
      CombinedPropertyError: Received one or more errors
          at ObjectValidator.handleIgnoreStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1219:70)
          at ObjectValidator.handleStrategy (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1075:47)
          at ObjectValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:1172:17)
          at ObjectValidator.run (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:99:23)
          at ArrayValidator.handle (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:421:37)
          at ArrayValidator.parse (/srv/phasmo/PhasmoBotDev/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
          at EmbedBuilder.addFields (/srv/phasmo/PhasmoBotDev/node_modules/@discordjs/builders/dist/index.js:191:31)
          at randomPlayers (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:106:10)
          at RandomizeCommand.run (/srv/phasmo/PhasmoBotDev/src/commands/utils/RandomCommandV2.js:57:45)
          at CommandEvent.run (/srv/phasmo/PhasmoBotDev/src/events/member/Command.js:40:13)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        errors: [ [ 'value', [ValidationError] ] ]
      }
    ]
  ]
```

**Comment by imranbarbhuiya** [comment]
The error message you provided is from an u handled rejection so its not formatted properly.  Can you try adding a try/catch in your `.addFields` line and log the error coming from catch using `console.log`

**Comment by StanByes** [comment]
```
CombinedPropertyError (6)
  Received one or more errors

  input[0]
  | CombinedPropertyError (1)
  |   Received one or more errors
  |
  |   input.value
  |   | ValidationError > s.string
  |   |   Expected a string primitive
  |   |
  |   |   Received:
  |   |   | 100

  input[1]
  | CombinedPropertyError (1)
  |   Received one or more errors
  |
  |   input.value
  |   | ValidationError > s.string
  |   |   Expected a string primitive
  |   |
  |   |   Received:
  |   |   | 25

  input[2]
  | CombinedPropertyError (1)
  |   Received one or more errors
  |
  |   input.value
  |   | ValidationError > s.string
  |   |   Expected a string primitive
  |   |
  |   |   Received:
  |   |   | 1

  input[4]
  | CombinedPropertyError (1)
  |   Received one or more errors
  |
  |   input.value
  |   | ValidationError > s.string
  |   |   Expected a string primitive
  |   |
  |   |   Received:
  |   |   | 3

  input[5]
  | CombinedPropertyError (1)
  |   Received one or more errors
  |
  |   input.value
  |   | ValidationError > s.string
  |   |   Expected a string primitive
  |   |
  |   |   Received:
  |   |   | 2

  input[6]
  | CombinedPropertyError (1)
  |   Received one or more errors
  |
  |   input.value
  |   | ValidationError > s.string
  |   |   Expected a string primitive
  |   |
  |   |   Received:
  |   |   | 50
```
I think it's because I'm using Integer values without parse them in String ?

**Comment by StanByes** [comment]
It's really this, thank you for your help @imranbarbhuiya
