### ISSUE TITLE
A little bug with the channels.cache.get with TS

### ISSUE THREAD

**Issue by dalmatheo** [discordjs/discord.js#8756]
### Which package is this bug report for?

discord.js

### Issue description

If you are with typescript in discord JS 14.6.0 an node 18.10.0 (didn't test with any other versions), you have a little error with client.channels.cache.get("channelid"). It does not respond in my case a TextChannel but a boolean. So you need to use a @ts-ignore. 

### Code sample

```typescript
import {Client, Message, TextChannel} from "discord.js";
import config from "../assets/config.json"

export async function discordLog(client:Client, message:Message) {
    if (message.author.bot) return

    const test:TextChannel = client.channels.cache.get("1030922685015937064")
    await test.send(message.content)
}

just send a messageCreate in that function and there you have the error.
```

### Package version

14.6.0

### Node.js version

18.10.0

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
> just send a messageCreate in that function and there you have the error.

And that error is?

**Comment by dalmatheo** [comment]
```error TS2339: Property 'send' does not exist on type 'Channel'.
  Property 'send' does not exist on type 'CategoryChannel'.

10     await test.send()
                  ~~~~

    at createTSError (E:\Développement\JavaScript\discordtypescript\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (E:\Développement\JavaScript\discordtypescript\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (E:\Développement\JavaScript\discordtypescript\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (E:\Développement\JavaScript\discordtypescript\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (E:\Développement\JavaScript\discordtypescript\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Object.require.extensions.<computed> [as .ts] (E:\Développement\JavaScript\discordtypescript\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1051:19) {
  diagnosticCodes: [ 2339 ]
}
```

The problem is that when you console.log the test const it respond a TextChannel but it says that it's just a channel and you need to add @ts-ignore to set the type of test to TextChannel

**Comment by Jiralite** [comment]
The error seems to indicate that `test` is not a boolean despite stating otherwise in the issue.

Anyway, the code sample is incorrectly invalid as you are looking in a collection of any channel. Getting an arbitrary channel from there may not even be a text channel. You need to use a type guard. I see this is more of a question, so please visit the [Discord server](https://discord.gg/djs) if you have any queries.
