### ISSUE TITLE
Thread channel function fetchStarterMessage() does not wait until the first message is actually posted on the thread

### ISSUE THREAD

**Issue by KiprasJ** [discordjs/discord.js#8788]
### Which package is this bug report for?

discord.js

### Issue description

Step to reproduce:
1. Start a new post
2. Enter title, message and include file attachments.

The error seems to occur only when file attachments are added and I presume that the code sample runs sooner than the actual message is being posted to the thread.

### Code sample

```typescript
client.on('threadCreate', (threadChannel) => {
            threadChannel.fetchStarterMessage().then((message) => {
                console.log(message)
            })
})
```

Error
```
         throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
               ^
 
 DiscordAPIError[10008]: Unknown Message
     at SequentialHandler.runRequest (D:\Dev\Node.js\bitrune-be-new\node_modules\.pnpm\@discordjs+rest@1.3.0\node_modules\@discordjs\rest\dist\index.js:659:15)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async SequentialHandler.queueRequest (D:\Dev\Node.js\bitrune-be-new\node_modules\.pnpm\@discordjs+rest@1.3.0\node_modules\@discordjs\rest\dist\index.js:458:14)
     at async REST.request (D:\Dev\Node.js\bitrune-be-new\node_modules\.pnpm\@discordjs+rest@1.3.0\node_modules\@discordjs\rest\dist\index.js:902:22)
     at async MessageManager._fetchSingle (D:\Dev\Node.js\bitrune-be-new\node_modules\.pnpm\discord.js@14.6.0\node_modules\discord.js\src\managers\MessageManager.js:101:18) {
   requestBody: { files: undefined, json: undefined },
   rawError: { message: 'Unknown Message', code: 10008 },
   code: 10008,
   status: 404,
   method: 'GET',
   url: 'https://discord.com/api/v10/channels/1034998667037397072/messages/1034998667037397072'
 }

```
```


### Package version

14.6.0

### Node.js version

17.6.0

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, DirectMessages, MessageContent

### I have tested this issue on a development release

_No response_

**Comment by Jiralite** [comment]
This is just a Discord limitation. Discord does not send initial messages with their thread creation payloads. discord.js cannot decide to wait an unknown amount of time to cater to this need. The real fix here is for Discord to send initial mesage payloads alongside the thread - anything discord.js does here is working around the problem.

**Comment by KiprasJ** [comment]
@Jiralite Alright thanks for the explanation! 😸
