### ISSUE TITLE
Cannot read properties of undefined (reading 'cache') channel djs v13

### ISSUE THREAD

**Issue by pkdev08** [discordjs/discord.js#8813]
### Which package is this bug report for?

discord.js

### Issue description

Just been seeing a bunch of these uncaught exceptions errors since yesterday followed by reconnects. It's on the same shard each time and just reconnecting every few minutes. Not sure if discord introduced a new channel type or modified something with the channels.

Here is the stack it's happening at:

TypeError: Cannot read properties of undefined (reading 'cache')

at Function.create (/home/test/node_modules/discord.js/src/structures/Channel.js:228:60)
    at ChannelManager._add (/home/test/node_modules/discord.js/src/managers/ChannelManager.js:47:29)
    at Guild._patch (/home/test/node_modules/discord.js/src/structures/Guild.js:439:30)
    at new Guild (/home/test/node_modules/discord.js/src/structures/Guild.js:128:12)
    at GuildManager._add (/home/test/node_modules/discord.js/src/managers/CachedManager.js:58:32)
    at Object.module.exports [as GUILD_CREATE] (/home/test/node_modules/discord.js/src/client/websocket/handlers/GUILD_CREATE.js:15:27)
    at WebSocketManager.handlePacket (/home/test/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/test/node_modules/discord.js/src/client/websocket/WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (/home/test/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at WebSocket.onMessage (/home/test/node_modules/ws/lib/event-target.js:199:18)

### Package version

discord.js@13.11.0

### Node.js version

v16.18.0

### Operating system

Ubuntu

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildInvites, GuildVoiceStates, GuildMessageReactions, DirectMessages, MessageContent

**Comment by Jiralite** [comment]
This indicates discord.js failed to create a thread channel class. However, I wasn't able to reproduce this on announcement threads, private threads, or public threads.

> Not sure if discord introduced a new channel type

The channel types are checked before creating the class, so it is not a new channel type.

Your best bet is to log what data you are receiving as soon as you crash. Also, are you using a modified version of discord.js?

**Comment by pkdev08** [comment]
Nope, not on a modified version. I have been using the same version for a while and never encountered this error. I did notice their were two guilds that were undefined on that shard, which seemed odd. I'm going to reboot and see if that helps and try to log if it continues.
<img width="322" alt="undefined" src="https://user-images.githubusercontent.com/54294685/200100130-85e2db91-feaf-4770-9da4-6535db2239b1.png">

**Comment by imranbarbhuiya** [comment]
those are `unavailable` guilds

**Comment by pkdev08** [comment]
I noticed that I also had this same error in a different stack.

TypeError: Cannot read properties of undefined (reading 'cache')

 at Client.get emojis [as emojis] (/home/test/node_modules/discord.js/src/client/Client.js:206:61)
    at MessageReaction.get emoji [as emoji] (/home/test/node_modules/discord.js/src/structures/MessageReaction.js:78:42)
    at MessageReaction._remove (/home/test/node_modules/discord.js/src/structures/MessageReaction.js:126:48)
    at MessageReactionRemove.handle (/home/test/node_modules/discord.js/src/client/actions/MessageReactionRemove.js:32:14)
    at Object.module.exports [as MESSAGE_REACTION_REMOVE] (/home/test/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_REACTION_REMOVE.js:4:40)
    at WebSocketManager.handlePacket (/home/test/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/test/node_modules/discord.js/src/client/websocket/WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (/home/test/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at WebSocket.onMessage (/home/test/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)

**Comment by Qjuh** [comment]
Could you show the whole console.log of that Guild you showed earlier? Especially its `available` property?

**Comment by era5mx** [comment]
Did you manage to solve the issue? Could you share?
