### ISSUE TITLE
Cannot regist slashcommands

### ISSUE THREAD

**Issue by Fyphen1223** [discordjs/discord.js#8870]
### Which package is this bug report for?

discord.js

### Issue description

```javascript
var start = new Date();
const { REST, SlashCommandBuilder, Routes, ContextMenuCommandBuilder, ApplicationCommandType } = require('discord.js');
const config = require("./config.json");
const commands = [
		new SlashCommandBuilder().setName('ping').setDescription('Replies with ping'),
		new SlashCommandBuilder().setName('server').setDescription('Replies with server info'),
		new SlashCommandBuilder().setName('user').setDescription('Replies with send user info'),
     	new SlashCommandBuilder().setName('time').setDescription('Replies with now time'),
		new SlashCommandBuilder().setName('invite').setDescription('Generete invite link'),
		new SlashCommandBuilder()
			.setName('echo')
			.setDescription('Replies with your input!')
			.addStringOption(option =>
				option.setName('input')
				.setDescription('The input to echo back')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('dm')
			.setDescription('Send DM')
			.addStringOption(option =>
				option.setName('dm')
				.setDescription('DM Content')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('clear')
			.setDescription('Clear message')
			.setDMPermission(false)
			.setDefaultMemberPermissions(0)
			.addIntegerOption(option => 
				option.setName('clear')
				.setDescription('Number of you want to clear')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('timer')
			.setDescription('Set timer')
			.addIntegerOption(option => 
				option.setName('time')
				.setDescription('Time as second')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('ban')
			.setDescription('Ban Member')
			.setDefaultMemberPermissions(0)
			.addUserOption(option => 
				option.setName('user')
				.setDescription('User you want to ban')
				.setRequired(true))
			.addStringOption(option => 
				option.setName('reason')
				.setDescription('Reason to BAN')
				.setRequired(false)),
		new SlashCommandBuilder()
			.setName('dmsend')
			.setDescription('Send DM to member')
			.addUserOption(option => 
				option.setName('user')
			.setDescription('User you want to send DM from BOT')
			.setRequired(true))
			.addStringOption(option => 
				option.setName('content')
				.setDescription('DM Content')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('kick')
			.setDescription('Kick Member')
			.setDefaultMemberPermissions(0)
			.addUserOption(option => 
				option.setName('user')
				.setDescription('User you want to kick')
				.setRequired(true))
			.addStringOption(option => 
				option.setName('reason')
				.setDescription('Reason to Kick')
				.setRequired(false)),
		new SlashCommandBuilder().setName('update').setDescription('Dispay update article'),
		new SlashCommandBuilder()
			.setName('dev')
			.setDescription('Dev'),
		new SlashCommandBuilder()
			.setName('reactdel')
			.setDescription('Delete all reaction of selected message')
			.addStringOption(option =>
				option.setName('msgid')
				.setDescription('Message ID')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('translate')
			.setDescription('Transalate string ex. translate content, source, target')
			.addStringOption(option =>
				option.setName('content')
				.setDescription('Translate content')
				.setRequired(true))
			.addStringOption(option =>
				option.setName('source')
				.setDescription('Source launguage')
				.setRequired(true))
			.addStringOption(option =>
				option.setName('target')
				.setDescription('Target launguage')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('cmd')
			.setDescription('Command input')
			.setDefaultMemberPermissions(0),
		new SlashCommandBuilder()
			.setName('whois')
			.setDescription('Check whois information')
			.addStringOption(option =>
				option.setName('domain')
				.setDescription('Domain name')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('ytdl')
			.setDescription('YouTube Download')
			.setDefaultMemberPermissions(0)
			.addStringOption(option=>
				option.setName('url')
				.setDescription('YouTube Movie Url')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('down')
			.setDescription('Shutdown BOT')
			.setDefaultMemberPermissions(0),
		new SlashCommandBuilder()
			.setName('screenshot')
			.setDescription('Get web page screenshot')
			.addStringOption(option =>
				option.setName('url')
				.setDescription('URL')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('stop')
			.setDescription('Stop playing music'),
		new SlashCommandBuilder()
			.setName('lyric')
			.setDescription('Get song lyric')
			.addStringOption(option =>
				option.setName('artist')
				.setDescription('Artist')
				.setRequired(true))
			.addStringOption(option =>
				option.setName('song')
				.setDescription('Song name')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('play')
			.setDescription('Play the music with vanilla discordjs voice')
			.addStringOption(option =>
				option.setName('url')
				.setDescription('YouTube URL')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('stop')
			.setDescription('Stop the music with vanilla discordjs voice'),
		new SlashCommandBuilder()
			.setName('pause')
			.setDescription('Pause the music with vanilla discordjs voice'),
		new SlashCommandBuilder()
			.setName('unpause')
			.setDescription('Unpause the music with vanilla discordjs voice'),
		new SlashCommandBuilder()
			.setName('giveaway')
			.setDescription('Giveaway')
			.setDefaultMemberPermissions(0)
			.addStringOption(option =>
				option.setName('prize')
				.setDescription('Gift name')
				.setRequired(true))
			.addStringOption(option => 
				option.setName('duration')
				.setDescription('Time')
				.setRequired(true))
			.addIntegerOption(option =>
				option.setName('winners')
				.setDescription('Winner count')
				.setRequired(true)),
		new SlashCommandBuilder()
			.setName('reroll')
			.setDescription('Reroll giveaway')
			.setDefaultMemberPermissions(0)
			.addStringOption(option =>
				option.setName('msgid')
				.setDescription('Message ID')
				.setRequired(true)),
].map(command => command.toJSON());
const rest = new REST({ version: '10' }).setToken(config.token);
const reset = [];
rest.put(Routes.applicationCommands(config.applicationId), { body: commands })
	.then((data) => console.log(`Successfully registered ${data.length} application commands with ${(new Date() - start)/1000}s`))
	.catch(console.error);
```
Just like this, and run this script, should regist application commands and message but it show me error message.
```bash
DiscordAPIError[20001]: Bots cannot use this endpoint
    at SequentialHandler.runRequest (C:\Users\shoot\Desktop\Program\BOT\node_modules\@discordjs\rest\dist\index.js:659:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\****\Desktop\Program\BOT\node_modules\@discordjs\rest\dist\index.js:458:14)
    at async REST.request (C:\Users\****\Desktop\Program\BOT\node_modules\@discordjs\rest\dist\index.js:902:22) {
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object]
    ]
  },
  rawError: { message: 'Bots cannot use this endpoint', code: 20001 },
  code: 20001,
  status: 403,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications//commands'
}

```

### Code sample

```typescript
DiscordAPIError[20001]: Bots cannot use this endpoint
    at SequentialHandler.runRequest (C:\Users\shoot\Desktop\Program\BOT\node_modules\@discordjs\rest\dist\index.js:659:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\shoot\Desktop\Program\BOT\node_modules\@discordjs\rest\dist\index.js:458:14)
    at async REST.request (C:\Users\shoot\Desktop\Program\BOT\node_modules\@discordjs\rest\dist\index.js:902:22) {
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object]
    ]
  },
  rawError: { message: 'Bots cannot use this endpoint', code: 20001 },
  code: 20001,
  status: 403,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications//commands'
}

var start = new Date();
const { REST, SlashCommandBuilder, Routes, ContextMenuCommandBuilder, ApplicationCommandType } = require('discord.js');
const config = require("./config.json");
const commands = [
		new SlashCommandBuilder().setName('ping').setDescription('Replies with ping')
].map(command => command.toJSON());
const rest = new REST({ version: '10' }).setToken(config.token);
const reset = [];
rest.put(Routes.applicationCommands(config.applicationId), { body: commands })
	.then((data) => console.log(`Successfully registered ${data.length} application commands with ${(new Date() - start)/1000}s`))
	.catch(console.error);
```

### Package version

14.6.0

### Node.js version

16.17.0

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildBans, GuildEmojisAndStickers, GuildIntegrations, GuildWebhooks, GuildInvites, GuildVoiceStates, GuildPresences, GuildMessages, GuildMessageReactions, GuildMessageTyping, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent, GuildScheduledEvents, AutoModerationConfiguration, AutoModerationExecution

**Comment by Jiralite** [comment]
If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) as this issue tracker is only for bug reports and enhancement suggestions.

**Comment by Fyphen1223** [comment]
For someone looking answer for this issue, I strongly recommend checking bot's gateway intents.
