### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id'), trying to access crosspostable

### ISSUE THREAD

**Issue by NeunEinser** [discordjs/discord.js#8952]
### Which package is this bug report for?

discord.js

### Issue description

1. Send a message to an announcement channel
2. Try to read the `crosspostable` property
3. Get Error:
```
 TypeError: Cannot read properties of undefined (reading 'id')
    at GuildMemberRoleManager.get cache [as cache] (<path-from-root>/node_modules/discord.js/src/managers/GuildMemberRoleManager.js:37:101)
    at NewsChannel.memberPermissions (<path-from-root>/node_modules/discord.js/src/structures/GuildChannel.js:205:32)
    at NewsChannel.permissionsFor (<path-from-root>/node_modules/discord.js/src/structures/GuildChannel.js:161:29)
    at NewsChannel.get viewable [as viewable] (<path-from-root>/node_modules/discord.js/src/structures/GuildChannel.js:436:30)
    at Message.get crosspostable [as crosspostable] (<path-from-root>/node_modules/discord.js/src/structures/Message.js:675:17)
    at Client.<anonymous> (<path-from-root>/bin/your-file.js:36:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code sample

```typescript
const channel = (await this.discordClient.channels.fetch(testChannelId)) as NewsChannel;
const message = await channel.send("Test message");
if (message.crosspostable)
	await message.crosspost();
```

### Package version

discord.js@14.7.1

### Node.js version

v16.17.0, typescript@4.9.4

### Operating system

Ubuntu 20.04.4 LTS

### Priority this issue should have

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

GuildMessages

**Comment by Jiralite** [comment]
You require the `GUILDS` intent.

**Comment by NeunEinser** [comment]
Thank you very much! :)
