### ISSUE TITLE
The problem with the response to the interaction.

### ISSUE THREAD

**Issue by Monix362** [discordjs/discord.js#9015]
### Which package is this bug report for?

discord.js

### Issue description

When using a type 6 component, there is a problem when responding to an interaction if no roles are selected. 

Subsequently, when trying to send a heartbeat, the shard does not receive confirmation and reconnects due to zombie connections.

![gif](https://i.imgur.com/z5T1e9A.gif)
![img](https://i.imgur.com/8QwRrrf.png)
![img](https://i.imgur.com/zGvVR1K.png)

### Code sample

```typescript
TypeError: Cannot read properties of undefined (reading 'roles')
    at new RoleSelectMenuInteraction (\node_modules\discord.js\src\structures\RoleSelectMenuInteraction.js:25:57)
    at InteractionCreateAction.handle (\node_modules\discord.js\src\client\actions\InteractionCreate.js:90:25)
    at Object.module.exports [as INTERACTION_CREATE] (\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (\node_modules\discord.js\src\client\websocket\WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (\node_modules\discord.js\src\client\websocket\WebSocketShard.js:328:10)
    at callListener (\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (\node_modules\ws\lib\event-target.js:209:9)
```

### Package version

14.7.0

### Node.js version

16.3.0

### Operating system

Windows 11

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildVoiceStates, GuildMessages, MessageContent

**Comment by Jiralite** [comment]
It is never a good idea to report bugs on old versions. You just need to update.
