### ISSUE TITLE
MessageReaction/ReactionEmoji toJSON infinite loop

### ISSUE THREAD

**Issue by haowang1013** [discordjs/discord.js#9067]
### Which package is this bug report for?

discord.js

### Issue description

Calling MessageReaction.toJSON causes an infinite loop if the reaction has an emoji property since the flatten logic will call ReactionEmoji.toJSON, which triggers MessageReaction.toJSON again since the emoji object has a reference back to the reaction.

This is the log
```
RangeError: Maximum call stack size exceeded
    at MessageReaction.toJSON (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\structures\MessageReaction.js:117:5)
    at flatten (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\util\Util.js:46:48)
    at ReactionEmoji.toJSON (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\structures\ReactionEmoji.js:23:12)
    at flatten (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\util\Util.js:46:48)
    at MessageReaction.toJSON (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\structures\MessageReaction.js:117:12)
    at flatten (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\util\Util.js:46:48)
    at ReactionEmoji.toJSON (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\structures\ReactionEmoji.js:23:12)
    at flatten (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\util\Util.js:46:48)
    at MessageReaction.toJSON (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\structures\MessageReaction.js:117:12)
    at flatten (D:\work\directivegames\dg-discord-bot\node_modules\discord.js\src\util\Util.js:46:48)
```

### Code sample

```typescript
client.on(Events.MessageReactionAdd, (reaction, user) => {
   console.log(reaction.toJSON())
})
```

### Package version

14.7.1

### Node.js version

18.12.0

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by RedStars071** [comment]
I have the same problem

**Comment by shawnjb** [comment]
A potential solution for this issue would be to update the `MessageReaction.toJSON()` method to check for circular references before calling `ReactionEmoji.toJSON()`. This would prevent the infinite loop caused by the circular reference between the `MessageReaction` and `ReactionEmoji` objects.

One way to do this would be to add a `visited` property to the `MessageReaction` and `ReactionEmoji` objects, and set it to true when calling `toJSON()`. Before calling `ReactionEmoji.toJSON()`, the `MessageReaction.toJSON()` method could check if the `emoji` property's `visited` property is set to `true`, and if so, skip calling `ReactionEmoji.toJSON()` to avoid the infinite loop.

**Comment by Jiralite** [comment]
There's a linked pull request for this issue already. Feel free to review it, @shawnjb.
