### ISSUE TITLE
ESM issue in discordjs

### ISSUE THREAD

**Issue by SaumilAgrawal** [discordjs/discord.js#9188]
### Which package is this bug report for?

discord.js

### Issue description

I am using discordjs in back4app, I see the following error in the logs
It seems the error is because the ES is written in .js file :

/usr/src/app/data/cloud/node_modules/@discordjs/util/dist/index.js:34
  return () => defaultValue ??= cb();
                            ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/src/app/data/cloud/node_modules/@discordjs/rest/dist/index.js:276:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

### Package version

14.7.1

### Node.js version

18.14.2

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by kyranet** [comment]
You're not using Node.js v16.9.0+, which implemented [`??=`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment). Check `process.version` or `process.versions` to confirm.
