### ISSUE TITLE
Crashing when calling GuildMemberRolesManager.cache

### ISSUE THREAD

**Issue by Nabil-Alsaiad** [discordjs/discord.js#9192]
### Which package is this bug report for?

discord.js

### Issue description

An error is thrown whenever I try to call the "cache" property from a "GuildMemberRolesManager" inside a "GUILD_MEMBER_UPDATE" event, this issue occurs on both "oldMember" and "newMember".

The error message:
"PROJECT_PATH"\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:37
    return this.guild.roles.cache.filter(role => this.member._roles.includes(role.id)).set(everyone.id, everyone);

                    ^ (((this arrow is pointing to the "id" property from "set(everyone.id, everyone)" in the previous line)))

TypeError: Cannot read properties of undefined (reading 'id')
    at get cache [as cache] ("PROJECT_PATH"\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:37:101)
    at Client.<anonymous> ("PROJECT_PATH"\dist\core\discordBot.js:45:68)
    at Client.emit (node:events:513:28)
    at GuildMemberUpdateAction.handle ("PROJECT_PATH"\node_modules\discord.js\src\client\actions\GuildMemberUpdate.js:30:74)
    at module.exports [as GUILD_MEMBER_UPDATE] ("PROJECT_PATH"\node_modules\discord.js\src\client\websocket\handlers\GUILD_MEMBER_UPDATE.js:4:36)
    at WebSocketManager.handlePacket ("PROJECT_PATH"\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket ("PROJECT_PATH"\node_modules\discord.js\src\client\websocket\WebSocketShard.js:489:22)      
    at WebSocketShard.onMessage ("PROJECT_PATH"\node_modules\discord.js\src\client\websocket\WebSocketShard.js:328:10)     
    at callListener ("PROJECT_PATH"\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage ("PROJECT_PATH"\node_modules\ws\lib\event-target.js:209:9)

Node.js v18.14.2

### Code sample

```typescript
client.on("guildMemberUpdate", (oldMember: GuildMember | PartialGuildMember, newMember: GuildMember) => {
		console.log("old roles: ", oldMember.roles.cache);
		console.log("new roles: ", newMember.roles.cache);
});
```

### Package version

14.7.1

### Node.js version

18.14.2

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Which partials do you have configured?

GuildMember, Message

### Which gateway intents are you subscribing to?

GuildMembers, GuildMessages

### I have tested this issue on a development release

discord.js@14.7.2-dev.1677808268-dc142c4.0

**Comment by Jiralite** [comment]
You need the `Guilds` intent.
