### ISSUE TITLE
discordjs embed builder - setDescription/setTitle throw error if text is empty 

### ISSUE THREAD

**Issue by orblazer** [discordjs/discord.js#9439]
### Which package is this bug report for?

discord.js

### Issue description

1. use `discord.js@14.9.0`, `@discordjs/builders@1.6.1`
2. make basic client
3. use bellow code

### Code sample

```typescript
// TODO: define "channel" to an text channel
const embed = new Discord.EmbedBuilder()
    .setColor('Green')
    .setTitle('test')
    .setDescription('')
    .setTimestamp()

await channel.send({
  content: 'test embed',
  embeds: [embed]
})
```

### Package version

14.9.0

### Node.js version

v18.15.0

### Operating system

Linux (alpine in docker)

### Priority this issue should have

Low (slightly annoying)

### Which partials do you have configured?

Not applicable (subpackage bug)

### Which gateway intents are you subscribing to?

Not applicable (subpackage bug)

**Comment by orblazer** [comment]
This thrown error like this :
```
Error: Received one or more errors
    at UnionValidator.handle (/app/node_modules/@sapphire/shapeshift/src/validators/UnionValidator.ts:105:14)
    at UnionValidator.parse (/app/node_modules/@sapphire/shapeshift/src/validators/BaseValidator.ts:96:2)
    at setDescription (/app/node_modules/@discordjs/builders/src/messages/embed/Embed.ts:192:24)
    at sendMessage (/app/src/index.ts:579:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by vladfrangu** [comment]
This is not a bug, if you call that method you need to provide a proper description/title that isn't the empty string
