### ISSUE TITLE
DiscordAPError[10062]: Unknown Interaction

### ISSUE THREAD

**Issue by edram3** [discordjs/discord.js#9477]
### Which package is this bug report for?

discord.js

### Issue description

/home/container/node_modules/@discordjs/rest/dist/index.js:640
      throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
            ^

DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:736:23)
    at async REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async ChatInputCommandInteraction.reply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5) {
  requestBody: {
    files: [],
    json: {
      type: 4,
      data: {
        content: undefined,
        tts: false,
        nonce: undefined,
        embeds: [
          {
            description: 'Successfully deleted **2** messages.',
            color: 5793266
          }
        ],
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined
      }
    }
  },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1101979375995453581/aW50ZXJhY3Rpb246MTEwMTk3OTM3NTk5NTQ1MzU4MTpnYlQwY2c3ZGRYODhWRnBsemdxUWNOYW1OcjZhdWZRVmowbHF1QVBYQXY4S2tucmNadVNRR0w1djhUNHI3TkxsSjVzaERJN1NobXBhZ21TaWJyVHdNM2hrMHFFNFZGZ3RyZlVHdzRvMzJqQ1FkTDRUZG56SHhMUlpLRXUzb3JWUg/callback'
}

### Code sample

```typescript
require('dotenv').config();
// mongoose
const mongoose = require("mongoose");
const { mongooseConnectionString } = require("./config.json");
if (!mongooseConnectionString) return;

        mongoose
            .connect(mongooseConnectionString, {
              keepAlive: true,
            })
            .then(() => console.log("Connected to mongodb"));

const { IntentsBitField, Client, Collection, REST, ActivityType, Events, ModalBuilder, TextInputBuilder, TextInputStyle, ActionRowBuilder, EmbedBuilder, ButtonStyle, ButtonBuilder, ChannelType } = require("discord.js");
const {loadCommands} = require("./Handlers/loadCommands");
const {loadEvents} = require("./Handlers/loadEvents");

const client = new Client({
  intents: [
    IntentsBitField.Flags.Guilds,
    IntentsBitField.Flags.GuildMembers,
    IntentsBitField.Flags.MessageContent,
    IntentsBitField.Flags.GuildMessages,
    IntentsBitField.Flags.GuildPresences,
    IntentsBitField.Flags.DirectMessages,
    IntentsBitField.Flags.DirectMessageTyping,
  ],
});

client.commands = new Collection();

client.on('ready', () => {
    console.log(`${client.user.tag} ready!`);
    const guildMcGuild = client.guilds.cache.get("695758677881389178")
    const bigdaddy = guildMcGuild.members.cache.filter(member => !member.user.bot).size;
    const activities = [
      { 
          name: "/help <category>",
          type: ActivityType.Playing,
      },
      { 
          name: "Edd's Fan Club",
          type: ActivityType.Watching,
      },
      { 
          name: "with the children in my basement",
          type: ActivityType.Playing,
      },
      { 
          name: "with commands",
          type: ActivityType.Playing,
      },
      { 
          name: "you",
          type: ActivityType.Watching,
      },
      {
        name: `${bigdaddy} members`,
        type: ActivityType.Watching,
      },
      { 
          name: "Eddie174",
          type: ActivityType.Watching,
      },
      {
        name: "Spotify",
        type: ActivityType.Listening,
      },
      {
        name: "Create a Ticket for Support",
        type: ActivityType.Watching,
      },
      {
        name: "/relationship @c0rrupt3d",
        type: ActivityType.Playing,
      },
    ];

    setInterval(() => {
      const status = Math.floor(Math.random() * activities.length);
      client.user.setActivity(activities[status]);
    }, 10000);
  });
  client.on("warn", (info) => console.log(info));
  client.on("error", console.error);

client.login(process.env.TOKEN).then(() => {
    loadCommands(client);
    loadEvents(client);
});

client.on(Events.InteractionCreate, async interaction => {
  if (interaction.isChatInputCommand()) {
  const command = client.commands.get(interaction.commandName)

  if (!command) {
      interaction.reply({ content: "Command no longer supported." });
  }

  command.execute(interaction, client);
  }
})

const ticketSchema = require("./Schemas/ticketSchema");
client.on(Events.InteractionCreate, async interaction => {

  if (interaction.isButton()) return;
  if (interaction.isChatInputCommand()) return;

  const modal = new ModalBuilder()
  .setTitle("Provide us with more details")
  .setCustomId("modal")

  const reason = new TextInputBuilder()
  .setCustomId("reason")
  .setRequired(true)
  .setLabel("Why did you create this ticket?")
  .setPlaceholder("Provide us with your reason.")
  .setStyle(TextInputStyle.Short)

  const firstActionRow = new ActionRowBuilder().addComponents(reason)

  modal.addComponents(firstActionRow);

  let choices;
  if (interaction.isStringSelectMenu()) {

    choices = interaction.values;

    const result = choices.join("");

    ticketSchema.findOne({ Guild: interaction.guild.id }, async (err, data) => {

      const filter = { Guild: interaction.guild.id };
      const update = { Ticket: result };

      ticketSchema.updateOne(filter, update, {
        new: true
      }).then(value => {
        console.log(value)
      })
    })
  }

  if (!interaction.isModalSubmit()) {
    interaction.showModal(modal)
  }

})



client.on(Events.InteractionCreate, async interaction => {

  if (interaction.isModalSubmit()) {

    if (interaction.customId === "modal") {

      ticketSchema.findOne({ Guild: interaction.guild.id }, async (err, data) => {

        const reasonInput = interaction.fields.getTextInputValue("reason")

        const posChannel = await interaction.guild.channels.cache.find(c => c.name === `ticket-${interaction.user.tag}`);
        if (posChannel) return await interaction.reply({ content: `You already have a ticket open in ${posChannel}`, ephemeral: true });

        const category = data.Channel;
        let channel = await interaction.guild.channels.create({
          name: `ticket-${interaction.user.tag}`,
          type: ChannelType.GuildText,
          parent: `${category}`
        })

        const embed = new EmbedBuilder()
        .setTitle(`Welcome to your ticket, ${interaction.user.username}.`)
        .setDescription("Support is on their way! Please wait patiently while we respond.")
        .setColor("Blurple")
        .addFields({ name: `Ticket Name:`, value: `${channel.name}`})
        .addFields({ name: `Reason:`, value: `${reasonInput}`})
        .addFields({ name: `Ticket Type:`, value: `${data.Ticket}`})

        const button = new ActionRowBuilder()
        .addComponents(
          new ButtonBuilder()
          .setCustomId("ticket")
          .setLabel("Close Ticket")
          .setStyle(ButtonStyle.Danger)
        )


          let msg = await channel.send({ embeds: [embed], components: [button] });
          await interaction.reply({ content: `Your ticket has been created, ${channel}.`, ephemeral: true });

          const collector = msg.createMessageComponentCollector()
          const date = new Date()


          collector.on("collect", async i => {
            if (i.customId == "ticket")
              ;(channel).delete();


            const dmEmbed = new EmbedBuilder()
            .setTitle("Your ticket has been closed.")
            .setDescription("Thank you for contacting us. If you need more help, feel free to create more tickets! Here are the ticket details:")
            .addFields(
              { name: `Ticket Name:`, value: `${channel.name}`, inline: true },
              { name: `Ticket Type:`, value: `${data.Ticket}`, inline: true },
              { name: `Ticket Created:`, value: `<t:${parseInt(channel.createdTimestamp / 1000)}:f>`, inline: true },
              { name: `Created By:`, value: `<@${interaction.user.id}>`, inline: true },
              { name: `Closed By:`, value: `<@${i.user.id}>`, inline: true },
              { name: `Reason:`, value: `${reasonInput}`, inline: true }
            )
            .setColor("Blurple")
            .setFooter({ text: "Ed's Utilities", iconURL: client.user.displayAvatarURL() })


            await channel.send({ content: `<@${i.user.id}>, Ticket has been succesfully been closed.`, ephemeral: true })
            await interaction.member.send({ embeds: [dmEmbed] }).catch(err => {
              return;
            })
          })

      })
    }
  }
})

const afkSchema = require("./Schemas/afkSchema");

client.on(Events.MessageCreate, async message => {
  if (message.author.bot) return;

  const check = await afkSchema.findOne({ Guild: message.guild.id, User: message.author.id });
  if (check) {
    const nick = check.Nickname;
    await afkSchema.deleteMany({ Guild: message.guild.id, User: message.author.id });

    await message.member.setNickname(`${nick}`).catch(err => {
      return;
    })

    const embed3 = new EmbedBuilder()
    .setColor("Blurple")
    .setDescription(`Welcome back, <@${message.author.id}>! Your afk has been removed.`)

    const ml = await message.reply({ embeds: [embed3] });
    setTimeout(() => {
      ml.delete();
    }, 4000)
  } else {

    const members = message.mentions.users.first();
    if (!members) return;
    const Data = await afkSchema.findOne({ Guild: message.guild.id, User: members.id });
    if (!Data) return;

    const member = message.guild.members.cache.get(members.id);

    const afkEmbed = new EmbedBuilder()
    .setColor(0xc72c3b)
    .setDescription(`${member.user.tag} is currently AFK. Don't message them until they remove their AFK.`)

    if (message.content.includes(members)) {
      const m = await message.reply({ embeds: [afkEmbed] });
      setTimeout(() => {
        m.delete();
      }, 4000)
    }
  }
})
```

### Versions

- discord.js 14.8.0
- node.js 18.5.0
- windows 21h2

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildPresences, GuildMessages, DirectMessages, DirectMessageTyping, MessageContent

**Comment by Jiralite** [comment]
If you're unsure about something, you should ask in the [Discord server](https://discord.com/invite/djs) or create a new [discussion](https://github.com/discordjs/discord.js/discussions) as this issue tracker is only for bug reports and enhancement suggestions.
