### ISSUE TITLE
Issue with sending DM

### ISSUE THREAD

**Issue by jdmartin** [discordjs/discord.js#9494]
### Which package is this bug report for?

discord.js

### Issue description

0. I am using discord.js on Node.js v18.16.0.
1. I have a command that takes interaction input via /attendance, and then starts communicating with that user via DM.
2. When I execute that command, I get this error:

```
/home/dev/speedybot/node_modules/discord.js/src/structures/MessagePayload.js:202
        isJSONEncodable(embed) ? embed.toJSON() : this.target.client.options.jsonTransformer(embed),
        ^
TypeError: isJSONEncodable is not a function
    at /home/dev/speedybot/node_modules/discord.js/src/structures/MessagePayload.js:202:9
    at Array.map (<anonymous>)
    at MessagePayload.resolveBody (/home/dev/speedybot/node_modules/discord.js/src/structures/MessagePayload.js:201:36)
    at DMChannel.send (/home/dev/speedybot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:158:61)
    at MessageCollector.<anonymous> (/home/dev/speedybot/slash-commands/attendance.js:46:32)
    at MessageCollector.emit (node:events:513:28)
    at MessageCollector.handleCollect (/home/dev/speedybot/node_modules/discord.js/src/structures/interfaces/Collector.js:133:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
As far as I can tell, this is the relevant section of my (probably janky) code that executes before the error occurs.  This had been working fine for months before the update to 14.10.1

I hope this is enough to get things started.  Please do let me know if I missed a key detail, and I'll get right on it.  Thanks, as always, for discord.js. ❤️ 

### Code sample

```typescript
const { SlashCommandBuilder } = require("@discordjs/builders");

const absence = require("../db/absencedb-slash.js");
const absenceDBHelper = new absence.DataDisplayTools();

const attendanceTools = require("../utils/attendance-utils.js");
const attendanceHelper = new attendanceTools.attendanceTools();

const utils = require("../utils/speedyutils.js");
const client = utils.client;

module.exports = {
    data: new SlashCommandBuilder().setName("attendance").setDescription("Manage your raid attendance!"),

    async execute(interaction) {
        interaction.reply({
            content: "Ok, check your DMs and we'll do this.",
            ephemeral: true,
        });

        const user = client.users.cache.get(interaction.member.user.id);

        const name = interaction.user.username;

        const DM = await interaction.user.send({
            content: `Please choose the number that corresponds to what you want to do.\n  \n\t1. **Show/Cancel** Existing Entries\n\t2. Say You'll Be **Absent** or **Late**...\n\tQ. **Quit**`,
        });

        const collector = DM.channel.createMessageCollector({
            time: 30000,
        });

        var response = "";

        collector.on("collect", (m) => {
        ...
```

### Versions

- discord.js 14.10.1
- node.js 18.16.0
- Linux 6.1.21-v8+ on Raspberry Pi, using Debian 11.7

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Channel, Message, Reaction

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildWebhooks, GuildPresences, GuildMessages, GuildMessageReactions, DirectMessages, DirectMessageReactions, DirectMessageTyping, MessageContent

**Comment by brn-hyn** [comment]
Having the same issue as well `TypeError: isJSONEncodable is not a function`
