### ISSUE TITLE
Cannot start the client: Cannot read properties of null (reading 'destroy')

### ISSUE THREAD

**Issue by Cyberghxst** [discordjs/discord.js#9551]
### Which package is this bug report for?

discord.js

### Issue description

When I try to start my client, I get this error, it only happens with versions 14.10+, If I use 14.9 and earlier, my client does start without any problem.
**Error:**
```
C:\Users\Cyberghxst\Documents\JavaScript\zenet-bot\node_modules\.pnpm\discord.js@14.12.0-dev.1683547467-64324a8.0\node_modules\discord.js\src\client\websocket\WebSocketManager.js:328
    this._ws.destroy({ code: CloseCodes.Normal });
             ^

TypeError: Cannot read properties of null (reading 'destroy')
    at WebSocketManager.destroy (C:\Users\Cyberghxst\Documents\JavaScript\zenet-bot\node_modules\.pnpm\discord.js@14.12.0-dev.1683547467-64324a8.0\node_modules\discord.js\src\client\websocket\WebSocketManager.js:328:14)
    at Zenet.destroy (C:\Users\Cyberghxst\Documents\JavaScript\zenet-bot\node_modules\.pnpm\discord.js@14.12.0-dev.1683547467-64324a8.0\node_modules\discord.js\src\client\Client.js:251:13)
    at Zenet.login (C:\Users\Cyberghxst\Documents\JavaScript\zenet-bot\node_modules\.pnpm\discord.js@14.12.0-dev.1683547467-64324a8.0\node_modules\discord.js\src\client\Client.js:229:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.8.1
```

### Code sample

```typescript
const { Client, ClientOptions, Collection } = require('discord.js'),
    { FileLoader, StatusLoader } = require('./loader.js');

class Zenet extends Client {
    /**
     * @param {ZenetOptions} options 
     */
    constructor(options) {
        super(options);
        this.commands = new Collection();
        this.interactions = new Collection();
        this.events = new Collection();
        this.slash_commands = new Collection();
        this.modules = new FileLoader(this);
        this.options = options;
        this.status = new StatusLoader(this);
        this._init()
    }

    _init() {
        for (const event of [...this.events.values()]) {
            if (event.once) this.once(event.name, (...args) => event.code(this, ...args));
            else this.on(event.name, (...args) => event.code(this, ...args));
        }
        super.login(this.options.token); // This is the line 27.
    }
}

exports.Zenet = Zenet
```

### Versions

- discord.js 14.11.0
- node v19.8.1
- Windows 10 22H2

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages, MessageContent

**Comment by jaw0r3k** [comment]
you shouldnt overwrite options

**Comment by Cyberghxst** [comment]
Okay, thank you!
