### ISSUE TITLE
C:\Users\jacob\Downloads\nope-main\nope-main\node_modules\discord.js\src\client\Client.js:214     if (!token || typeof token !== 'string') throw new Error(ErrorCodes.TokenInvalid)

### ISSUE THREAD

**Issue by PsxScriptsW** [discordjs/discord.js#9658]
### Which package is this bug report for?

discord.js

### Issue description

It just wont work

### Code sample

```typescript
C:\Users\jacob\Downloads\nope-main\nope-main\node_modules\discord.js\src\client\Client.js:214
    if (!token || typeof token !== 'string') throw new Error(ErrorCodes.TokenInvalid);
                                                   ^
Error [TokenInvalid]: An invalid token was provided.
    at Client.login (C:\Users\jacob\Downloads\nope-main\nope-main\node_modules\discord.js\src\client\Client.js:214:52)
    at initialise (C:\Users\jacob\Downloads\nope-main\nope-main\src\discord\discordClient.ts:13:10)
    at Object.<anonymous> (C:\Users\jacob\Downloads\nope-main\nope-main\src\index.ts:8:11)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (C:\Users\jacob\Downloads\nope-main\nope-main\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\jacob\Downloads\nope-main\nope-main\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  [Symbol(code)]: 4
}
```

### Versions

most recent version of evrethying

### Issue priority

Low (slightly annoying)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by PsxScriptsW** [comment]
Its not invalid

**Comment by monbrey** [comment]
Yes, it is. The error only happens when it's invalid.

**The issue tracker is only for bug reports and enhancement suggestions. If you have a question, please ask it in the [Discord server](https://discord.gg/bRCvFy9) instead of opening an issue – you will get redirected there anyway.**

**Comment by PsxScriptsW** [comment]
hey uh i just checked it my bot token is not invalid

**Comment by almostSouji** [comment]
As monbrey already said, this error is thrown by the library if an invalid token is supplied (more specifically, something that is not a string in the stack trace you posted).

This could suggest that your approach to providing the token is not correct, so you may be passing `undefined` or other values to the token. The issue tracker is only for bugs, please join the discord server as https://discord.gg/djs and provide your error and code for further help.

**Comment by PsxScriptsW** [comment]
does anyone know how to log the value you passed in client.login

**Comment by Syjalo** [comment]
```js
client.login(something);
console.log(something); // ?
// or
console.log(await client.login(something));
```
