### ISSUE TITLE
Can't send messages using guildId and channelId from AWS Lambda Function

### ISSUE THREAD

**Issue by fedecastelli** [discordjs/discord.js#9659]
### Which package is this bug report for?

discord.js

### Issue description

I configured an AWS Lambda function that starts each time an event is emitted, create the message with the required information and send it to the desired server and channel. If I 

Everything has been configured using AWS CDK and if I test the script locally, I have no errors and I can send the message correctly. If I test it on the AWS Console, I see this error (even if I receive the message correctly received):

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Cannot read properties of undefined (reading 'handle')",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Cannot read properties of undefined (reading 'handle')",
        "stack": [
            "TypeError: Cannot read properties of undefined (reading 'handle')",
            "    at pW.exports [as MESSAGE_CREATE] (/var/task/index.js:121:4457)",
            "    at lw.handlePacket (/var/task/index.js:126:337)",
            "    at tj.<anonymous> (/var/task/index.js:125:1005)",
            "    at tj.emit (/var/task/index.js:109:2508)",
            "    at hg.<anonymous> (/var/task/index.js:117:302)",
            "    at hg.emit (/var/task/index.js:109:2508)",
            "    at hg.onMessage (/var/task/index.js:115:17830)",
            "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Cannot read properties of undefined (reading 'handle')",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1189:17)",
        "    at process.emit (node:events:513:28)",
        "    at emit (node:internal/process/promises:149:20)",
        "    at processPromiseRejections (node:internal/process/promises:283:27)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}
```

### Code sample

```typescript
dotenv.config();
const client = new Client({
  intents: [
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.Guilds,
    GatewayIntentBits.DirectMessages,
  ],
});
const discordBotToken = process.env.DISCORD_BOT_TOKEN as string;
client.once(Events.ClientReady, () => console.log('Ready!'));

export const lambdaHandler = async (event: EventBridgeEvent<any, any>): Promise<void> => {
  console.log(event);
  try {
    const loginResponse = await client.login(discordBotToken);
    console.log(loginResponse);
    const guildId = 'YOUR_GUILD_ID';
    const channelId = 'YOUR_CHANNEL_ID';

    const guild = await client.guilds.fetch(guildId);
    const channel = guild.channels.cache.get(channelId) as TextChannel;

    if (!channel) throw new Error('Invalid channel ID');
    const response = await channel.send('Test notification');
    await client.destroy();
  } catch (e) {
    // it doesn't reach this part of code. The error is handled somewhere else
    console.error(e);
    await client.destroy();
  }
}
```

### Versions

- discord.js v14.11.0
- node v18.16.0
- typescript v5.1.3

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages, DirectMessages

**Comment by Jiralite** [comment]
Spinning up a WebSocket to send a message isn't really ideal!

You should make use of the core package (without the WebSocket). Check out the independent REST API usage [here](https://github.com/discordjs/discord.js/tree/main/packages/core#independent-rest-api-usage) and feel free to join our [support server](https://discord.gg/djs) for further questions!
