### ISSUE TITLE
[Uncaught Rejection]: Error: Authentication failed 

### ISSUE THREAD

**Issue by AudiRo2993** [discordjs/discord.js#9661]
### Which package is this bug report for?

discord.js

### Issue description

 [Uncaught Rejection]: Error: Authentication failed
Promise {
<rejected> Error: Authentication failed
at WebSocketShard.onClose (/root/Bots/Razen/node_modules/@discordjs/ws/dist/index.js:1035:15)
 at WebSocket.emit (node:events:513:28)
 at WebSocket.emitClose (/root/Bots/Razen/node_modules/ws/lib/websocket.js:258:10)
at TLSSocket.socketOnClose (/root/Bots/Razen/node_modules/ws/lib/websocket.js:1264:15)
 at TLSSocket.emit (node:events:525:35)
at TCP.done (node:_tls_wrap:588:7)
}

I get this error spamming in my console, the bot credentials are right, and the bot is running, however it is slowing it down alot.

### Versions

- discord.js v14.11.0
- nodejs v16.20.0

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

Not applicable

### Which gateway intents are you subscribing to?

Not applicable

**Comment by AudiRo2993** [comment]
I;'m not sure about what is that supposed to mean, im on a team in discord developer portal, the token has been resetted by the team owner
