### ISSUE TITLE
Cannot read properties of undefined (reading 'cache') on Channel Update

### ISSUE THREAD

**Issue by pkdev08** [discordjs/discord.js#9696]
### Which package is this bug report for?

discord.js

### Issue description

Randomly got this error thrown 5 times and those shards never reconnected, had to manually destroy them. Someone else in the support server reported a similar error. Might be due to new media channels?

```xl
TypeError: Cannot read properties of undefined (reading 'cache')
    at ChannelUpdateAction.handle (/home/test/node_modules/discord.js/src/client/actions/ChannelUpdate.js:17:54)
    at module.exports [as CHANNEL_UPDATE] (/home/test/node_modules/discord.js/src/client/websocket/handlers/CHANNEL_UPDATE.js:6:57)
    at WebSocketManager.handlePacket (/home/test/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/test/node_modules/discord.js/src/client/websocket/WebSocketShard.js:493:22)
    at WebSocketShard.onMessage (/home/test/node_modules/discord.js/src/client/websocket/WebSocketShard.js:327:10)
    at callListener (/home/test/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/test/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/test/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
```

### Versions

discord.js 13.16.0
node js 18.16.1

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

User, Channel, GuildMember, Message, Reaction

### Which gateway intents are you subscribing to?

Not applicable

**Comment by KevinNovak** [comment]
+1, also having this issue on a large bot which causes some shards to hard-crash
