### ISSUE TITLE
Error when trying to use discord.js

### ISSUE THREAD

**Issue by Scrapmine** [discordjs/discord.js#9757]
### Which package is this bug report for?

discord.js

### Issue description

1. Run this code `
const { Client, Intents } = require('discord.js');
const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES] });
`
2. Get this error `
        userAgentAppendix: options.rest?.userAgentAppendix
                                        ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/arild/Minecraft/discord-bot/node_modules/discord.js/src/index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
`

### Versions

discord.js@14.12.1
v12.22.9
Linux Mint 21.1 Cinnamon

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMessages

### I have tested this issue on a development release

not tested in dev release

**Comment by Jiralite** [comment]
discord.js requires Node.js version 16.11.0. You can read the guide [here](https://discordjs.guide/preparations).
