### ISSUE TITLE
using @discordjs/proxy-container on docker desktop and got the error Error: connect ETIMEDOUT 108.160.173.207:443

### ISSUE THREAD

**Issue by msnmask** [discordjs/discord.js#9901]
### Which package is this bug report for?

proxy-container

### Issue description

    "discord.js": "^14.13.0",
Node.js v16.19.1.

javaScript project

```
    clientConnect() {
        this.client = new Client({
        intents: [
            GatewayIntentBits.Guilds,
            GatewayIntentBits.GuildMessages,
            GatewayIntentBits.MessageContent,
            GatewayIntentBits.GuildMembers,
        ],
        rest: {
            api: 'http://localhost:8080/api',
        }
    });
        this.client.login(process.env.DISCORD_TOKEN).then(res => {
            console.log('result', res);
            this.server.connect = true;
        }).catch(rej => {
            console.log('reject', rej, '\nreconnecting');
            this.server.connect = false;
            this.clientConnect();
        });
    }
```
the code is here 

got the error :

```
reject Error: connect ETIMEDOUT 157.240.16.50:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '157.240.16.50',
  port: 443
}
reconnecting

```

i run through the two steps guidline on discord.js/packages/proxy-container/README.md
and here is the docker desktop
![image](https://github.com/discordjs/discord.js/assets/58804959/d637d4c6-8756-41b7-89c2-29490952da17)
![image](https://github.com/discordjs/discord.js/assets/58804959/5b5f02c0-0e67-40cb-ad11-abae0b000a53)

![image](https://github.com/discordjs/discord.js/assets/58804959/db93c397-e3cd-4d3d-b50b-e93722cfcfdc)

### Code sample

```typescript
clientConnect() {
        this.client = new Client({
        intents: [
            GatewayIntentBits.Guilds,
            GatewayIntentBits.GuildMessages,
            GatewayIntentBits.MessageContent,
            GatewayIntentBits.GuildMembers,
        ],
        rest: {
            api: 'http://localhost:8080/api',
        }
    });
        this.client.login(process.env.DISCORD_TOKEN).then(res => {
            console.log('result', res);
            this.server.connect = true;
        }).catch(rej => {
            console.log('reject', rej, '\nreconnecting');
            this.server.connect = false;
            this.clientConnect();
        });
    }
```

### Versions

    "discord.js": "^14.13.0",
Node.js v16.19.1.

### Issue priority

High (immediate attention needed)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers, GuildMessages

**Comment by didinele** [comment]
This is a networking issue on your end. From what I can gather, you're also running your bot in docker? If so, `localhost` won't behave like you expect it to by default. I recommend reading up on this: https://docs.docker.com/network

Either way, your code sample is not enough for us to reproduce this issue.

**Comment by msnmask** [comment]
2023-10-19 15:04:11 node:internal/process/promises:288
2023-10-19 15:04:11             triggerUncaughtException(err, true /* fromPromise */);
2023-10-19 15:04:11             ^
2023-10-19 15:04:11
2023-10-19 15:04:11 Error: Client network socket disconnected before secure TLS connection was established
2023-10-19 15:04:11     at connResetException (node:internal/errors:720:14)
2023-10-19 15:04:12 Listening on port 8080
2023-10-19 15:04:24 Listening on port 8080
2023-10-19 15:04:11     at TLSSocket.onConnectEnd (node:_tls_wrap:1655:19)
2023-10-19 15:04:11     at TLSSocket.emit (node:events:529:35)
2023-10-19 15:04:11     at endReadableNT (node:internal/streams/readable:1368:12)
2023-10-19 15:04:11     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2023-10-19 15:04:11   code: 'ECONNRESET',
2023-10-19 15:04:11   path: undefined,
2023-10-19 15:04:11   host: 'discord.com',
2023-10-19 15:04:11   port: 443,
2023-10-19 15:04:11   localAddress: null
2023-10-19 15:04:11 }
2023-10-19 15:04:11
2023-10-19 15:04:11 Node.js v18.18.2
2023-10-19 15:04:23 node:internal/process/promises:288
2023-10-19 15:04:23             triggerUncaughtException(err, true /* fromPromise */);
2023-10-19 15:04:23             ^
2023-10-19 15:04:23
2023-10-19 15:04:23 ConnectTimeoutError: Connect Timeout Error
2023-10-19 15:04:23     at onConnectTimeout ***@***.***/node_modules/undici/lib/core/connect.js:186:24)
2023-10-19 15:04:23     at ***@***.***/node_modules/undici/lib/core/connect.js:133:46
2023-10-19 15:04:23     at Immediate._onImmediate ***@***.***/node_modules/undici/lib/core/connect.js:174:9)
2023-10-19 15:04:23     at process.processImmediate (node:internal/timers:476:21) {
2023-10-19 15:04:23   code: 'UND_ERR_CONNECT_TIMEOUT'
2023-10-19 15:04:23 }
2023-10-19 15:04:23
2023-10-19 15:04:23 Node.js v18.18.2
ok..so what is this then ?this is from your docker contiainer . inside ,your docker contianer .
i done these :
first , [cid:8c7f3c8e-7093-4105-b563-d63fb301d659]
the docker config .

{
  "credsStore": "desktop",
  "proxies": {
    "default": {
      "httpProxy": "http://127.0.0.1:7890",
      "httpsProxy": "http://127.0.0.1:7890"
    }
  }
}

and im using clash to open the proxy on http://127.0.0.1:7890 like this
[cid:05bddda3-4d26-4740-963e-d684707388e6]
so ... what is wrong . i dont understand ..
________________________________
发件人: DD ***@***.***>
发送时间: 2023年10月19日 0:24
收件人: discordjs/discord.js ***@***.***>
抄送: msnmask ***@***.***>; Author ***@***.***>
主题: Re: [discordjs/discord.js] using @discordjs/proxy-container on docker desktop and got the error Error: connect ETIMEDOUT 108.160.173.207:443 (Issue #9901)


This is a networking issue on your end. From what I can gather, you're also running your bot in docker? If so, localhost won't behave like you expect it to by default. I recommend reading up on this: https://docs.docker.com/network

Either way, your code sample is not enough for us to reproduce this issue.

―

**Comment by Jiralite** [comment]
- #9904 
- https://discord.com/channels/222078108977594368/1164501957587783710
