### ISSUE TITLE
Localizations responds with Unhandled Rejection

### ISSUE THREAD

**Issue by CameronMitchell1020** [discordjs/discord.js#9911]
### Which package is this bug report for?

discord.js

### Issue description

1. Create a slash command builder and add localizations with .setDescription/NameLocalizations
2. Run the bot
3. Gives unhandled rejection when trying to register commands
4. Unhandled Rejection at: Promise {
  <rejected> ExpectedConstraintError > s.string.regex
    Invalid string format

    Expected: expected /^[\p{Ll}\p{Lm}\p{Lo}\p{N}\p{sc=Devanagari}\p{sc=Thai}_-]+$/u.test(expected) to be true

    Received:
    | 'Версия'

      at Object.run (E:\TeamBG4.0\node_modules\@sapphire\shapeshift\dist\index.js:1592:64)
      at E:\TeamBG4.0\node_modules\@sapphire\shapeshift\dist\index.js:212:66
      at Array.reduce (<anonymous>)
      at StringValidator.parse (E:\TeamBG4.0\node_modules\@sapphire\shapeshift\dist\index.js:212:29)
      at validateName (E:\TeamBG4.0\node_modules\@discordjs\builders\dist\index.js:1428:17)
      at MixedClass.setNameLocalization (E:\TeamBG4.0\node_modules\@discordjs\builders\dist\index.js:1557:5)
      at MixedClass.setNameLocalizations (E:\TeamBG4.0\node_modules\@discordjs\builders\dist\index.js:1573:12)
      at Object.<anonymous> (E:\TeamBG4.0\src\commands\Community\version.js:6:8)
      at Module._compile (node:internal/modules/cjs/loader:1241:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
} reason: ExpectedConstraintError > s.string.regex
  Invalid string format

  Expected: expected /^[\p{Ll}\p{Lm}\p{Lo}\p{N}\p{sc=Devanagari}\p{sc=Thai}_-]+$/u.test(expected) to be true

  Received:
  | 'Версия'

    at Object.run (E:\TeamBG4.0\node_modules\@sapphire\shapeshift\dist\index.js:1592:64)
    at E:\TeamBG4.0\node_modules\@sapphire\shapeshift\dist\index.js:212:66
    at Array.reduce (<anonymous>)
    at StringValidator.parse (E:\TeamBG4.0\node_modules\@sapphire\shapeshift\dist\index.js:212:29)
    at validateName (E:\TeamBG4.0\node_modules\@discordjs\builders\dist\index.js:1428:17)
    at MixedClass.setNameLocalization (E:\TeamBG4.0\node_modules\@discordjs\builders\dist\index.js:1557:5)
    at MixedClass.setNameLocalizations (E:\TeamBG4.0\node_modules\@discordjs\builders\dist\index.js:1573:12)
    at Object.<anonymous> (E:\TeamBG4.0\src\commands\Community\version.js:6:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

### Code sample

```typescript
const { SlashCommandBuilder, EmbedBuilder} = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
      .setName(`version`)
      .setNameLocalizations({ ru: 'Версия' })
      .setDescription(`Gives the version of the bot`)
      .setDescriptionLocalizations({ ru: 'Выдает версию бота' }),
```

### Versions

discord.js@14.12.1
node.js v20.9.0
Microsoft Windows [Version 10.0.19045.3570]

### Issue priority

Medium (should be fixed soon)

### Which partials do you have configured?

No Partials

### Which gateway intents are you subscribing to?

Guilds, GuildMembers

### I have tested this issue on a development release

e80194e3f

**Comment by almeidx** [comment]
Command names (including the localized ones) must be lowercase
